// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
memcpy((void*)0x20000880, "/dev/loop-control\000", 18);
	res = syscall(__NR_openat, 0xffffffffffffff9cul, 0x20000880ul, 0ul, 0ul);
	if (res != -1)
		r[0] = res;
memcpy((void*)0x20000080, "system.posix_acl_access\000", 24);
*(uint32_t*)0x20000300 = 2;
*(uint16_t*)0x20000304 = 1;
*(uint16_t*)0x20000306 = 0;
*(uint32_t*)0x20000308 = 0;
*(uint16_t*)0x2000030c = 4;
*(uint16_t*)0x2000030e = 0;
*(uint32_t*)0x20000310 = 0;
*(uint16_t*)0x20000314 = 8;
*(uint16_t*)0x20000316 = 0;
*(uint32_t*)0x20000318 = -1;
*(uint16_t*)0x2000031c = 0x10;
*(uint16_t*)0x2000031e = 0;
*(uint32_t*)0x20000320 = 0;
*(uint16_t*)0x20000324 = 0x20;
*(uint16_t*)0x20000326 = 0;
*(uint32_t*)0x20000328 = 0;
	syscall(__NR_fsetxattr, r[0], 0x20000080ul, 0x20000300ul, 0x2cul, 0ul);
	return 0;
}
