// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

#ifndef __NR_close_range
#define __NR_close_range 436
#endif

uint64_t r[5] = {0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socketpair, 1ul, 5ul, 0, 0x20000d00ul);
	if (res != -1)
r[0] = *(uint32_t*)0x20000d04;
memcpy((void*)0x20000000, "/dev/snd/seq\000", 13);
	res = syscall(__NR_openat, 0xffffffffffffff9cul, 0x20000000ul, 0ul, 0);
	if (res != -1)
		r[1] = res;
	res = syscall(__NR_socketpair, 1ul, 5ul, 0, 0x20000d00ul);
	if (res != -1) {
r[2] = *(uint32_t*)0x20000d00;
r[3] = *(uint32_t*)0x20000d04;
	}
	syscall(__NR_getpid);
	res = syscall(__NR_socketpair, 1ul, 1ul, 0, 0x20000080ul);
	if (res != -1)
r[4] = *(uint32_t*)0x20000084;
	syscall(__NR_socketpair, 1ul, 5ul, 0, 0x20000d00ul);
*(uint64_t*)0x20001440 = 0;
*(uint32_t*)0x20001448 = 0;
*(uint64_t*)0x20001450 = 0;
*(uint64_t*)0x20001458 = 0;
*(uint64_t*)0x20001460 = 0x200000c0;
*(uint64_t*)0x200000c0 = 0x20;
*(uint32_t*)0x200000c8 = 1;
*(uint32_t*)0x200000cc = 1;
*(uint32_t*)0x200000d0 = r[4];
*(uint32_t*)0x200000d4 = r[0];
*(uint32_t*)0x200000d8 = r[4];
*(uint32_t*)0x200000dc = r[2];
*(uint64_t*)0x20001468 = 0x20;
*(uint32_t*)0x20001470 = 0;
	syscall(__NR_sendmsg, r[3], 0x20001440ul, 0ul);
	syscall(__NR_close_range, r[1], -1, 0ul);
	return 0;
}
