// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

#define BITMASK(bf_off,bf_len) (((1ull << (bf_len)) - 1) << (bf_off))
#define STORE_BY_BITMASK(type,htobe,addr,val,bf_off,bf_len) *(type*)(addr) = htobe((htobe(*(type*)(addr)) & ~BITMASK((bf_off), (bf_len))) | (((type)(val) << (bf_off)) & BITMASK((bf_off), (bf_len))))

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socket, 0x10ul, 3ul, 0xc);
	if (res != -1)
		r[0] = res;
*(uint64_t*)0x20000f40 = 0;
*(uint32_t*)0x20000f48 = 0;
*(uint64_t*)0x20000f50 = 0x20000f00;
*(uint64_t*)0x20000f00 = 0x20000dc0;
*(uint32_t*)0x20000dc0 = 0x24;
*(uint8_t*)0x20000dc4 = 1;
*(uint8_t*)0x20000dc5 = 1;
*(uint16_t*)0x20000dc6 = 0x101;
*(uint32_t*)0x20000dc8 = 0;
*(uint32_t*)0x20000dcc = 0;
*(uint8_t*)0x20000dd0 = 0;
*(uint8_t*)0x20000dd1 = 0;
*(uint16_t*)0x20000dd2 = htobe16(0);
*(uint16_t*)0x20000dd4 = 4;
STORE_BY_BITMASK(uint16_t, , 0x20000dd6, 2, 0, 14);
STORE_BY_BITMASK(uint16_t, , 0x20000dd7, 0, 6, 1);
STORE_BY_BITMASK(uint16_t, , 0x20000dd7, 1, 7, 1);
*(uint16_t*)0x20000dd8 = 0xc;
STORE_BY_BITMASK(uint16_t, , 0x20000dda, 0x19, 0, 14);
STORE_BY_BITMASK(uint16_t, , 0x20000ddb, 0, 6, 1);
STORE_BY_BITMASK(uint16_t, , 0x20000ddb, 1, 7, 1);
*(uint16_t*)0x20000ddc = 8;
*(uint16_t*)0x20000dde = 2;
*(uint32_t*)0x20000de0 = 0x216;
*(uint64_t*)0x20000f08 = 0x24;
*(uint64_t*)0x20000f58 = 1;
*(uint64_t*)0x20000f60 = 0;
*(uint64_t*)0x20000f68 = 0;
*(uint32_t*)0x20000f70 = 0;
	syscall(__NR_sendmsg, r[0], 0x20000f40ul, 0ul);
	return 0;
}
