// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
memcpy((void*)0x200000c0, "/dev/snd/seq\000", 13);
	res = syscall(__NR_openat, 0xffffffffffffff9cul, 0x200000c0ul, 0ul, 0);
	if (res != -1)
		r[0] = res;
*(uint8_t*)0x200002c0 = 0;
*(uint8_t*)0x200002c1 = 0;
*(uint8_t*)0x200002c2 = 0;
*(uint8_t*)0x200002c3 = 0;
*(uint32_t*)0x200002c4 = 0;
*(uint32_t*)0x200002c8 = 0;
*(uint8_t*)0x200002cc = 0;
memset((void*)0x200002cd, 0, 3);
memset((void*)0x200002d0, 0, 64);
	syscall(__NR_ioctl, r[0], 0xc0505350, 0x200002c0ul);
	return 0;
}
