// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[2] = {0xffffffffffffffff, 0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
memcpy((void*)0x20000000, "/dev/autofs\000", 12);
	res = syscall(__NR_openat, 0xffffffffffffff9cul, 0x20000000ul, 0ul, 0ul);
	if (res != -1)
		r[0] = res;
*(uint32_t*)0x20000100 = 1;
*(uint32_t*)0x20000104 = 1;
*(uint32_t*)0x20000108 = 0x18;
*(uint32_t*)0x2000010c = r[0];
memcpy((void*)0x20000118, "./file0\000", 8);
	res = syscall(__NR_ioctl, r[0], 0xc0189375, 0x20000100ul);
	if (res != -1)
r[1] = *(uint32_t*)0x2000010c;
memcpy((void*)0x20000040, "/dev/autofs\000", 12);
	syscall(__NR_openat, 0xffffffffffffff9cul, 0x20000040ul, 0ul, 0ul);
	syscall(__NR_read, r[1], 0ul, 0ul);
	return 0;
}
