// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

#ifndef __NR_io_uring_setup
#define __NR_io_uring_setup 425
#endif
#ifndef __NR_pkey_mprotect
#define __NR_pkey_mprotect 329
#endif

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
*(uint32_t*)0x20000d84 = 0;
*(uint32_t*)0x20000d88 = 0;
*(uint32_t*)0x20000d8c = 0;
*(uint32_t*)0x20000d90 = 0;
*(uint32_t*)0x20000d98 = -1;
memset((void*)0x20000d9c, 0, 12);
	res = syscall(__NR_io_uring_setup, 0x643e, 0x20000d80ul);
	if (res != -1)
		r[0] = res;
	syscall(__NR_mmap, 0x203fd000ul, 0xc00000ul, 0ul, 0x12ul, r[0], 0ul);
	syscall(__NR_pkey_mprotect, 0x20a2e000ul, 0x2000ul, 0x1000000ul, -1);
	return 0;
}
