// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <fcntl.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

static long syz_open_dev(volatile long a0, volatile long a1, volatile long a2)
{
	if (a0 == 0xc || a0 == 0xb) {
		char buf[128];
		sprintf(buf, "/dev/%s/%d:%d", a0 == 0xc ? "char" : "block", (uint8_t)a1, (uint8_t)a2);
		return open(buf, O_RDWR, 0);
	} else {
		char buf[1024];
		char* hash;
		strncpy(buf, (char*)a0, sizeof(buf) - 1);
		buf[sizeof(buf) - 1] = 0;
		while ((hash = strchr(buf, '#'))) {
			*hash = '0' + (char)(a1 % 10);
			a1 /= 10;
		}
		return open(buf, a2, 0);
	}
}

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
memcpy((void*)0x20000700, "/dev/sg#\000", 9);
	res = -1;
res = syz_open_dev(0x20000700, 0x8000001000, 0);
	if (res != -1)
		r[0] = res;
*(uint32_t*)0x200000c0 = 0xfffffeb9;
*(uint32_t*)0x200000c4 = 0;
*(uint32_t*)0x200000c8 = 0;
memcpy((void*)0x200000cc, "\x29\x9e\x64\xfa\x02\x21\xe9\x58\x4b\x7f\x04\x26\xc4\x87\xfe\x5f\x2d\x18\xb6\x20\x66\x40\xff\xa9\xc2\xd2\x89\x7a\x9b\x96\xac\x5b\xb6\xc5\x83\x6b\x2c\xdd\x32\x2d\x42\xbc\xdd\xc0\x64\x96\x0d\xeb\x28\x42\x22\x36\x21\x01\x00\x00\x00\x01\x00\x00\x00\x93\xb8\xfd\x5a\xcd\xf9\x07\x6c\xcc\xbb\xae\x50\xf4\x6f\x5b\x24\xd8\xeb\xbc\x55\x47\x3d\x48\xee\x4e\x3d\xdf\x9c\xf5\x7c\x35\x90\xd8\xeb\x0b\xee\x27\xce\x8d\xd0\x5e\xa1\xaf\x78\xd1\x89\x05\x0a\xd9\xb3\xc1\xcd\x93\xc5\xa2\x93\x0e", 118);
	syscall(__NR_ioctl, r[0], 1, 0x200000c0ul);
	return 0;
}
