// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_pipe2, 0x20000000ul, 0ul);
	if (res != -1)
r[0] = *(uint32_t*)0x20000004;
*(uint32_t*)0x20000200 = 0x43;
*(uint8_t*)0x20000204 = 9;
*(uint16_t*)0x20000205 = 0;
*(uint32_t*)0x20000207 = 0;
*(uint32_t*)0x2000020b = 0;
*(uint64_t*)0x2000020f = 0;
*(uint64_t*)0x20000217 = 0;
*(uint64_t*)0x2000021f = 0;
*(uint64_t*)0x20000227 = 0;
*(uint64_t*)0x2000022f = 0;
*(uint64_t*)0x20000237 = 0;
*(uint32_t*)0x2000023f = 0;
	syscall(__NR_write, r[0], 0x20000200ul, 0x43ul);
*(uint32_t*)0x20000040 = 0x14;
*(uint8_t*)0x20000044 = 0x11;
*(uint16_t*)0x20000045 = 0;
*(uint8_t*)0x20000047 = 0;
*(uint32_t*)0x20000048 = 0;
*(uint64_t*)0x2000004c = 0;
	syscall(__NR_write, r[0], 0x20000040ul, 0x14ul);
	return 0;
}
