// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[2] = {0xffffffffffffffff, 0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
memcpy((void*)0x20000040, "./file0\000", 8);
	syscall(__NR_mknod, 0x20000040ul, 0x1000ul, 0x700);
memcpy((void*)0x20000000, "./file0\000", 8);
	res = syscall(__NR_openat, 0xffffff9c, 0x20000000ul, 0x60800ul, 0ul);
	if (res != -1)
		r[0] = res;
*(uint32_t*)0x20000200 = r[0];
*(uint16_t*)0x20000204 = 1;
*(uint16_t*)0x20000206 = 0;
	syscall(__NR_ppoll, 0x20000200ul, 1ul, 0ul, 0ul, 0ul);
memcpy((void*)0x200002c0, "./file0\000", 8);
	res = syscall(__NR_creat, 0x200002c0ul, 0ul);
	if (res != -1)
		r[1] = res;
	syscall(__NR_write, r[1], 0ul, 0x5bful);
	return 0;
}
