// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[4] = {0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_epoll_create, 0xc744);
	if (res != -1)
		r[0] = res;
	res = syscall(__NR_epoll_create, 0x100);
	if (res != -1)
		r[1] = res;
*(uint32_t*)0x20000100 = 0;
*(uint64_t*)0x20000104 = 0;
	syscall(__NR_epoll_ctl, r[1], 1ul, r[0], 0x20000100ul);
	res = syscall(__NR_socket, 2ul, 3ul, 1);
	if (res != -1)
		r[2] = res;
	res = syscall(__NR_epoll_create, 1);
	if (res != -1)
		r[3] = res;
*(uint32_t*)0x20000080 = 0;
*(uint64_t*)0x20000084 = 0;
	syscall(__NR_epoll_ctl, r[3], 1ul, r[2], 0x20000080ul);
*(uint32_t*)0x20000000 = 0;
*(uint64_t*)0x20000004 = 0;
	syscall(__NR_epoll_ctl, r[0], 1ul, r[2], 0x20000000ul);
	return 0;
}
