// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[2] = {0xffffffffffffffff, 0x0};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socketpair, 1ul, 1ul, 0, 0x20000040ul);
	if (res != -1)
r[0] = *(uint32_t*)0x20000044;
	res = syscall(__NR_gettid);
	if (res != -1)
		r[1] = res;
*(uint64_t*)0x20003040 = 0;
*(uint32_t*)0x20003048 = 0;
*(uint64_t*)0x20003050 = 0x20000880;
*(uint64_t*)0x20000880 = 0x20000200;
memset((void*)0x20000200, 126, 1);
*(uint64_t*)0x20000888 = 1;
*(uint64_t*)0x20003058 = 1;
*(uint64_t*)0x20003060 = 0x20000100;
*(uint64_t*)0x20000100 = 0x1c;
*(uint32_t*)0x20000108 = 1;
*(uint32_t*)0x2000010c = 2;
*(uint32_t*)0x20000110 = r[1];
*(uint32_t*)0x20000114 = 0xee01;
*(uint32_t*)0x20000118 = 0;
*(uint64_t*)0x20003068 = 0x20;
*(uint32_t*)0x20003070 = 0;
*(uint32_t*)0x20003078 = 0;
	syscall(__NR_sendmmsg, r[0], 0x20003040ul, 1ul, 0ul);
	return 0;
}
