// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socket, 0x10ul, 3ul, 6);
	if (res != -1)
		r[0] = res;
*(uint64_t*)0x200000c0 = 0;
*(uint32_t*)0x200000c8 = 0;
*(uint64_t*)0x200000d0 = 0x20000080;
*(uint64_t*)0x20000080 = 0x20000240;
*(uint32_t*)0x20000240 = 0xb8;
*(uint16_t*)0x20000244 = 0x13;
*(uint16_t*)0x20000246 = 1;
*(uint32_t*)0x20000248 = 0;
*(uint32_t*)0x2000024c = 0;
*(uint8_t*)0x20000250 = 0xac;
*(uint8_t*)0x20000251 = 0x1e;
*(uint8_t*)0x20000252 = 0;
*(uint8_t*)0x20000253 = 1;
*(uint32_t*)0x20000260 = htobe32(0x7f000001);
*(uint16_t*)0x20000270 = htobe16(0);
*(uint16_t*)0x20000272 = htobe16(0);
*(uint16_t*)0x20000274 = htobe16(0);
*(uint16_t*)0x20000276 = htobe16(0);
*(uint16_t*)0x20000278 = 0xa;
*(uint8_t*)0x2000027a = 0;
*(uint8_t*)0x2000027b = 0xa0;
*(uint8_t*)0x2000027c = 0;
*(uint32_t*)0x20000280 = 0;
*(uint32_t*)0x20000284 = 0;
*(uint64_t*)0x20000288 = 0;
*(uint64_t*)0x20000290 = 0;
*(uint64_t*)0x20000298 = 0;
*(uint64_t*)0x200002a0 = 0;
*(uint64_t*)0x200002a8 = 0;
*(uint64_t*)0x200002b0 = 0;
*(uint64_t*)0x200002b8 = 0;
*(uint64_t*)0x200002c0 = 0;
*(uint64_t*)0x200002c8 = 0;
*(uint64_t*)0x200002d0 = 0;
*(uint64_t*)0x200002d8 = 0;
*(uint64_t*)0x200002e0 = 0;
*(uint32_t*)0x200002e8 = 0;
*(uint32_t*)0x200002ec = 0;
*(uint8_t*)0x200002f0 = 0;
*(uint8_t*)0x200002f1 = 0;
*(uint8_t*)0x200002f2 = 0;
*(uint8_t*)0x200002f3 = 0;
*(uint64_t*)0x20000088 = 0xb8;
*(uint64_t*)0x200000d8 = 1;
*(uint64_t*)0x200000e0 = 0;
*(uint64_t*)0x200000e8 = 0;
*(uint32_t*)0x200000f0 = 0;
	syscall(__NR_sendmsg, r[0], 0x200000c0ul, 0ul);
	return 0;
}
