// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <sched.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

#define USLEEP_FORKED_CHILD (3 * 50 *1000)

static long handle_clone_ret(long ret)
{
	if (ret != 0) {
		return ret;
	}
	usleep(USLEEP_FORKED_CHILD);
	syscall(__NR_exit, 0);
	while (1) {
	}
}

static long syz_clone(volatile long flags, volatile long stack, volatile long stack_len,
		      volatile long ptid, volatile long ctid, volatile long tls)
{
	long sp = (stack + stack_len) & ~15;
	long ret = (long)syscall(__NR_clone, flags & ~CLONE_VM, sp, ptid, ctid, tls);
	return handle_clone_ret(ret);
}

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);

syz_clone(0, 0, 0, 0, 0, 0);
memcpy((void*)0x20000100, "\x33\x02\x2e\x14\x64\x66\x92\x77\x9e\x8b\x87\xfe\x60\x4d\x8b\x5b\x48\x38\xca\x34\x16\x3a\x8f\x95\x19\x05\x9b\x34\x1d\x46\xec\x42\xa0\x22\xdf\x0f\x92\x3f\x4b\x56\x77\x48\x0e\xe4\xcb\x7f\x63\x7d\xdb\xb6\xea\x39\x22\x23\x85\x04\x90\x80\x3f\xdf\x2b\xe2\xd0\xde\x7a\x6c\x3f\x90\x0d\x4d\xaa\xf9\xca\xf3\xf0\x62\xad\xe3\x26\xec\x90\xd5\xf8\x2f\xe9\x1c\xae\x59\x25\x74\xbc\x0a\x92\x57\xdf\x79\x5b\xe9\xab\x61\x33\x30\x45\xad\xa3\x86\x99\x44\x60\xcf\xbe\x55\x02\x3b\x74\xe7\xe8\x81\xab\x82\x0d\xb6\xe4\x9b\xa7\xcc\xea\x58\x93\x15\x74\xad\x82\xcf\x95\x4a\x5a\xcd\x8d\x34\xf7\xc6\x3a\x38\x68\x36\xdb", 147);
syz_clone(0, 0, 0, 0, 0x200000c0, 0x20000100);
	return 0;
}
