// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
memcpy((void*)0x20000800, "./file0\000", 8);
	res = syscall(__NR_creat, 0x20000800ul, 0ul);
	if (res != -1)
		r[0] = res;
	syscall(__NR_ioctl, r[0], 0x40086602, 0ul);
*(uint32_t*)0x20000380 = 7;
*(uint8_t*)0x20000384 = 0x7f;
*(uint16_t*)0x20000385 = 0;
	syscall(__NR_write, r[0], 0x20000380ul, 7ul);
*(uint32_t*)0x20000180 = 0;
	syscall(__NR_ioctl, r[0], 1, 0x20000180ul);
	return 0;
}
