// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socket, 0xaul, 2ul, 0x88);
	if (res != -1)
		r[0] = res;
*(uint8_t*)0x20000200 = 0;
*(uint8_t*)0x20000201 = 0;
*(uint8_t*)0x20000202 = 4;
*(uint8_t*)0x20000203 = 0;
*(uint8_t*)0x20000204 = 0;
*(uint8_t*)0x20000205 = 0;
*(uint16_t*)0x20000206 = 0;
*(uint8_t*)0x20000208 = 0xfe;
*(uint8_t*)0x20000209 = 0x80;
memset((void*)0x2000020a, 0, 13);
*(uint8_t*)0x20000217 = 0xbb;
memset((void*)0x20000218, 0, 10);
memset((void*)0x20000222, 255, 2);
*(uint32_t*)0x20000224 = htobe32(0x7f000001);
*(uint8_t*)0x20000228 = -1;
*(uint8_t*)0x20000229 = 2;
memset((void*)0x2000022a, 0, 13);
*(uint8_t*)0x20000237 = 1;
*(uint8_t*)0x20000238 = 0xfe;
*(uint8_t*)0x20000239 = 0x80;
memset((void*)0x2000023a, 0, 13);
*(uint8_t*)0x20000247 = 0xbb;
*(uint8_t*)0x20000248 = -1;
*(uint8_t*)0x20000249 = 1;
memset((void*)0x2000024a, 0, 13);
*(uint8_t*)0x20000257 = 1;
*(uint8_t*)0x20000258 = 0xfe;
*(uint8_t*)0x20000259 = 0x80;
memset((void*)0x2000025a, 0, 13);
*(uint8_t*)0x20000267 = 0;
*(uint8_t*)0x20000268 = 0xfc;
*(uint8_t*)0x20000269 = 1;
memset((void*)0x2000026a, 0, 13);
*(uint8_t*)0x20000277 = 0;
*(uint8_t*)0x20000278 = 0xfe;
*(uint8_t*)0x20000279 = 0x80;
memset((void*)0x2000027a, 0, 13);
*(uint8_t*)0x20000287 = 0xaa;
	syscall(__NR_setsockopt, r[0], 0x29, 0x36, 0x20000200ul, 0xc2ul);
	return 0;
}
