// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
memcpy((void*)0x200002c0, "/sys/power/pm_print_times", 25);
	res = syscall(__NR_openat, 0xffffffffffffff9cul, 0x200002c0ul, 0x82001ul, 0ul);
	if (res != -1)
		r[0] = res;
*(uint32_t*)0x20000040 = 0x37;
*(uint8_t*)0x20000044 = 7;
*(uint16_t*)0x20000045 = 0;
*(uint16_t*)0x20000047 = 0x2a;
memcpy((void*)0x20000049, "\000\000\271\230\350\241\237_)>\236\227\253\355Yn\251\t\000\212\003\000\340\000\000\000\000\000\000\000\331\000*\300g\223\221FI\273\303\257", 42);
*(uint32_t*)0x20000073 = 0;
	syscall(__NR_write, r[0], 0x20000040ul, 0x37ul);
	return 0;
}
