// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <errno.h>
#include <fcntl.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/ioctl.h>
#include <sys/mount.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

#include <linux/loop.h>

#ifndef __NR_memfd_create
#define __NR_memfd_create 319
#endif

static unsigned long long procid;

static long syz_open_dev(volatile long a0, volatile long a1, volatile long a2)
{
	if (a0 == 0xc || a0 == 0xb) {
		char buf[128];
		sprintf(buf, "/dev/%s/%d:%d", a0 == 0xc ? "char" : "block", (uint8_t)a1, (uint8_t)a2);
		return open(buf, O_RDWR, 0);
	} else {
		char buf[1024];
		char* hash;
		strncpy(buf, (char*)a0, sizeof(buf) - 1);
		buf[sizeof(buf) - 1] = 0;
		while ((hash = strchr(buf, '#'))) {
			*hash = '0' + (char)(a1 % 10);
			a1 /= 10;
		}
		return open(buf, a2, 0);
	}
}

struct fs_image_segment {
	void* data;
	uintptr_t size;
	uintptr_t offset;
};
static int setup_loop_device(long unsigned size, long unsigned nsegs, struct fs_image_segment* segs, const char* loopname, int* memfd_p, int* loopfd_p)
{
	int err = 0, loopfd = -1;
	int memfd = syscall(__NR_memfd_create, "syzkaller", 0);
	if (memfd == -1) {
		err = errno;
		goto error;
	}
	if (ftruncate(memfd, size)) {
		err = errno;
		goto error_close_memfd;
	}
	for (size_t i = 0; i < nsegs; i++) {
		if (pwrite(memfd, segs[i].data, segs[i].size, segs[i].offset) < 0) {
		}
	}
	loopfd = open(loopname, O_RDWR);
	if (loopfd == -1) {
		err = errno;
		goto error_close_memfd;
	}
	if (ioctl(loopfd, LOOP_SET_FD, memfd)) {
		if (errno != EBUSY) {
			err = errno;
			goto error_close_loop;
		}
		ioctl(loopfd, LOOP_CLR_FD, 0);
		usleep(1000);
		if (ioctl(loopfd, LOOP_SET_FD, memfd)) {
			err = errno;
			goto error_close_loop;
		}
	}
	*memfd_p = memfd;
	*loopfd_p = loopfd;
	return 0;

error_close_loop:
	close(loopfd);
error_close_memfd:
	close(memfd);
error:
	errno = err;
	return -1;
}

static long syz_mount_image(volatile long fsarg, volatile long dir, volatile unsigned long size, volatile unsigned long nsegs, volatile long segments, volatile long flags, volatile long optsarg, volatile long change_dir)
{
	struct fs_image_segment* segs = (struct fs_image_segment*)segments;
	int res = -1, err = 0, loopfd = -1, memfd = -1, need_loop_device = !!segs;
	char* mount_opts = (char*)optsarg;
	char* target = (char*)dir;
	char* fs = (char*)fsarg;
	char* source = NULL;
	char loopname[64];
	if (need_loop_device) {
		memset(loopname, 0, sizeof(loopname));
		snprintf(loopname, sizeof(loopname), "/dev/loop%llu", procid);
		if (setup_loop_device(size, nsegs, segs, loopname, &memfd, &loopfd) == -1)
			return -1;
		source = loopname;
	}
	mkdir(target, 0777);
	char opts[256];
	memset(opts, 0, sizeof(opts));
	if (strlen(mount_opts) > (sizeof(opts) - 32)) {
	}
	strncpy(opts, mount_opts, sizeof(opts) - 32);
	if (strcmp(fs, "iso9660") == 0) {
		flags |= MS_RDONLY;
	} else if (strncmp(fs, "ext", 3) == 0) {
		if (strstr(opts, "errors=panic") || strstr(opts, "errors=remount-ro") == 0)
			strcat(opts, ",errors=continue");
	} else if (strcmp(fs, "xfs") == 0) {
		strcat(opts, ",nouuid");
	}
	res = mount(source, target, fs, flags, opts);
	if (res == -1) {
		err = errno;
		goto error_clear_loop;
	}
	res = open(target, O_RDONLY | O_DIRECTORY);
	if (res == -1) {
		err = errno;
		goto error_clear_loop;
	}
	if (change_dir) {
		res = chdir(target);
		if (res == -1) {
			err = errno;
		}
	}

error_clear_loop:
	if (need_loop_device) {
		ioctl(loopfd, LOOP_CLR_FD, 0);
		close(loopfd);
		close(memfd);
	}
	errno = err;
	return res;
}

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
*(uint8_t*)0x20000000 = 0xac;
*(uint8_t*)0x20000001 = 0x14;
*(uint8_t*)0x20000002 = 0x14;
*(uint8_t*)0x20000003 = 0xaa;
*(uint32_t*)0x20000004 = htobe32(0x64010100);
*(uint16_t*)0x20000008 = 1;
memcpy((void*)0x2000000a, "\xe2\xfa\x82\x59\x99\x17\xd2\x64\x1e\xd8\xb5\x64\xba\x8b\x49\x9c\x47\xff\xb8\xf7\xc4\x74\x5a\x15\x1e\x9a\xb5\x0a\x0a\x97\x5a\x01", 32);
*(uint32_t*)0x2000002c = 0x10001;
*(uint32_t*)0x20000030 = 0x1ff;
*(uint32_t*)0x20000034 = 8;
*(uint32_t*)0x20000038 = 0;
	syscall(__NR_setsockopt, -1, 0, 0xd3, 0x20000000ul, 0x3cul);
*(uint32_t*)0x20000040 = htobe32(0xa010100);
*(uint8_t*)0x20000044 = 0xac;
*(uint8_t*)0x20000045 = 0x14;
*(uint8_t*)0x20000046 = 0x14;
*(uint8_t*)0x20000047 = 0;
*(uint16_t*)0x20000048 = 1;
memcpy((void*)0x2000004a, "\xfa\x18\x1e\xcc\x7c\x6a\xca\x3c\xda\xa9\x1b\x72\x85\xc6\xb9\xe9\x20\x46\x4a\x28\xed\xd6\x57\x7f\x2b\x98\xcc\xb1\x31\xc4\x11\x75", 32);
*(uint32_t*)0x2000006c = 0x80000001;
*(uint32_t*)0x20000070 = 0xcb;
*(uint32_t*)0x20000074 = 0;
*(uint32_t*)0x20000078 = 1;
	syscall(__NR_setsockopt, -1, 0, 0xcd, 0x20000040ul, 0x3cul);
	syscall(__NR_readlinkat, -1, 0ul, 0x20000100ul, 0x93ul);
memcpy((void*)0x20000700, "nfs\000", 4);
memcpy((void*)0x20000740, "./file0\000", 8);
*(uint64_t*)0x20000940 = 0x20000780;
memset((void*)0x20000780, 24, 1);
*(uint64_t*)0x20000948 = 1;
*(uint64_t*)0x20000950 = 0;
*(uint64_t*)0x20000958 = 0x20000840;
memcpy((void*)0x20000840, "\x39\x83\xd7\xc8", 4);
*(uint64_t*)0x20000960 = 4;
*(uint64_t*)0x20000968 = 0x54;
*(uint8_t*)0x200009c0 = 0x2c;
memcpy((void*)0x200009c1, "subj_user", 9);
*(uint8_t*)0x200009ca = 0x3d;
memcpy((void*)0x200009cb, "/dev/vcs\000", 9);
*(uint8_t*)0x200009d4 = 0x2c;
memcpy((void*)0x200009d5, "fowner<", 7);
sprintf((char*)0x200009dc, "%020llu", (long long)0xee00);
*(uint8_t*)0x200009f0 = 0x2c;
memcpy((void*)0x200009f1, "uid", 3);
*(uint8_t*)0x200009f4 = 0x3d;
sprintf((char*)0x200009f5, "%020llu", (long long)-1);
*(uint8_t*)0x20000a09 = 0x2c;
memcpy((void*)0x20000a0a, "hash", 4);
*(uint8_t*)0x20000a0e = 0x2c;
*(uint8_t*)0x20000a0f = 0;
	res = -1;
res = syz_mount_image(0x20000700, 0x20000740, 0x58, 2, 0x20000940, 0x981420, 0x200009c0, 0);
	if (res != -1)
		r[0] = res;
memcpy((void*)0x20000a80, "./file0\000", 8);
	syscall(__NR_unlinkat, r[0], 0x20000a80ul, 0ul);
memcpy((void*)0x20000ac0, "/dev/vcsu#\000", 11);
syz_open_dev(0x20000ac0, 0, 0);
	syscall(__NR_setsockopt, -1, 0x29, 0x39, 0ul, 0ul);
*(uint8_t*)0x20000c00 = 0xac;
*(uint8_t*)0x20000c01 = 0x14;
*(uint8_t*)0x20000c02 = 0x14;
*(uint8_t*)0x20000c03 = 0;
*(uint32_t*)0x20000c04 = htobe32(-1);
*(uint16_t*)0x20000c08 = 0;
memcpy((void*)0x20000c0a, "\x2d\x1e\xe8\xde\x71\x7b\x2c\xaa\xef\x42\x34\x50\xfb\xc4\xdd\xc8\xdb\xa8\x51\x44\xca\xba\xb2\x54\x74\x09\x96\xcc\xb3\xfa\x09\x4d", 32);
*(uint32_t*)0x20000c2c = 0x80000001;
*(uint32_t*)0x20000c30 = 0xfffffffb;
*(uint32_t*)0x20000c34 = 0;
*(uint32_t*)0x20000c38 = 0;
	syscall(__NR_setsockopt, -1, 0, 0xd3, 0x20000c00ul, 0x3cul);
memcpy((void*)0x20000d00, "/dev/vcs#\000", 10);
syz_open_dev(0x20000d00, 0, 0);
	return 0;
}
