// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[2] = {0xffffffffffffffff, 0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socket, 1ul, 5ul, 0);
	if (res != -1)
		r[0] = res;
*(uint16_t*)0x20000000 = 1;
memcpy((void*)0x20000002, "./file0aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", 108);
	syscall(__NR_bind, r[0], 0x20000000ul, 0x6eul);
	syscall(__NR_listen, r[0], 0);
	res = syscall(__NR_socket, 1ul, 5ul, 0);
	if (res != -1)
		r[1] = res;
*(uint16_t*)0x20000080 = 1;
memcpy((void*)0x20000082, "./file0aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", 108);
	syscall(__NR_connect, r[1], 0x20000080ul, 0x6eul);
	syscall(__NR_accept4, r[0], 0ul, 0ul, 0ul);
	return 0;
}
