// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socket, 0x10ul, 3ul, 0);
	if (res != -1)
		r[0] = res;
*(uint64_t*)0x20001180 = 0;
*(uint32_t*)0x20001188 = 0;
*(uint64_t*)0x20001190 = 0x20000580;
*(uint64_t*)0x20000580 = 0x200059c0;
memcpy((void*)0x200059c0, "\x24\x00\x00\x00\x2a\x00\x5d\x95\x7a\x21\x13\xb6\x4b\x48\xc9\xbc\x00\xe0\x00\x00\x02", 21);
*(uint64_t*)0x20000588 = 0x24;
*(uint64_t*)0x20001198 = 1;
*(uint64_t*)0x200011a0 = 0;
*(uint64_t*)0x200011a8 = 0;
*(uint32_t*)0x200011b0 = 0;
	syscall(__NR_sendmsg, r[0], 0x20001180ul, 0ul);
	return 0;
}
