// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);

*(uint64_t*)0x200004c0 = 0;
*(uint32_t*)0x200004c8 = 0;
*(uint64_t*)0x200004d0 = 0x20000480;
*(uint64_t*)0x20000480 = 0x20000880;
*(uint16_t*)0x20000880 = 0;
memcpy((void*)0x20000882, "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02", 11);
*(uint64_t*)0x20000488 = 0x18;
*(uint64_t*)0x200004d8 = 1;
*(uint64_t*)0x200004e0 = 0;
*(uint64_t*)0x200004e8 = 0;
*(uint32_t*)0x200004f0 = 0;
	syscall(__NR_sendmsg, -1, 0x200004c0ul, 0ul);
*(uint64_t*)0x20000800 = 0x20000280;
*(uint64_t*)0x20000808 = 0;
*(uint64_t*)0x20000810 = 0x20000500;
*(uint64_t*)0x20000818 = 0;
*(uint64_t*)0x20000820 = 0x20000300;
*(uint64_t*)0x20000828 = 0;
*(uint64_t*)0x20000830 = 0x200005c0;
*(uint64_t*)0x20000838 = 0;
*(uint64_t*)0x20000840 = 0x20000640;
*(uint64_t*)0x20000848 = 0;
*(uint64_t*)0x20000850 = 0x20000740;
*(uint64_t*)0x20000858 = 0;
	syscall(__NR_process_vm_readv, -1, 0x20000800ul, 0xcul, 0x20001d80ul, 1ul, 0ul);
	return 0;
}
