// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socket, 0xaul, 2ul, 0);
	if (res != -1)
		r[0] = res;
*(uint16_t*)0x20000000 = 0xa;
*(uint16_t*)0x20000002 = htobe16(0);
*(uint32_t*)0x20000004 = htobe32(0);
*(uint8_t*)0x20000008 = 0xfe;
*(uint8_t*)0x20000009 = 0x80;
memset((void*)0x2000000a, 0, 13);
*(uint8_t*)0x20000017 = 0xbb;
*(uint32_t*)0x20000018 = 1;
	syscall(__NR_connect, r[0], 0x20000000ul, 0x1cul);
*(uint64_t*)0x20000640 = 0;
*(uint32_t*)0x20000648 = 0;
*(uint64_t*)0x20000650 = 0x200005c0;
*(uint64_t*)0x200005c0 = 0x20000100;
memcpy((void*)0x20000100, "\xb8\x46\x8e", 3);
*(uint64_t*)0x200005c8 = 3;
*(uint64_t*)0x200005d0 = 0x20000680;
memset((void*)0x20000680, 169, 1);
*(uint64_t*)0x200005d8 = 1;
*(uint64_t*)0x20000658 = 2;
*(uint64_t*)0x20000660 = 0x20000c80;
*(uint64_t*)0x20000c80 = 0x18;
*(uint32_t*)0x20000c88 = 0x29;
*(uint32_t*)0x20000c8c = 0x37;
*(uint8_t*)0x20000c90 = 0;
*(uint8_t*)0x20000c91 = 0;
memset((void*)0x20000c92, 0, 6);
*(uint64_t*)0x20000c98 = 0x18;
*(uint32_t*)0x20000ca0 = 0x29;
*(uint32_t*)0x20000ca4 = 4;
*(uint8_t*)0x20000ca8 = 0;
*(uint8_t*)0x20000ca9 = 0;
memset((void*)0x20000caa, 0, 6);
*(uint64_t*)0x20000cb0 = 0x14;
*(uint32_t*)0x20000cb8 = 0x29;
*(uint32_t*)0x20000cbc = 0x3e;
*(uint32_t*)0x20000cc0 = 0;
*(uint64_t*)0x20000cc8 = 0x24;
*(uint32_t*)0x20000cd0 = 0x29;
*(uint32_t*)0x20000cd4 = 0x32;
*(uint64_t*)0x20000cd8 = htobe64(0);
*(uint64_t*)0x20000ce0 = htobe64(1);
*(uint32_t*)0x20000ce8 = 0;
*(uint64_t*)0x20000668 = 0x70;
*(uint32_t*)0x20000670 = 0;
	syscall(__NR_sendmsg, r[0], 0x20000640ul, 0ul);
	return 0;
}
