// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socket, 0x10ul, 2ul, 0);
	if (res != -1)
		r[0] = res;
*(uint64_t*)0x20000140 = 0;
*(uint32_t*)0x20000148 = 0;
*(uint64_t*)0x20000150 = 0x20000100;
*(uint64_t*)0x20000100 = 0x20000500;
*(uint32_t*)0x20000500 = 0x8c;
*(uint16_t*)0x20000504 = 0x1d;
*(uint16_t*)0x20000506 = 1;
*(uint32_t*)0x20000508 = 0;
*(uint32_t*)0x2000050c = 0;
*(uint16_t*)0x20000510 = 3;
*(uint16_t*)0x20000512 = 0x10;
*(uint8_t*)0x20000514 = 0;
*(uint16_t*)0x20000516 = 0;
*(uint8_t*)0x20000518 = 0;
*(uint16_t*)0x2000051c = 0x70;
*(uint16_t*)0x2000051e = 1;
memcpy((void*)0x20000520, "digest_null-generic\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000", 64);
*(uint32_t*)0x20000560 = 0x140;
memcpy((void*)0x20000564, "\x7a\xb9\xd8\x18\x7f\x4d\x4f\x8b\x1c\x2b\xbc\x48\x4f\x86\x7c\x7a\xa9\x5f\x3c\xcc\x89\x03\x5e\x27\x85\xc1\xb3\x14\x92\x25\xa8\x38\x5c\xe7\x0e\xa8\xfd\x9a\xb9\xf4", 40);
*(uint64_t*)0x20000108 = 0x8c;
*(uint64_t*)0x20000158 = 1;
*(uint64_t*)0x20000160 = 0;
*(uint64_t*)0x20000168 = 0;
*(uint32_t*)0x20000170 = 0;
	syscall(__NR_sendmsg, r[0], 0x20000140ul, 0ul);
	return 0;
}
