// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <fcntl.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

#ifndef __NR_epoll_pwait2
#define __NR_epoll_pwait2 441
#endif

static long syz_open_dev(volatile long a0, volatile long a1, volatile long a2)
{
	if (a0 == 0xc || a0 == 0xb) {
		char buf[128];
		sprintf(buf, "/dev/%s/%d:%d", a0 == 0xc ? "char" : "block", (uint8_t)a1, (uint8_t)a2);
		return open(buf, O_RDWR, 0);
	} else {
		char buf[1024];
		char* hash;
		strncpy(buf, (char*)a0, sizeof(buf) - 1);
		buf[sizeof(buf) - 1] = 0;
		while ((hash = strchr(buf, '#'))) {
			*hash = '0' + (char)(a1 % 10);
			a1 /= 10;
		}
		return open(buf, a2, 0);
	}
}

static long syz_open_procfs(volatile long a0, volatile long a1)
{
	char buf[128];
	memset(buf, 0, sizeof(buf));
	if (a0 == 0) {
		snprintf(buf, sizeof(buf), "/proc/self/%s", (char*)a1);
	} else if (a0 == -1) {
		snprintf(buf, sizeof(buf), "/proc/thread-self/%s", (char*)a1);
	} else {
		snprintf(buf, sizeof(buf), "/proc/self/task/%d/%s", (int)a0, (char*)a1);
	}
	int fd = open(buf, O_RDWR);
	if (fd == -1)
		fd = open(buf, O_RDONLY);
	return fd;
}

uint64_t r[6] = {0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
memcpy((void*)0x20000000, "/dev/loop#\000", 11);
	res = -1;
res = syz_open_dev(0x20000000, 0, 0);
	if (res != -1)
		r[0] = res;
	syscall(__NR_ioctl, -1, 0x4c01, 0);
memcpy((void*)0x20001cc0, "/dev/vcsu#\000", 11);
syz_open_dev(0x20001cc0, 0xffffffff, 0x220000);
	res = syscall(__NR_epoll_create, 0x7f);
	if (res != -1)
		r[1] = res;
memcpy((void*)0x20000100, "ns/cgroup\000", 10);
	res = -1;
res = syz_open_procfs(0, 0x20000100);
	if (res != -1)
		r[2] = res;
	syscall(__NR_ioctl, r[2], 0x81f8943c, 0ul);
	syscall(__NR_epoll_ctl, r[1], 2ul, r[2], 0);
memcpy((void*)0x20000240, "/dev/rtc0\000", 10);
	res = syscall(__NR_openat, 0xffffffffffffff9cul, 0x20000240ul, 0x101080ul, 0ul);
	if (res != -1)
		r[3] = res;
	syscall(__NR_ioctl, r[3], 0x700f, 0);
memcpy((void*)0x20000280, "/dev/nvram\000", 11);
	res = syscall(__NR_openat, 0xffffffffffffff9cul, 0x20000280ul, 0xc0ul, 0ul);
	if (res != -1)
		r[4] = res;
*(uint32_t*)0x20001d00 = 0;
*(uint64_t*)0x20001d04 = 0;
	syscall(__NR_epoll_ctl, r[4], 3ul, -1, 0x20001d00ul);
memcpy((void*)0x20001cc0, "/dev/vcsu#\000", 11);
	res = -1;
res = syz_open_dev(0x20001cc0, 0xffffffff, 0x220000);
	if (res != -1)
		r[5] = res;
*(uint32_t*)0x20001d00 = 0;
*(uint64_t*)0x20001d04 = 0;
	syscall(__NR_epoll_ctl, r[5], 3ul, -1, 0x20001d00ul);
*(uint64_t*)0x20000300 = 0;
*(uint64_t*)0x20000308 = 0x3938700;
*(uint64_t*)0x20000340 = 6;
	syscall(__NR_epoll_pwait2, r[1], 0x200002c0ul, 2ul, 0x20000300ul, 0x20000340ul, 8ul);
	syscall(__NR_ioctl, r[0], 0x4c07, 0);
	return 0;
}
