// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
memcpy((void*)0x20000240, "/dev/full\000", 10);
	res = syscall(__NR_openat, 0xffffffffffffff9cul, 0x20000240ul, 0ul, 0ul);
	if (res != -1)
		r[0] = res;
memcpy((void*)0x20000040, "security.selinux\000", 17);
memcpy((void*)0x20000280, ".#)}^\\\301\374\321\004T6\rQaN\023\313\264M?_f\234>X\257\324\252\306X\255\344\324\340\276\251\r\022\373<\345\362\367\021\375G\234\034l\b`\036\031J\251f\304g\331\201J5\236\024\221B\315\034\v\320\346?\252n\327\260\b^\237V%\000h@\\\307\276\027@h\327\244\200\213\337a1\232\002\232\030\360oA\273\270\030\0352E\317\372`\372j\2621aln\3250\351\300\020\000\000\000\000\000\000\000\000\000\000j\345`\244\345CNY12}-f,\230\260\303\366\302\\\375\215\310_\332\203\203t9_\261nz\356\266\230\340\317f\017I\352^\204D\2203S\355\321\370B\337\341\360\033\275d%\002\304\336\254\206", 200);
	syscall(__NR_fsetxattr, r[0], 0x20000040ul, 0x20000280ul, 0xc8ul, 0ul);
	return 0;
}
