// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socket, 2ul, 1ul, 0);
	if (res != -1)
		r[0] = res;
*(uint8_t*)0x200000c0 = 0xfe;
*(uint8_t*)0x200000c1 = 0x88;
memset((void*)0x200000c2, 0, 12);
*(uint8_t*)0x200000ce = 0;
*(uint8_t*)0x200000cf = 1;
*(uint8_t*)0x200000d0 = 0xac;
*(uint8_t*)0x200000d1 = 0x1e;
*(uint8_t*)0x200000d2 = 0;
*(uint8_t*)0x200000d3 = 1;
*(uint16_t*)0x200000e0 = htobe16(0);
*(uint16_t*)0x200000e2 = htobe16(0);
*(uint16_t*)0x200000e4 = htobe16(0);
*(uint16_t*)0x200000e6 = htobe16(0);
*(uint16_t*)0x200000e8 = 0xa;
*(uint8_t*)0x200000ea = 0;
*(uint8_t*)0x200000eb = 0;
*(uint8_t*)0x200000ec = 0;
*(uint32_t*)0x200000f0 = 0;
*(uint32_t*)0x200000f4 = 0xee01;
*(uint64_t*)0x200000f8 = 0;
*(uint64_t*)0x20000100 = 0;
*(uint64_t*)0x20000108 = 0;
*(uint64_t*)0x20000110 = 0;
*(uint64_t*)0x20000118 = 0;
*(uint64_t*)0x20000120 = 0;
*(uint64_t*)0x20000128 = 0;
*(uint64_t*)0x20000130 = 0;
*(uint64_t*)0x20000138 = 0;
*(uint64_t*)0x20000140 = 0;
*(uint64_t*)0x20000148 = 0;
*(uint64_t*)0x20000150 = 0;
*(uint32_t*)0x20000158 = 0;
*(uint32_t*)0x2000015c = 0;
*(uint8_t*)0x20000160 = 0;
*(uint8_t*)0x20000161 = 0;
*(uint8_t*)0x20000162 = 0;
*(uint8_t*)0x20000163 = 0;
*(uint8_t*)0x20000168 = -1;
*(uint8_t*)0x20000169 = 1;
memset((void*)0x2000016a, 0, 13);
*(uint8_t*)0x20000177 = 1;
*(uint32_t*)0x20000178 = htobe32(0);
*(uint8_t*)0x2000017c = 0x33;
*(uint16_t*)0x20000180 = 0;
memcpy((void*)0x20000184, " \001\000\000\000\000\000\000\000\000\000\000\000\000\000\000", 16);
*(uint32_t*)0x20000194 = 0;
*(uint8_t*)0x20000198 = 0;
*(uint8_t*)0x20000199 = 0;
*(uint8_t*)0x2000019a = 0;
*(uint32_t*)0x2000019c = 0;
*(uint32_t*)0x200001a0 = 0;
*(uint32_t*)0x200001a4 = 0;
	syscall(__NR_setsockopt, r[0], 0, 0x11, 0x200000c0ul, 0xe8ul);
	return 0;
}
