// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
memcpy((void*)0x200003c0, "/dev/snd/seq\000", 13);
	res = syscall(__NR_openat, 0xffffffffffffff9cul, 0x200003c0ul, 0ul, 0);
	if (res != -1)
		r[0] = res;
*(uint8_t*)0x20000400 = 0;
*(uint8_t*)0x20000401 = 0;
*(uint8_t*)0x20000402 = 0x40;
*(uint8_t*)0x20000403 = 0;
*(uint32_t*)0x20000404 = 0;
*(uint32_t*)0x20000408 = 0;
*(uint8_t*)0x2000040c = 0;
memset((void*)0x2000040d, 0, 3);
memset((void*)0x20000410, 0, 64);
	syscall(__NR_ioctl, r[0], 0x40505331, 0x20000400ul);
	return 0;
}
