// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
memcpy((void*)0x20000380, "/dev/vcsu\000", 10);
	res = syscall(__NR_openat, 0xffffffffffffff9cul, 0x20000380ul, 0ul, 0ul);
	if (res != -1)
		r[0] = res;
*(uint64_t*)0x20006a80 = 0x200035c0;
*(uint64_t*)0x20006a88 = 0x48;
*(uint64_t*)0x20006a90 = 0x20003640;
*(uint64_t*)0x20006a98 = 0x21;
	syscall(__NR_readv, r[0], 0x20006a80ul, 2ul);
	return 0;
}
