// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[2] = {0x0, 0x0};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
memcpy((void*)0x20000200, "keyring\000", 8);
memcpy((void*)0x20000240, "syz", 3);
*(uint8_t*)0x20000243 = 0x20;
*(uint8_t*)0x20000244 = 0;
	res = syscall(__NR_add_key, 0x20000200ul, 0x20000240ul, 0ul, 0ul, -1);
	if (res != -1)
		r[0] = res;
memcpy((void*)0x20000000, "logon\000", 6);
memcpy((void*)0x20000040, "fscrypt:", 8);
memcpy((void*)0x20000048, "e355a76a11a1be18", 16);
*(uint8_t*)0x20000058 = 0;
*(uint32_t*)0x20000080 = 0;
memcpy((void*)0x20000084, "\x14\xa6\x58\xcb\xb5\xbe\xf3\x51\xc0\x59\x3a\x91\x8a\xcb\xa9\x35\xd3\x74\x47\xd5\xd4\x6b\x00\xc2\x1b\xf7\x41\xbc\x44\x04\xba\x31\xff\xfc\x22\x89\x0d\xe7\xe1\xc2\xc6\xf9\xe4\xcf\x26\xca\x2f\xdd\x02\xff\xf2\xe9\x24\xf4\x95\xb5\xe9\x88\x75\x97\xb0\xe0\x75\xf5", 64);
*(uint32_t*)0x200000c4 = 0;
	res = syscall(__NR_add_key, 0x20000000ul, 0x20000040ul, 0x20000080ul, 0x48ul, r[0]);
	if (res != -1)
		r[1] = res;
	syscall(__NR_keyctl, 9ul, r[1], 0xfffffffd, 0, 0);
	return 0;
}
