// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socket, 0x10ul, 3ul, 6);
	if (res != -1)
		r[0] = res;
*(uint64_t*)0x20000200 = 0;
*(uint32_t*)0x20000208 = 0;
*(uint64_t*)0x20000210 = 0x20000140;
*(uint64_t*)0x20000140 = 0x20001980;
*(uint32_t*)0x20001980 = 0xfc;
*(uint16_t*)0x20001984 = 0x13;
*(uint16_t*)0x20001986 = 1;
*(uint32_t*)0x20001988 = 0;
*(uint32_t*)0x2000198c = 0;
*(uint32_t*)0x20001990 = htobe32(-1);
memset((void*)0x200019a0, 0, 16);
*(uint16_t*)0x200019b0 = htobe16(0);
*(uint16_t*)0x200019b2 = htobe16(0);
*(uint16_t*)0x200019b4 = htobe16(0);
*(uint16_t*)0x200019b6 = htobe16(0);
*(uint16_t*)0x200019b8 = 2;
*(uint8_t*)0x200019ba = 0;
*(uint8_t*)0x200019bb = 0;
*(uint8_t*)0x200019bc = 0;
*(uint32_t*)0x200019c0 = 0;
*(uint32_t*)0x200019c4 = 0;
*(uint64_t*)0x200019c8 = 0;
*(uint64_t*)0x200019d0 = 0;
*(uint64_t*)0x200019d8 = 0;
*(uint64_t*)0x200019e0 = 0;
*(uint64_t*)0x200019e8 = 0;
*(uint64_t*)0x200019f0 = 0;
*(uint64_t*)0x200019f8 = 0;
*(uint64_t*)0x20001a00 = 0;
*(uint64_t*)0x20001a08 = 0;
*(uint64_t*)0x20001a10 = 0;
*(uint64_t*)0x20001a18 = 0;
*(uint64_t*)0x20001a20 = 0;
*(uint32_t*)0x20001a28 = 0;
*(uint32_t*)0x20001a2c = 0;
*(uint8_t*)0x20001a30 = 0;
*(uint8_t*)0x20001a31 = 0;
*(uint8_t*)0x20001a32 = 0;
*(uint8_t*)0x20001a33 = 0;
*(uint16_t*)0x20001a38 = 0x44;
*(uint16_t*)0x20001a3a = 5;
*(uint8_t*)0x20001a3c = 0xfe;
*(uint8_t*)0x20001a3d = 0x80;
memset((void*)0x20001a3e, 0, 13);
*(uint8_t*)0x20001a4b = 0xbb;
*(uint32_t*)0x20001a4c = htobe32(0);
*(uint8_t*)0x20001a50 = 0;
*(uint16_t*)0x20001a54 = 0;
*(uint8_t*)0x20001a58 = 0xfc;
*(uint8_t*)0x20001a59 = 1;
memset((void*)0x20001a5a, 0, 13);
*(uint8_t*)0x20001a67 = 0;
*(uint32_t*)0x20001a68 = 0;
*(uint8_t*)0x20001a6c = 6;
*(uint8_t*)0x20001a6d = 0;
*(uint8_t*)0x20001a6e = 0;
*(uint32_t*)0x20001a70 = 0;
*(uint32_t*)0x20001a74 = 0;
*(uint32_t*)0x20001a78 = 0;
*(uint64_t*)0x20000148 = 0xfc;
*(uint64_t*)0x20000218 = 1;
*(uint64_t*)0x20000220 = 0;
*(uint64_t*)0x20000228 = 0;
*(uint32_t*)0x20000230 = 0;
	syscall(__NR_sendmsg, r[0], 0x20000200ul, 0ul);
	return 0;
}
