// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[2] = {0xffffffffffffffff, 0x0};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
memcpy((void*)0x200002c0, "./file0\000", 8);
	res = syscall(__NR_creat, 0x200002c0ul, 0ul);
	if (res != -1)
		r[0] = res;
memcpy((void*)0x20000080, ".\000", 2);
	res = syscall(__NR_newfstatat, 0xffffffffffffff9cul, 0x20000080ul, 0x20000140ul, 0ul);
	if (res != -1)
r[1] = *(uint32_t*)0x20000158;
	syscall(__NR_setresuid, 0, r[1], 0);
	syscall(__NR_setfsuid, 0);
	syscall(__NR_ioctl, r[0], 0x6611, 0);
	return 0;
}
