// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[3] = {0xffffffffffffffff, 0x0, 0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socket, 0x10ul, 3ul, 9);
	if (res != -1)
		r[0] = res;
*(uint64_t*)0x200001c0 = 0;
*(uint32_t*)0x200001c8 = 0;
*(uint64_t*)0x200001d0 = 0x20000180;
*(uint64_t*)0x20000180 = 0;
*(uint64_t*)0x20000188 = 0;
*(uint64_t*)0x200001d8 = 1;
*(uint64_t*)0x200001e0 = 0;
*(uint64_t*)0x200001e8 = 0;
*(uint32_t*)0x200001f0 = 0;
	syscall(__NR_sendmsg, -1, 0x200001c0ul, 0ul);
memcpy((void*)0x20000380, "\x01\x00\x00\x00\x01\x00\x00\x00\x18", 9);
	syscall(__NR_ioctl, -1, 0xc0189379, 0x20000380ul);
	res = syscall(__NR_io_setup, 0x1198, 0x20000040ul);
	if (res != -1)
r[1] = *(uint64_t*)0x20000040;
	res = syscall(__NR_socket, 0x10ul, 3ul, 9);
	if (res != -1)
		r[2] = res;
*(uint64_t*)0x20000100 = 0x20000080;
*(uint64_t*)0x20000080 = 0;
*(uint32_t*)0x20000088 = 0;
*(uint32_t*)0x2000008c = 0;
*(uint16_t*)0x20000090 = 0;
*(uint16_t*)0x20000092 = 0;
*(uint32_t*)0x20000094 = r[0];
*(uint64_t*)0x20000098 = 0;
*(uint64_t*)0x200000a0 = 0;
*(uint64_t*)0x200000a8 = 0;
*(uint64_t*)0x200000b0 = 0;
*(uint32_t*)0x200000b8 = 0;
*(uint32_t*)0x200000bc = -1;
*(uint64_t*)0x20000108 = 0x20000000;
*(uint64_t*)0x20000000 = 0;
*(uint32_t*)0x20000008 = 0;
*(uint32_t*)0x2000000c = 0;
*(uint16_t*)0x20000010 = 8;
*(uint16_t*)0x20000012 = 0;
*(uint32_t*)0x20000014 = r[2];
*(uint64_t*)0x20000018 = 0x20000180;
*(uint64_t*)0x20000020 = 0x35;
*(uint64_t*)0x20000028 = 0;
*(uint64_t*)0x20000030 = 0;
*(uint32_t*)0x20000038 = 0;
*(uint32_t*)0x2000003c = -1;
	syscall(__NR_io_submit, r[1], 2ul, 0x20000100ul);
	return 0;
}
