// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);

memcpy((void*)0x20002b80, "./file0\000", 8);
*(uint64_t*)0x20002bc0 = 0;
*(uint64_t*)0x20002bc8 = 0xea60;
*(uint64_t*)0x20002bd0 = 0;
*(uint64_t*)0x20002bd8 = 0;
	syscall(__NR_utimensat, -1, 0x20002b80ul, 0x20002bc0ul, 0ul);
	return 0;
}
