// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <fcntl.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

static long syz_open_dev(volatile long a0, volatile long a1, volatile long a2)
{
	if (a0 == 0xc || a0 == 0xb) {
		char buf[128];
		sprintf(buf, "/dev/%s/%d:%d", a0 == 0xc ? "char" : "block", (uint8_t)a1, (uint8_t)a2);
		return open(buf, O_RDWR, 0);
	} else {
		char buf[1024];
		char* hash;
		strncpy(buf, (char*)a0, sizeof(buf) - 1);
		buf[sizeof(buf) - 1] = 0;
		while ((hash = strchr(buf, '#'))) {
			*hash = '0' + (char)(a1 % 10);
			a1 /= 10;
		}
		return open(buf, a2, 0);
	}
}

uint64_t r[2] = {0xffffffffffffffff, 0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
memcpy((void*)0x200001c0, "/dev/loop#\000", 11);
	res = -1;
res = syz_open_dev(0x200001c0, 0, 0);
	if (res != -1)
		r[0] = res;
memcpy((void*)0x20000a00, "/sys/power/pm_trace", 19);
	res = syscall(__NR_openat, 0xffffffffffffff9cul, 0x20000a00ul, 0ul, 0ul);
	if (res != -1)
		r[1] = res;
*(uint32_t*)0x20000280 = r[1];
*(uint32_t*)0x20000284 = 0x800;
*(uint64_t*)0x20000288 = 0;
*(uint64_t*)0x20000290 = 0;
*(uint64_t*)0x20000298 = 0;
*(uint64_t*)0x200002a0 = 0;
*(uint64_t*)0x200002a8 = 0;
*(uint32_t*)0x200002b0 = 0;
*(uint32_t*)0x200002b4 = 0;
*(uint32_t*)0x200002b8 = 0;
*(uint32_t*)0x200002bc = 0;
memcpy((void*)0x200002c0, "\x3b\x81\x20\xdc\x46\xb7\x1a\x45\x83\x86\xad\xe6\x4b\x87\x62\x95\x2a\x01\x4f\x9e\x47\x35\xb4\x9a\x8f\xe7\x09\xfc\xde\x05\x44\x91\xe9\x7a\x3e\xc6\x15\x24\xb9\xb9\x60\x3f\x1b\xb1\xba\x8f\xf7\x39\x83\xe2\x26\x34\x9e\x05\xea\x67\xcb\xab\x59\xf3\xf3\x48\x74\xbb", 64);
memcpy((void*)0x20000300, "\x43\xe8\x6a\xd3\xde\x74\x7d\xcc\x92\xf6\x76\x68\x4f\xd8\xb8\x12\xb5\x65\xad\xbf\xd3\x93\xaf\x32\x48\x9a\x9f\xc9\x0e\x65\x2c\x6f\xdb\xfe\x8d\xe5\xb7\x2b\x6e\xa8\x5a\x8d\xbf\xf1\xfd\x7a\x69\xec\xb1\x36\xaf\x04\x45\x9a\xce\x1f\xd3\xfb\x76\x9d\x89\x41\xd6\x61", 64);
memcpy((void*)0x20000340, "\x2e\xed\xaf\xbf\x93\x0f\xc9\x3c\xb0\xcd\xce\xd9\x61\xac\x98\xc2\x5a\x0b\x58\x80\xfb\x7d\xe4\x85\xaa\x48\x5d\x85\x92\x49\x08\x1c", 32);
*(uint64_t*)0x20000360 = 0;
*(uint64_t*)0x20000368 = 0;
memset((void*)0x20000370, 0, 64);
	syscall(__NR_ioctl, r[0], 0x4c0a, 0x20000280ul);
	return 0;
}
