// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socket, 0x10ul, 3ul, 4);
	if (res != -1)
		r[0] = res;
*(uint64_t*)0x20000480 = 0;
*(uint32_t*)0x20000488 = 0;
*(uint64_t*)0x20000490 = 0x20000440;
*(uint64_t*)0x20000440 = 0x20000080;
*(uint32_t*)0x20000080 = 0x58;
*(uint16_t*)0x20000084 = 0x12;
*(uint16_t*)0x20000086 = 1;
*(uint32_t*)0x20000088 = 0;
*(uint32_t*)0x2000008c = 0;
*(uint8_t*)0x20000090 = 0;
*(uint8_t*)0x20000091 = 0;
*(uint8_t*)0x20000092 = 0;
*(uint8_t*)0x20000093 = 0;
*(uint16_t*)0x20000094 = htobe16(0);
*(uint16_t*)0x20000096 = htobe16(0);
*(uint32_t*)0x20000098 = 0;
*(uint32_t*)0x2000009c = 0;
*(uint32_t*)0x200000a0 = 0;
*(uint32_t*)0x200000a4 = 0;
*(uint32_t*)0x200000a8 = 8;
*(uint32_t*)0x200000ac = 0x8000;
*(uint32_t*)0x200000b0 = 0;
*(uint32_t*)0x200000b4 = 0;
*(uint32_t*)0x200000b8 = 0;
*(uint32_t*)0x200000bc = 0;
*(uint32_t*)0x200000c0 = 0;
*(uint32_t*)0x200000c4 = 0;
*(uint32_t*)0x200000c8 = 0;
*(uint16_t*)0x200000cc = 4;
*(uint16_t*)0x200000ce = 1;
*(uint16_t*)0x200000d0 = 4;
*(uint16_t*)0x200000d2 = 1;
*(uint16_t*)0x200000d4 = 4;
*(uint16_t*)0x200000d6 = 1;
*(uint64_t*)0x20000448 = 0x58;
*(uint64_t*)0x20000498 = 1;
*(uint64_t*)0x200004a0 = 0;
*(uint64_t*)0x200004a8 = 0;
*(uint32_t*)0x200004b0 = 0x4850;
	syscall(__NR_sendmsg, r[0], 0x20000480ul, 0ul);
	return 0;
}
