// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[7] = {0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0x0, 0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socket, 0xaul, 2ul, 0x88);
	if (res != -1)
		r[0] = res;
	res = syscall(__NR_socket, 0xaul, 2ul, 0x88);
	if (res != -1)
		r[1] = res;
*(uint16_t*)0x20000080 = 0xa;
*(uint16_t*)0x20000082 = htobe16(0);
*(uint32_t*)0x20000084 = htobe32(0);
*(uint8_t*)0x20000088 = -1;
*(uint8_t*)0x20000089 = 1;
memset((void*)0x2000008a, 0, 13);
*(uint8_t*)0x20000097 = 1;
*(uint32_t*)0x20000098 = 0;
	syscall(__NR_connect, r[1], 0x20000080ul, 0x1cul);
	res = syscall(__NR_socket, 0xaul, 2ul, 0x88);
	if (res != -1)
		r[2] = res;
	res = syscall(__NR_socket, 0x11ul, 3ul, 0x300);
	if (res != -1)
		r[3] = res;
	syscall(__NR_read, r[3], 0x20000140ul, 0x24ul);
*(uint8_t*)0x20000300 = 0xfc;
*(uint8_t*)0x20000301 = 0;
memset((void*)0x20000302, 0, 13);
*(uint8_t*)0x2000030f = 1;
*(uint32_t*)0x20000310 = 0x31;
*(uint32_t*)0x20000314 = 0;
	syscall(__NR_ioctl, r[0], 0x8916, 0x20000300ul);
*(uint32_t*)0x20000100 = 5;
	syscall(__NR_setsockopt, r[2], 0x11, 0xd, 0x20000100ul, 4ul);
memcpy((void*)0x200002c0, "sit0\000\000\000\000\000\000\000\000\000\000\000\000", 16);
	res = syscall(__NR_ioctl, r[3], 0x8933, 0x200002c0ul);
	if (res != -1)
r[4] = *(uint32_t*)0x200002d0;
	res = syscall(__NR_gettid);
	if (res != -1)
		r[5] = res;
*(uint32_t*)0x200000c0 = 0;
	syscall(__NR_sched_setparam, r[5], 0x200000c0ul);
*(uint32_t*)0x20000040 = 0;
*(uint32_t*)0x20000044 = r[5];
	syscall(__NR_fcntl, r[1], 0xful, 0x20000040ul);
*(uint64_t*)0x20000480 = htobe64(0);
*(uint64_t*)0x20000488 = htobe64(1);
*(uint32_t*)0x20000490 = 0;
*(uint32_t*)0x20000494 = r[4];
	syscall(__NR_ioctl, r[2], 0x8918, 0x20000480ul);
*(uint8_t*)0x20000000 = 0xfe;
*(uint8_t*)0x20000001 = 0x80;
memset((void*)0x20000002, 0, 13);
*(uint8_t*)0x2000000f = 0xbb;
*(uint32_t*)0x20000010 = 0x65;
*(uint32_t*)0x20000014 = r[4];
	syscall(__NR_ioctl, r[1], 0x8916, 0x20000000ul);
memset((void*)0x200000c0, 0, 10);
memset((void*)0x200000ca, 255, 2);
*(uint32_t*)0x200000cc = htobe32(0);
*(uint32_t*)0x200000d0 = 0x80;
*(uint32_t*)0x200000d4 = r[4];
	syscall(__NR_ioctl, r[0], 0x8916, 0x200000c0ul);
memcpy((void*)0x20000000, "/dev/rtc0\000", 10);
	res = syscall(__NR_openat, 0xffffffffffffff9cul, 0x20000000ul, 0ul, 0ul);
	if (res != -1)
		r[6] = res;
	syscall(__NR_ioctl, r[6], 0x7002, 0);
	syscall(__NR_flistxattr, r[6], 0x20000040ul, 0x69ul);
*(uint32_t*)0x20000000 = 0;
	syscall(__NR_getsockopt, r[0], 0x29, 0xcf, 0ul, 0x20000000ul);
*(uint32_t*)0x20000180 = 0;
memcpy((void*)0x20000184, "syzkaller1\000\000\000\000\000\000\000\000\000\000\000\000\000\000", 24);
*(uint32_t*)0x2000019c = 3;
*(uint16_t*)0x200001b4 = 7;
	syscall(__NR_ioctl, r[2], 0x8982, 0x20000180ul);
	return 0;
}
