// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);

memcpy((void*)0x20000000, "/\000q\315fO\203\361\241\227\025\301@z\350\257\2261\215;\031\0358l\274\303P\226\r\257\212w\341\331f\336\302\322:\3231\261\032\307\036\a\376J\317c\253\020\344\373S\343b\266\275\357\366\262\206\253\350\346\236Bgu\t6\351$\005r\200g\341\aO*\236\226\315W \346%#\te\003r0\302\005*p\230\216\355\257e\303\271,P\330\340\211$\231n \2045\322\261NTyU\310\314C)\356\372\034!(\0339T\333A\336\270\303\273\245nJ\204qfp!*^\177\342Y\006Xd\313\205\005&\263F.\256\025MF\031\353X\234G\3501\205\310-t\005\316\230A\2240\vG\276s\312\220K\354\306V\316h\240>jc\253\345*\fXw%v\006f\370\vM\322\217\352\230\374}\211c\314.`\037\216\211\177.[\235\232{\000\000\000\000\000\000\000\000\000", 243);
	syscall(__NR_init_module, 0x20000000ul, 0xf3ul, 0ul);
	return 0;
}
