// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);

memcpy((void*)0x20000040, "\244\261Z\274XV\274\030-\241\236\227\a2%\347\204\312\360<\"W\331t\340\261\220\016\211\001\006\2251\351\\q\a\322\004\257M[y\246Lg\201\337R\343\004\252\242y\273o^#\244\347\257Y\023\352\207\366\024Z5\262wo\267H\347\223\237\020y\237\345\202\177\273Q!+\257\324\202\271Oxc?\255@\255\3657\3717\255\3314\\\221\212\035\221u\353\234\255\360Ei\207\237!RX^\025B?>_\016\301\235\262\0257\004\a\352d\337\345\344\226E\026\376^f\0268W\347\336\317=\332\360\213\224J\351o=\304.\306s\327\303\362\370\022\240y\375\322\211Y\002\367_\331l\23426\255\020A~\035\226Y\356\241\350 \005\a\352\376\250\207\023\001\326\3076\277\036\372\0043k\202\226c2\215\320\341\336?<d\3252\235FDA\223\034a\n\320\031\210\222A\346]\236\216_\210\022e0\327\001~\003\255J\241Cvd", 258);
	syscall(__NR_mq_open, 0x20000040ul, 0ul, 0ul, 0ul);
	return 0;
}
