// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socket, 0xaul, 2ul, 0x88);
	if (res != -1)
		r[0] = res;
*(uint16_t*)0x20000080 = 0xa;
*(uint16_t*)0x20000082 = htobe16(0);
*(uint32_t*)0x20000084 = htobe32(0);
*(uint8_t*)0x20000088 = 0xfe;
*(uint8_t*)0x20000089 = 0x80;
memset((void*)0x2000008a, 0, 13);
*(uint8_t*)0x20000097 = 0xbb;
*(uint32_t*)0x20000098 = 2;
	syscall(__NR_connect, r[0], 0x20000080ul, 0x1cul);
*(uint64_t*)0x20001b00 = 0x20000040;
*(uint16_t*)0x20000040 = 0xa;
*(uint16_t*)0x20000042 = htobe16(0x4e21);
*(uint32_t*)0x20000044 = htobe32(0);
memset((void*)0x20000048, 0, 10);
memset((void*)0x20000052, 255, 2);
*(uint32_t*)0x20000054 = htobe32(0x7f000001);
*(uint32_t*)0x20000058 = 0;
*(uint32_t*)0x20001b08 = 0x1c;
*(uint64_t*)0x20001b10 = 0;
*(uint64_t*)0x20001b18 = 0;
*(uint64_t*)0x20001b20 = 0;
*(uint64_t*)0x20001b28 = 0;
*(uint32_t*)0x20001b30 = 0;
*(uint32_t*)0x20001b38 = 0;
	syscall(__NR_sendmmsg, r[0], 0x20001b00ul, 1ul, 0ul);
	return 0;
}
