// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[2] = {0xffffffffffffffff, 0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socket, 0x10ul, 3ul, 0xc);
	if (res != -1)
		r[0] = res;
*(uint64_t*)0x20000240 = 0;
*(uint32_t*)0x20000248 = 0;
*(uint64_t*)0x20000250 = 0x20000200;
*(uint64_t*)0x20000200 = 0;
*(uint64_t*)0x20000208 = 0x1c;
*(uint64_t*)0x20000258 = 1;
*(uint64_t*)0x20000260 = 0;
*(uint64_t*)0x20000268 = 0;
*(uint32_t*)0x20000270 = 0;
	syscall(__NR_sendmsg, r[0], 0x20000240ul, 0ul);
	res = syscall(__NR_socket, 0x10ul, 3ul, 0xc);
	if (res != -1)
		r[1] = res;
*(uint64_t*)0x20000a00 = 0;
*(uint32_t*)0x20000a08 = 0;
*(uint64_t*)0x20000a10 = 0x200009c0;
*(uint64_t*)0x200009c0 = 0x20000980;
*(uint32_t*)0x20000980 = 0x1c;
*(uint8_t*)0x20000984 = 1;
*(uint8_t*)0x20000985 = 4;
*(uint16_t*)0x20000986 = 0x301;
*(uint32_t*)0x20000988 = 0;
*(uint32_t*)0x2000098c = 0;
*(uint8_t*)0x20000990 = 0;
*(uint8_t*)0x20000991 = 0;
*(uint16_t*)0x20000992 = htobe16(0);
*(uint16_t*)0x20000994 = 5;
*(uint16_t*)0x20000996 = 1;
*(uint8_t*)0x20000998 = 1;
*(uint64_t*)0x200009c8 = 0x1c;
*(uint64_t*)0x20000a18 = 1;
*(uint64_t*)0x20000a20 = 0;
*(uint64_t*)0x20000a28 = 0;
*(uint32_t*)0x20000a30 = 0;
	syscall(__NR_sendmsg, r[1], 0x20000a00ul, 0ul);
	syscall(__NR_close, r[0]);
	return 0;
}
