// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

#ifndef __NR_copy_file_range
#define __NR_copy_file_range 326
#endif
#ifndef __NR_memfd_create
#define __NR_memfd_create 319
#endif

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
memset((void*)0x20000280, 1, 1);
	res = syscall(__NR_memfd_create, 0x20000280ul, 0ul);
	if (res != -1)
		r[0] = res;
*(uint64_t*)0x20000600 = 0x20000140;
memset((void*)0x20000140, 78, 1);
*(uint64_t*)0x20000608 = 1;
	syscall(__NR_writev, r[0], 0x20000600ul, 1ul);
*(uint64_t*)0x20000040 = 0x20001640;
memset((void*)0x20001640, 238, 1);
*(uint64_t*)0x20000048 = 1;
	syscall(__NR_writev, r[0], 0x20000040ul, 1ul);
*(uint64_t*)0x20000000 = 0;
	syscall(__NR_copy_file_range, r[0], 0x20000000ul, r[0], 0ul, 0x18cul, 0ul);
	return 0;
}
