// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socket, 2ul, 3ul, 1);
	if (res != -1)
		r[0] = res;
*(uint16_t*)0x20000140 = 2;
*(uint16_t*)0x20000142 = htobe16(0);
*(uint8_t*)0x20000144 = 0xac;
*(uint8_t*)0x20000145 = 0x14;
*(uint8_t*)0x20000146 = 0x14;
*(uint8_t*)0x20000147 = 0xaa;
*(uint16_t*)0x20000150 = 0;
memset((void*)0x20000152, 0, 6);
*(uint32_t*)0x20000160 = 0x5a;
*(uint16_t*)0x20000164 = 2;
*(uint16_t*)0x20000166 = htobe16(0);
*(uint32_t*)0x20000168 = htobe32(0);
memcpy((void*)0x20000174, "sit0\000\000\000\000\000\000\000\000\000\000\000\000", 16);
	syscall(__NR_ioctl, r[0], 0x8955, 0x20000140ul);
	return 0;
}
