// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_timerfd_create, 0ul, 0ul);
	if (res != -1)
		r[0] = res;
*(uint64_t*)0x20000640 = 0x77359400;
*(uint64_t*)0x20000648 = 0;
*(uint64_t*)0x20000650 = 0;
*(uint64_t*)0x20000658 = 0x3938700;
	syscall(__NR_timerfd_settime, r[0], 0ul, 0x20000640ul, 0ul);
	syscall(__NR_prctl, 0x1dul, 0xffffffffde1d3510ul, 0, 0, 0);
*(uint64_t*)0x20000000 = 9;
*(uint64_t*)0x20000008 = 0;
*(uint64_t*)0x20000010 = 0;
*(uint64_t*)0x20000018 = 0;
*(uint64_t*)0x20000020 = 0;
*(uint64_t*)0x20000028 = 0;
*(uint64_t*)0x20000030 = 0;
*(uint64_t*)0x20000038 = 0;
*(uint64_t*)0x20000100 = 0x77359400;
*(uint64_t*)0x20000108 = 0;
	syscall(__NR_select, 0x40ul, 0x20000000ul, 0ul, 0ul, 0x20000100ul);
	return 0;
}
