// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

#define BITMASK(bf_off,bf_len) (((1ull << (bf_len)) - 1) << (bf_off))
#define STORE_BY_BITMASK(type,htobe,addr,val,bf_off,bf_len) *(type*)(addr) = htobe((htobe(*(type*)(addr)) & ~BITMASK((bf_off), (bf_len))) | (((type)(val) << (bf_off)) & BITMASK((bf_off), (bf_len))))

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socket, 0x10ul, 3ul, 6);
	if (res != -1)
		r[0] = res;
*(uint64_t*)0x200043c0 = 0;
*(uint32_t*)0x200043c8 = 0;
*(uint64_t*)0x200043d0 = 0x20001700;
*(uint64_t*)0x20001700 = 0x20001340;
*(uint32_t*)0x20001340 = 0x18;
*(uint16_t*)0x20001344 = 0x25;
*(uint16_t*)0x20001346 = 0xd03;
*(uint32_t*)0x20001348 = 0;
*(uint32_t*)0x2000134c = 0;
*(uint16_t*)0x20001350 = 7;
STORE_BY_BITMASK(uint16_t, , 0x20001352, 0, 0, 14);
STORE_BY_BITMASK(uint16_t, , 0x20001353, 0, 6, 1);
STORE_BY_BITMASK(uint16_t, , 0x20001353, 0, 7, 1);
memcpy((void*)0x20001354, "-@\000", 3);
*(uint64_t*)0x20001708 = 0x18;
*(uint64_t*)0x200043d8 = 1;
*(uint64_t*)0x200043e0 = 0;
*(uint64_t*)0x200043e8 = 0;
*(uint32_t*)0x200043f0 = 0;
	syscall(__NR_sendmsg, r[0], 0x200043c0ul, 0ul);
	return 0;
}
