// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[2] = {0xffffffffffffffff, 0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socket, 0x10ul, 3ul, 4);
	if (res != -1)
		r[0] = res;
*(uint16_t*)0x20000200 = 0x10;
memcpy((void*)0x20000202, "\x4c\xc3\x4c\x70\x9e\x67\x4f\x8b\xa4\xf1\x18\x06\x1d\x3a\xea\x29\xaa\x60\x2b\x8a\xdc\xec\x04\x6f\x16\x45\xf7\x38\xbb\x62\x93\xed\xe5\x09\xc9\x6a\x32\xa2\x9d\x51\xae\xd8\x64\x88\x33\x64\xaf\xb6\x4d\x02\x14\x7f\x13\x4c\x46\xff\x00\xd8\x49\x02\xb4\x2f\x54\x62\xbc\x81\x6c\x6e\xfc\x81\x68\xcc\xc9\xa7\x2d\x35\x39\x55\x65\x5c\xcc\x5b\xb7\x16\xbc\x0f\xc1\x56\xdb\xbb\x28\x10\x5c\xa2\x29\x2d\xd8\x41\xb5\x68\x4a\x77\x36\x59\x1c\x3a\x73\x4a\xe7\x0b\xb2\xb9\xd9\x10\x1c\x53\x5c\x95\x83\xcb\x7e\x48\x3c\xfc\x4b\x74", 126);
	syscall(__NR_bind, r[0], 0x20000200ul, 0x80ul);
	res = syscall(__NR_socket, 2ul, 1ul, 0);
	if (res != -1)
		r[1] = res;
	syscall(__NR_close, r[1]);
	return 0;
}
