// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socket, 0x10ul, 3ul, 0x10);
	if (res != -1)
		r[0] = res;
*(uint64_t*)0x200000c0 = 0;
*(uint32_t*)0x200000c8 = 0;
*(uint64_t*)0x200000d0 = 0x20000100;
*(uint64_t*)0x20000100 = 0x20000140;
*(uint32_t*)0x20000140 = 0x1c;
*(uint16_t*)0x20000144 = 0;
*(uint16_t*)0x20000146 = 5;
*(uint32_t*)0x20000148 = 0;
*(uint32_t*)0x2000014c = 0;
*(uint8_t*)0x20000150 = 6;
*(uint8_t*)0x20000151 = 0;
*(uint16_t*)0x20000152 = 0;
*(uint16_t*)0x20000154 = 8;
*(uint16_t*)0x20000156 = 3;
*(uint32_t*)0x20000158 = 0;
*(uint64_t*)0x20000108 = 0x1c;
*(uint64_t*)0x200000d8 = 1;
*(uint64_t*)0x200000e0 = 0;
*(uint64_t*)0x200000e8 = 0;
*(uint32_t*)0x200000f0 = 0;
	syscall(__NR_sendmsg, r[0], 0x200000c0ul, 0ul);
*(uint64_t*)0x200021c0 = 0;
*(uint32_t*)0x200021c8 = 0;
*(uint64_t*)0x200021d0 = 0x200020c0;
*(uint64_t*)0x200020c0 = 0;
*(uint64_t*)0x200020c8 = 0;
*(uint64_t*)0x200020d0 = 0;
*(uint64_t*)0x200020d8 = 0;
*(uint64_t*)0x200020e0 = 0;
*(uint64_t*)0x200020e8 = 0;
*(uint64_t*)0x200020f0 = 0;
*(uint64_t*)0x200020f8 = 0;
*(uint64_t*)0x20002100 = 0;
*(uint64_t*)0x20002108 = 0;
*(uint64_t*)0x20002110 = 0;
*(uint64_t*)0x20002118 = 0;
*(uint64_t*)0x20002120 = 0;
*(uint64_t*)0x20002128 = 0;
*(uint64_t*)0x20002130 = 0;
*(uint64_t*)0x20002138 = 0;
*(uint64_t*)0x20002140 = 0;
*(uint64_t*)0x20002148 = 0;
*(uint64_t*)0x200021d8 = 9;
*(uint64_t*)0x200021e0 = 0;
*(uint64_t*)0x200021e8 = 0;
*(uint32_t*)0x200021f0 = 0;
*(uint32_t*)0x200021f8 = 0;
	syscall(__NR_recvmmsg, r[0], 0x200021c0ul, 1ul, 0x2102ul, 0ul);
	return 0;
}
