// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

#ifndef __NR_execveat
#define __NR_execveat 322
#endif
#ifndef __NR_memfd_create
#define __NR_memfd_create 319
#endif

uint64_t r[2] = {0xffffffffffffffff, 0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_pipe, 0x20000380ul);
	if (res != -1)
r[0] = *(uint32_t*)0x20000380;
memcpy((void*)0x20000080, "\323\341\213\365Vz|D\r\224a\275No\305\001\305l\334\227\024\213\234\347\255)\262\264\030\v\373\027)\373C\310-,%6\035\244# \352b\310\306\356\037\'\315\345\257\335O\215Hg4BW\256\233?R\311\375\356\326!_\366\261F]Q\310\236fXh)\242>\334\250\364\001\2707\"\342\340\bs\026\005\311\2605\305\000jK\231\303\333\343\336\270\326V\000\b\000\000\000\000\000\000\000\000\000", 124);
	res = syscall(__NR_memfd_create, 0x20000080ul, 0ul);
	if (res != -1)
		r[1] = res;
memcpy((void*)0x20000200, "\t\t\n#", 4);
	syscall(__NR_write, r[1], 0x20000200ul, 0x58ul);
	syscall(__NR_dup3, r[1], r[0], 0ul);
memset((void*)0x200001c0, 0, 1);
	syscall(__NR_execveat, r[0], 0x200001c0ul, 0ul, 0ul, 0x1000ul);
	return 0;
}
