// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socket, 0xaul, 2ul, 0x88);
	if (res != -1)
		r[0] = res;
*(uint64_t*)0x20002b40 = 0x200004c0;
*(uint16_t*)0x200004c0 = 0xa;
*(uint16_t*)0x200004c2 = htobe16(0x4e20);
*(uint32_t*)0x200004c4 = htobe32(0);
memset((void*)0x200004c8, 0, 16);
*(uint32_t*)0x200004d8 = 0;
*(uint32_t*)0x20002b48 = 0x1c;
*(uint64_t*)0x20002b50 = 0;
*(uint64_t*)0x20002b58 = 0;
*(uint64_t*)0x20002b60 = 0;
*(uint64_t*)0x20002b68 = 0;
*(uint32_t*)0x20002b70 = 0;
*(uint32_t*)0x20002b78 = 0;
*(uint64_t*)0x20002b80 = 0x20000040;
*(uint16_t*)0x20000040 = 0xa;
*(uint16_t*)0x20000042 = htobe16(0x4e22);
*(uint32_t*)0x20000044 = htobe32(0);
*(uint8_t*)0x20000048 = 0xfc;
*(uint8_t*)0x20000049 = 1;
memset((void*)0x2000004a, 0, 13);
*(uint8_t*)0x20000057 = 0;
*(uint32_t*)0x20000058 = 0;
*(uint32_t*)0x20002b88 = 0x1c;
*(uint64_t*)0x20002b90 = 0;
*(uint64_t*)0x20002b98 = 0;
*(uint64_t*)0x20002ba0 = 0;
*(uint64_t*)0x20002ba8 = 0;
*(uint32_t*)0x20002bb0 = 0;
*(uint32_t*)0x20002bb8 = 0;
	syscall(__NR_sendmmsg, r[0], 0x20002b40ul, 2ul, 0ul);
	return 0;
}
