// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
memcpy((void*)0x20001480, "/dev/snd/seq\000", 13);
	res = syscall(__NR_openat, 0xffffffffffffff9cul, 0x20001480ul, 0ul, 0);
	if (res != -1)
		r[0] = res;
*(uint32_t*)0x20000000 = 0xffff7fff;
*(uint32_t*)0x20000004 = 0;
memcpy((void*)0x20000008, "client0\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000", 64);
*(uint32_t*)0x20000048 = 0;
memcpy((void*)0x2000004c, "\xcd\x09\xbf\x36\x4a\xf5\x51\xa9", 8);
memcpy((void*)0x20000054, "\x1b\x5b\x48\x0e\x7a\xe5\xa3\x4c\x74\xa2\xed\x22\x4d\x2c\x90\x26\xbd\x51\x05\xe9\xd7\xce\xc7\x66\x00\xe7\xdb\x66\x50\x02\x9c\x25", 32);
*(uint32_t*)0x20000074 = 0;
*(uint32_t*)0x20000078 = 0;
*(uint32_t*)0x2000007c = 0;
*(uint32_t*)0x20000080 = 0;
memset((void*)0x20000084, 0, 56);
	syscall(__NR_ioctl, r[0], 0xc0bc5351, 0x20000000ul);
	return 0;
}
