// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[2] = {0xffffffffffffffff, 0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socketpair, 1ul, 5ul, 0, 0x20000040ul);
	if (res != -1) {
r[0] = *(uint32_t*)0x20000040;
r[1] = *(uint32_t*)0x20000044;
	}
*(uint64_t*)0x20000600 = 0;
*(uint32_t*)0x20000608 = 0;
*(uint64_t*)0x20000610 = 0;
*(uint64_t*)0x20000618 = 0;
*(uint64_t*)0x20000620 = 0;
*(uint64_t*)0x20000628 = 0;
*(uint32_t*)0x20000630 = 0;
	syscall(__NR_sendmsg, r[0], 0x20000600ul, 0ul);
*(uint64_t*)0x20001a40 = 0;
*(uint32_t*)0x20001a48 = 0;
*(uint64_t*)0x20001a50 = 0x20001480;
*(uint64_t*)0x20001480 = 0x20002080;
memset((void*)0x20002080, 135, 1);
*(uint64_t*)0x20001488 = 1;
*(uint64_t*)0x20001a58 = 1;
*(uint64_t*)0x20001a60 = 0;
*(uint64_t*)0x20001a68 = 0;
*(uint32_t*)0x20001a70 = 0;
*(uint32_t*)0x20001a78 = 0;
	syscall(__NR_sendmmsg, -1, 0x20001a40ul, 1ul, 0ul);
*(uint64_t*)0x20002000 = 0;
*(uint32_t*)0x20002008 = 0;
*(uint64_t*)0x20002010 = 0;
*(uint64_t*)0x20002018 = 0;
*(uint64_t*)0x20002020 = 0;
*(uint64_t*)0x20002028 = 0;
*(uint32_t*)0x20002030 = 0;
*(uint32_t*)0x20002038 = 0;
*(uint64_t*)0x20002040 = 0;
*(uint32_t*)0x20002048 = 0;
*(uint64_t*)0x20002050 = 0;
*(uint64_t*)0x20002058 = 0;
*(uint64_t*)0x20002060 = 0;
*(uint64_t*)0x20002068 = 0;
*(uint32_t*)0x20002070 = 0;
*(uint32_t*)0x20002078 = 0;
	syscall(__NR_recvmmsg, r[1], 0x20002000ul, 0x40000000000030eul, 0x40012002ul, 0ul);
	return 0;
}
