// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <arpa/inet.h>
#include <endian.h>
#include <errno.h>
#include <net/if.h>
#include <netinet/in.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

#include <linux/genetlink.h>
#include <linux/if_addr.h>
#include <linux/if_link.h>
#include <linux/in6.h>
#include <linux/neighbour.h>
#include <linux/net.h>
#include <linux/netlink.h>
#include <linux/rtnetlink.h>
#include <linux/veth.h>

#define BITMASK(bf_off,bf_len) (((1ull << (bf_len)) - 1) << (bf_off))
#define STORE_BY_BITMASK(type,htobe,addr,val,bf_off,bf_len) *(type*)(addr) = htobe((htobe(*(type*)(addr)) & ~BITMASK((bf_off), (bf_len))) | (((type)(val) << (bf_off)) & BITMASK((bf_off), (bf_len))))

struct nlmsg {
	char* pos;
	int nesting;
	struct nlattr* nested[8];
	char buf[4096];
};

static void netlink_init(struct nlmsg* nlmsg, int typ, int flags,
			 const void* data, int size)
{
	memset(nlmsg, 0, sizeof(*nlmsg));
	struct nlmsghdr* hdr = (struct nlmsghdr*)nlmsg->buf;
	hdr->nlmsg_type = typ;
	hdr->nlmsg_flags = NLM_F_REQUEST | NLM_F_ACK | flags;
	memcpy(hdr + 1, data, size);
	nlmsg->pos = (char*)(hdr + 1) + NLMSG_ALIGN(size);
}

static void netlink_attr(struct nlmsg* nlmsg, int typ,
			 const void* data, int size)
{
	struct nlattr* attr = (struct nlattr*)nlmsg->pos;
	attr->nla_len = sizeof(*attr) + size;
	attr->nla_type = typ;
	if (size > 0)
		memcpy(attr + 1, data, size);
	nlmsg->pos += NLMSG_ALIGN(attr->nla_len);
}

static int netlink_send_ext(struct nlmsg* nlmsg, int sock,
			    uint16_t reply_type, int* reply_len, bool dofail)
{
	if (nlmsg->pos > nlmsg->buf + sizeof(nlmsg->buf) || nlmsg->nesting)
	exit(1);
	struct nlmsghdr* hdr = (struct nlmsghdr*)nlmsg->buf;
	hdr->nlmsg_len = nlmsg->pos - nlmsg->buf;
	struct sockaddr_nl addr;
	memset(&addr, 0, sizeof(addr));
	addr.nl_family = AF_NETLINK;
	ssize_t n = sendto(sock, nlmsg->buf, hdr->nlmsg_len, 0, (struct sockaddr*)&addr, sizeof(addr));
	if (n != (ssize_t)hdr->nlmsg_len) {
		if (dofail)
	exit(1);
		return -1;
	}
	n = recv(sock, nlmsg->buf, sizeof(nlmsg->buf), 0);
	if (reply_len)
		*reply_len = 0;
	if (n < 0) {
		if (dofail)
	exit(1);
		return -1;
	}
	if (n < (ssize_t)sizeof(struct nlmsghdr)) {
		errno = EINVAL;
		if (dofail)
	exit(1);
		return -1;
	}
	if (hdr->nlmsg_type == NLMSG_DONE)
		return 0;
	if (reply_len && hdr->nlmsg_type == reply_type) {
		*reply_len = n;
		return 0;
	}
	if (n < (ssize_t)(sizeof(struct nlmsghdr) + sizeof(struct nlmsgerr))) {
		errno = EINVAL;
		if (dofail)
	exit(1);
		return -1;
	}
	if (hdr->nlmsg_type != NLMSG_ERROR) {
		errno = EINVAL;
		if (dofail)
	exit(1);
		return -1;
	}
	errno = -((struct nlmsgerr*)(hdr + 1))->error;
	return -errno;
}

static int netlink_query_family_id(struct nlmsg* nlmsg, int sock, const char* family_name, bool dofail)
{
	struct genlmsghdr genlhdr;
	memset(&genlhdr, 0, sizeof(genlhdr));
	genlhdr.cmd = CTRL_CMD_GETFAMILY;
	netlink_init(nlmsg, GENL_ID_CTRL, 0, &genlhdr, sizeof(genlhdr));
	netlink_attr(nlmsg, CTRL_ATTR_FAMILY_NAME, family_name, strnlen(family_name, GENL_NAMSIZ - 1) + 1);
	int n = 0;
	int err = netlink_send_ext(nlmsg, sock, GENL_ID_CTRL, &n, dofail);
	if (err < 0) {
		return -1;
	}
	uint16_t id = 0;
	struct nlattr* attr = (struct nlattr*)(nlmsg->buf + NLMSG_HDRLEN + NLMSG_ALIGN(sizeof(genlhdr)));
	for (; (char*)attr < nlmsg->buf + n; attr = (struct nlattr*)((char*)attr + NLMSG_ALIGN(attr->nla_len))) {
		if (attr->nla_type == CTRL_ATTR_FAMILY_ID) {
			id = *(uint16_t*)(attr + 1);
			break;
		}
	}
	if (!id) {
		errno = EINVAL;
		return -1;
	}
	recv(sock, nlmsg->buf, sizeof(nlmsg->buf), 0);
	return id;
}

static long syz_genetlink_get_family_id(volatile long name, volatile long sock_arg)
{
	int fd = sock_arg;
	if (fd < 0) {
		fd = socket(AF_NETLINK, SOCK_RAW, NETLINK_GENERIC);
		if (fd == -1) {
			return -1;
		}
	}
	struct nlmsg nlmsg_tmp;
	int ret = netlink_query_family_id(&nlmsg_tmp, fd, (char*)name, false);
	if ((int)sock_arg < 0)
		close(fd);
	if (ret < 0) {
		return -1;
	}
	return ret;
}

uint64_t r[2] = {0xffffffffffffffff, 0x0};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socket, 0x10ul, 3ul, 0x10);
	if (res != -1)
		r[0] = res;
memcpy((void*)0x20000100, "ethtool\000", 8);
	res = -1;
res = syz_genetlink_get_family_id(0x20000100, -1);
	if (res != -1)
		r[1] = res;
*(uint64_t*)0x20000200 = 0;
*(uint32_t*)0x20000208 = 0;
*(uint64_t*)0x20000210 = 0x200001c0;
*(uint64_t*)0x200001c0 = 0x20000800;
*(uint32_t*)0x20000800 = 0x170;
*(uint16_t*)0x20000804 = r[1];
*(uint16_t*)0x20000806 = 1;
*(uint32_t*)0x20000808 = 0;
*(uint32_t*)0x2000080c = 0;
*(uint8_t*)0x20000810 = 0xe;
*(uint8_t*)0x20000811 = 0;
*(uint16_t*)0x20000812 = 0;
*(uint16_t*)0x20000814 = 0x15c;
STORE_BY_BITMASK(uint16_t, , 0x20000816, 2, 0, 14);
STORE_BY_BITMASK(uint16_t, , 0x20000817, 0, 6, 1);
STORE_BY_BITMASK(uint16_t, , 0x20000817, 1, 7, 1);
*(uint16_t*)0x20000818 = 0x88;
STORE_BY_BITMASK(uint16_t, , 0x2000081a, 3, 0, 14);
STORE_BY_BITMASK(uint16_t, , 0x2000081b, 0, 6, 1);
STORE_BY_BITMASK(uint16_t, , 0x2000081b, 1, 7, 1);
*(uint16_t*)0x2000081c = 0xa5;
STORE_BY_BITMASK(uint16_t, , 0x2000081e, 1, 0, 14);
STORE_BY_BITMASK(uint16_t, , 0x2000081f, 0, 6, 1);
STORE_BY_BITMASK(uint16_t, , 0x2000081f, 1, 7, 1);
*(uint16_t*)0x20000820 = 0x1d;
*(uint16_t*)0x20000822 = 2;
memcpy((void*)0x20000824, "*\'/@!,$[@(.\'{$-{\\!%^,(/@\000", 25);
*(uint16_t*)0x20000840 = 8;
*(uint16_t*)0x20000842 = 2;
memcpy((void*)0x20000844, "}^&\000", 4);
*(uint16_t*)0x20000848 = 8;
*(uint16_t*)0x2000084a = 1;
*(uint32_t*)0x2000084c = 0;
*(uint16_t*)0x20000850 = 8;
*(uint16_t*)0x20000852 = 1;
*(uint32_t*)0x20000854 = 0;
*(uint16_t*)0x20000858 = 8;
*(uint16_t*)0x2000085a = 1;
*(uint32_t*)0x2000085c = 0;
*(uint16_t*)0x20000860 = 0x18;
STORE_BY_BITMASK(uint16_t, , 0x20000862, 1, 0, 14);
STORE_BY_BITMASK(uint16_t, , 0x20000863, 0, 6, 1);
STORE_BY_BITMASK(uint16_t, , 0x20000863, 1, 7, 1);
*(uint16_t*)0x20000864 = 0;
*(uint16_t*)0x20000866 = 2;
memcpy((void*)0x20000868, ")\231%\\\\+-{\000", 9);
*(uint16_t*)0x20000874 = 8;
*(uint16_t*)0x20000876 = 1;
*(uint32_t*)0x20000878 = 0;
*(uint16_t*)0x2000087c = 7;
*(uint16_t*)0x2000087e = 2;
memcpy((void*)0x20000880, "5!\200", 3);
*(uint16_t*)0x20000884 = 0x18;
STORE_BY_BITMASK(uint16_t, , 0x20000886, 1, 0, 14);
STORE_BY_BITMASK(uint16_t, , 0x20000887, 0, 6, 1);
STORE_BY_BITMASK(uint16_t, , 0x20000887, 1, 7, 1);
*(uint16_t*)0x20000888 = 5;
*(uint16_t*)0x2000088a = 2;
memset((void*)0x2000088c, 0, 1);
*(uint16_t*)0x20000890 = 8;
*(uint16_t*)0x20000892 = 2;
memcpy((void*)0x20000894, "@/+\000", 4);
*(uint16_t*)0x20000898 = 4;
*(uint16_t*)0x2000089a = 3;
*(uint16_t*)0x2000089c = 0x10;
STORE_BY_BITMASK(uint16_t, , 0x2000089e, 1, 0, 14);
STORE_BY_BITMASK(uint16_t, , 0x2000089f, 0, 6, 1);
STORE_BY_BITMASK(uint16_t, , 0x2000089f, 1, 7, 1);
*(uint16_t*)0x200008a0 = 4;
*(uint16_t*)0x200008a2 = 3;
*(uint16_t*)0x200008a4 = 4;
*(uint16_t*)0x200008a6 = 3;
*(uint16_t*)0x200008a8 = 4;
*(uint16_t*)0x200008aa = 3;
*(uint16_t*)0x200008ac = 0xcd;
*(uint16_t*)0x200008ae = 5;
memcpy((void*)0x200008b0, "\x2b\xf8\x24\x64\x0a\x1a\xd4\xcd\x58\x61\x2c\x26\x3c\x2d\x59\x7e\xb8\xfe\x05\x99\x49\x3f\x91\xbe\x48\x1c\xcb\x1a\x92\xc6\xb0\x7d\xca\x58\xed\x65\xc4\xac\xa3\x4e\xfe\x02\x9a\x63\xbd\xbf\x2b\xd3\xe6\x3d\x09\xe4\x2f\x48\xa2\x40\x8e\xe6\xab\xa3\x60\x08\xcb\xdc\x3e\x22\xa0\x2f\xe3\x1e\x81\x8d\x64\x74\x6d\x06\xdd\x99\x48\x5c\xe6\xa3\x19\x91\x95\x4f\x62\x8b\x0c\xe8\x34\xf1\xf4\xd5\xae\x44\x0f\x80\x02\xaa\x98\x5e\x80\x95\x3a\x9b\x36\x61\xa2\x84\xa4\x56\xf6\x14\x66\x21\x48\x77\x12\x05\x4f\x17\x2f\xa0\xc6\x40\xb3\x91\x47\xfc\x75\x96\x5e\xc8\x33\x8b\xbc\xeb\x62\xa5\xe7\x70\x56\x24\xf0\xab\x6c\x20\xb8\x42\x43\x36\x09\xf8\x9c\xf8\xaf\xda\x9c\x98\xd2\x1e\xdd\x32\x44\xd7\x58\xa2\xbf\xb4\xc4\xb8\x54\x7e\x7d\x02\x6f\x41\xfd\x34\x1c\x3f\x4a\x1b\x02\x17\x29\xbb\x6c\x0b\x4a\xea\x63\x92\x99\x48\xe6\xd8\x1a\xe9\x92", 201);
*(uint64_t*)0x200001c8 = 0x170;
*(uint64_t*)0x20000218 = 1;
*(uint64_t*)0x20000220 = 0;
*(uint64_t*)0x20000228 = 0;
*(uint32_t*)0x20000230 = 0;
	syscall(__NR_sendmsg, r[0], 0x20000200ul, 0ul);
	return 0;
}
