// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[3] = {0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socket, 0xaul, 3ul, 2);
	if (res != -1)
		r[0] = res;
*(uint8_t*)0x20000000 = 0;
*(uint8_t*)0x20000001 = 0;
memset((void*)0x20000002, 0, 6);
	syscall(__NR_setsockopt, r[0], 0x29, 0x36, 0x20000000ul, 8ul);
memcpy((void*)0x20000000, "/dev/nvram\000", 11);
	res = syscall(__NR_openat, 0xffffffffffffff9cul, 0x20000000ul, 0ul, 0ul);
	if (res != -1)
		r[1] = res;
memcpy((void*)0x20000040, "/proc/self\000", 11);
	syscall(__NR_openat, 0xffffffffffffff9cul, 0x20000040ul, 0x741800ul, 0ul);
	syscall(__NR_ppoll, 0ul, 0ul, 0ul, 0ul, 0ul);
	syscall(__NR_getsockopt, r[1], 0x29, 0x20, 0ul, 0ul);
	res = syscall(__NR_socket, 0x10ul, 3ul, 4);
	if (res != -1)
		r[2] = res;
*(uint64_t*)0x20000300 = 0x20000180;
*(uint16_t*)0x20000180 = 0x10;
*(uint16_t*)0x20000182 = 0;
*(uint32_t*)0x20000184 = 0;
*(uint32_t*)0x20000188 = 0;
*(uint32_t*)0x20000308 = 0;
*(uint64_t*)0x20000310 = 0x200002c0;
*(uint64_t*)0x200002c0 = 0x20000340;
*(uint32_t*)0x20000340 = 0xcc;
*(uint16_t*)0x20000344 = 0;
*(uint16_t*)0x20000346 = 0;
*(uint32_t*)0x20000348 = 0;
*(uint32_t*)0x2000034c = 0;
*(uint8_t*)0x20000350 = 9;
*(uint8_t*)0x20000351 = 0;
*(uint16_t*)0x20000352 = 0;
*(uint16_t*)0x20000354 = 0;
*(uint16_t*)0x20000356 = 1;
memcpy((void*)0x20000358, "pci\000", 4);
*(uint16_t*)0x2000035c = 0;
*(uint16_t*)0x2000035e = 2;
memcpy((void*)0x20000360, "0000:00:10.0\000", 13);
*(uint16_t*)0x20000370 = 0;
*(uint16_t*)0x20000372 = 3;
*(uint32_t*)0x20000374 = 0;
*(uint16_t*)0x20000378 = 0;
*(uint16_t*)0x2000037a = 9;
*(uint32_t*)0x2000037c = 0;
*(uint16_t*)0x20000380 = 0;
*(uint16_t*)0x20000382 = 1;
memcpy((void*)0x20000384, "netdevsim\000", 10);
*(uint16_t*)0x20000390 = 0;
*(uint16_t*)0x20000392 = 2;
memcpy((void*)0x20000394, "netdevsim", 9);
*(uint8_t*)0x2000039d = 0x30;
*(uint8_t*)0x2000039e = 0;
*(uint16_t*)0x200003a0 = 0;
*(uint16_t*)0x200003a2 = 3;
*(uint32_t*)0x200003a4 = 0;
*(uint16_t*)0x200003a8 = 0;
*(uint16_t*)0x200003aa = 9;
*(uint32_t*)0x200003ac = 0;
*(uint16_t*)0x200003b0 = 0;
*(uint16_t*)0x200003b2 = 1;
memcpy((void*)0x200003b4, "netdevsim\000", 10);
*(uint16_t*)0x200003c0 = 0;
*(uint16_t*)0x200003c2 = 2;
memcpy((void*)0x200003c4, "netdevsim", 9);
*(uint8_t*)0x200003cd = 0x30;
*(uint8_t*)0x200003ce = 0;
*(uint16_t*)0x200003d0 = 0;
*(uint16_t*)0x200003d2 = 3;
*(uint32_t*)0x200003d4 = 0;
*(uint16_t*)0x200003d8 = 0;
*(uint16_t*)0x200003da = 9;
*(uint32_t*)0x200003dc = 0;
*(uint16_t*)0x200003e0 = 0;
*(uint16_t*)0x200003e2 = 1;
memcpy((void*)0x200003e4, "pci\000", 4);
*(uint16_t*)0x200003e8 = 0;
*(uint16_t*)0x200003ea = 2;
memcpy((void*)0x200003ec, "0000:00:10.0\000", 13);
*(uint16_t*)0x200003fc = 0;
*(uint16_t*)0x200003fe = 3;
*(uint32_t*)0x20000400 = 0;
*(uint16_t*)0x20000404 = 0;
*(uint16_t*)0x20000406 = 9;
*(uint32_t*)0x20000408 = 0;
*(uint64_t*)0x200002c8 = 0xcc;
*(uint64_t*)0x20000318 = 1;
*(uint64_t*)0x20000320 = 0;
*(uint64_t*)0x20000328 = 0;
*(uint32_t*)0x20000330 = 0;
	syscall(__NR_sendmsg, r[2], 0x20000300ul, 0ul);
	return 0;
}
