// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socket, 0xaul, 1ul, 0);
	if (res != -1)
		r[0] = res;
*(uint32_t*)0x20001380 = 1;
	syscall(__NR_setsockopt, r[0], 6, 0x13, 0x20001380ul, 4ul);
*(uint32_t*)0x200003c0 = 1;
	syscall(__NR_setsockopt, r[0], 6, 0x14, 0x200003c0ul, 4ul);
*(uint16_t*)0x20001340 = 0xa;
*(uint16_t*)0x20001342 = htobe16(0);
*(uint32_t*)0x20001344 = htobe32(0);
*(uint64_t*)0x20001348 = htobe64(0);
*(uint64_t*)0x20001350 = htobe64(1);
*(uint32_t*)0x20001358 = 0;
	syscall(__NR_connect, r[0], 0x20001340ul, 0x1cul);
*(uint64_t*)0x20000ac0 = 0;
*(uint32_t*)0x20000ac8 = 0;
*(uint64_t*)0x20000ad0 = 0x20000940;
*(uint64_t*)0x20000940 = 0x20000c00;
memset((void*)0x20000c00, 39, 1);
*(uint64_t*)0x20000948 = 1;
*(uint64_t*)0x20000ad8 = 1;
*(uint64_t*)0x20000ae0 = 0;
*(uint64_t*)0x20000ae8 = 0;
*(uint32_t*)0x20000af0 = 0;
*(uint32_t*)0x20000af8 = 0;
	syscall(__NR_sendmmsg, r[0], 0x20000ac0ul, 1ul, 0ul);
*(uint32_t*)0x20002e80 = 0;
	syscall(__NR_setsockopt, r[0], 6, 0x13, 0x20002e80ul, 4ul);
*(uint64_t*)0x20000540 = 0;
*(uint32_t*)0x20000548 = 0;
*(uint64_t*)0x20000550 = 0x20000240;
*(uint64_t*)0x20000240 = 0x200003c0;
*(uint64_t*)0x20000248 = 0x74;
*(uint64_t*)0x20000558 = 1;
*(uint64_t*)0x20000560 = 0;
*(uint64_t*)0x20000568 = 0;
*(uint32_t*)0x20000570 = 0;
	syscall(__NR_recvmsg, r[0], 0x20000540ul, 0ul, 0);
	return 0;
}
