// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socket, 0xaul, 2ul, 0x88);
	if (res != -1)
		r[0] = res;
*(uint32_t*)0x20001140 = htobe32(-1);
memset((void*)0x20001150, 0, 10);
memset((void*)0x2000115a, 255, 2);
*(uint32_t*)0x2000115c = htobe32(0x7f000001);
*(uint16_t*)0x20001160 = htobe16(0);
*(uint16_t*)0x20001162 = htobe16(0);
*(uint16_t*)0x20001164 = htobe16(0);
*(uint16_t*)0x20001166 = htobe16(0);
*(uint16_t*)0x20001168 = 0xa;
*(uint8_t*)0x2000116a = 0;
*(uint8_t*)0x2000116b = 0;
*(uint8_t*)0x2000116c = 0;
*(uint32_t*)0x20001170 = 0;
*(uint32_t*)0x20001174 = 0xee01;
*(uint64_t*)0x20001178 = 0;
*(uint64_t*)0x20001180 = 0;
*(uint64_t*)0x20001188 = 0;
*(uint64_t*)0x20001190 = 0;
*(uint64_t*)0x20001198 = 0;
*(uint64_t*)0x200011a0 = 0;
*(uint64_t*)0x200011a8 = 0;
*(uint64_t*)0x200011b0 = 0;
*(uint64_t*)0x200011b8 = 0;
*(uint64_t*)0x200011c0 = 0;
*(uint64_t*)0x200011c8 = 0;
*(uint64_t*)0x200011d0 = 0;
*(uint32_t*)0x200011d8 = 0;
*(uint32_t*)0x200011dc = 0;
*(uint8_t*)0x200011e0 = 0;
*(uint8_t*)0x200011e1 = 0;
*(uint8_t*)0x200011e2 = 0;
*(uint8_t*)0x200011e3 = 0;
memcpy((void*)0x200011e8, " \001\000\000\000\000\000\000\000\000\000\000\000\000\000\002", 16);
*(uint32_t*)0x200011f8 = htobe32(0);
*(uint8_t*)0x200011fc = 0x33;
*(uint16_t*)0x20001200 = 0;
*(uint8_t*)0x20001204 = 0xac;
*(uint8_t*)0x20001205 = 0x1e;
*(uint8_t*)0x20001206 = 0;
*(uint8_t*)0x20001207 = 1;
*(uint32_t*)0x20001214 = 0;
*(uint8_t*)0x20001218 = 0;
*(uint8_t*)0x20001219 = 0;
*(uint8_t*)0x2000121a = 0;
*(uint32_t*)0x2000121c = 0;
*(uint32_t*)0x20001220 = 0;
*(uint32_t*)0x20001224 = 0;
	syscall(__NR_setsockopt, r[0], 0x29, 0x23, 0x20001140ul, 0xe8ul);
	return 0;
}
