// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <fcntl.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

static long syz_open_dev(volatile long a0, volatile long a1, volatile long a2)
{
	if (a0 == 0xc || a0 == 0xb) {
		char buf[128];
		sprintf(buf, "/dev/%s/%d:%d", a0 == 0xc ? "char" : "block", (uint8_t)a1, (uint8_t)a2);
		return open(buf, O_RDWR, 0);
	} else {
		char buf[1024];
		char* hash;
		strncpy(buf, (char*)a0, sizeof(buf) - 1);
		buf[sizeof(buf) - 1] = 0;
		while ((hash = strchr(buf, '#'))) {
			*hash = '0' + (char)(a1 % 10);
			a1 /= 10;
		}
		return open(buf, a2, 0);
	}
}

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
memcpy((void*)0x20000080, "/dev/loop#\000", 11);
	res = -1;
res = syz_open_dev(0x20000080, 0x7ffffffb, 0);
	if (res != -1)
		r[0] = res;
*(uint64_t*)0x200000c0 = 0;
*(uint64_t*)0x200000c8 = 0;
*(uint64_t*)0x200000d0 = 0;
*(uint64_t*)0x200000d8 = 0;
*(uint64_t*)0x200000e0 = 0;
*(uint32_t*)0x200000e8 = 0;
*(uint32_t*)0x200000ec = 5;
*(uint32_t*)0x200000f0 = 0;
*(uint32_t*)0x200000f4 = 0;
memcpy((void*)0x200000f8, "\xd0\x07\x3a\x03\x84\xe2\x09\x53\x79\xac\xa7\x63\xfd\xa6\x4a\x4f\x6c\x77\x15\x8d\xe9\xe7\xb3\xc2\x9d\x69\xbf\xd0\x4d\x0a\x2b\x52\x1e\x80\x80\x7b\x84\xd0\xb1\xdd\x0c\x58\xa2\xb3\x6e\xac\xdb\x09\x94\x70\xee\xf7\x41\xc8\xc0\x1f\x5f\x64\x2c\xd3\xf7\x3e\x5a\x12", 64);
memcpy((void*)0x20000138, "\xee\x37\x4c\x21\x06\x21\x73\xc3\x39\xa2\xa5\x45\x32\x26\xc1\xb5\xd1\xdf\x13\xcb\x19\x86\x54\xff\x3c\x8e\x88\x25\x42\xae\x5c\xba\x09\xc3\xdc\x73\x90\xd2\x8e\x03\x87\xa1\x32\x1e\x29\x27\x7b\x35\x0a\x60\x3d\x9f\xc7\xa9\xec\xf9\x00\x28\x58\x00\x5b\xab\xa6\x1d", 64);
memcpy((void*)0x20000178, "\x73\xcf\xe1\xf9\xfc\x2d\x6b\x9d\x66\x89\x65\x16\x33\xfd\xc3\xaa\xcd\x81\x44\xb2\x97\x29\xb7\x49\xdf\x53\xe4\x63\x65\xb1\xd3\x85", 32);
*(uint64_t*)0x20000198 = 0;
*(uint64_t*)0x200001a0 = 0;
	syscall(__NR_ioctl, r[0], 0x4c04, 0x200000c0ul);
	return 0;
}
