// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socket, 0x10ul, 3ul, 0x10);
	if (res != -1)
		r[0] = res;
*(uint64_t*)0x20006080 = 0;
*(uint32_t*)0x20006088 = 0;
*(uint64_t*)0x20006090 = 0;
*(uint64_t*)0x20006098 = 0;
*(uint64_t*)0x200060a0 = 0;
*(uint64_t*)0x200060a8 = 0;
*(uint32_t*)0x200060b0 = 0;
*(uint32_t*)0x200060b8 = 0;
*(uint64_t*)0x200060c0 = 0;
*(uint32_t*)0x200060c8 = 0;
*(uint64_t*)0x200060d0 = 0;
*(uint64_t*)0x200060d8 = 0;
*(uint64_t*)0x200060e0 = 0x200041c0;
*(uint64_t*)0x200041c0 = 0x10;
*(uint32_t*)0x200041c8 = 1;
*(uint32_t*)0x200041cc = 2;
*(uint64_t*)0x200060e8 = 0x10;
*(uint32_t*)0x200060f0 = 0;
*(uint32_t*)0x200060f8 = 0;
	syscall(__NR_sendmmsg, r[0], 0x20006080ul, 2ul, 0ul);
	return 0;
}
