// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

#ifndef __NR_io_uring_setup
#define __NR_io_uring_setup 425
#endif

#define BITMASK(bf_off,bf_len) (((1ull << (bf_len)) - 1) << (bf_off))
#define STORE_BY_BITMASK(type,htobe,addr,val,bf_off,bf_len) *(type*)(addr) = htobe((htobe(*(type*)(addr)) & ~BITMASK((bf_off), (bf_len))) | (((type)(val) << (bf_off)) & BITMASK((bf_off), (bf_len))))

uint64_t r[4] = {0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0x0};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
memcpy((void*)0x20000000, "/dev/loop-control\000", 18);
	res = syscall(__NR_openat, 0xffffffffffffff9cul, 0x20000000ul, 0ul, 0ul);
	if (res != -1)
		r[0] = res;
	syscall(__NR_ioctl, r[0], 0x4c80, 0ul);
	res = syscall(__NR_io_uring_setup, 0, 0ul);
	if (res != -1)
		r[1] = res;
	syscall(__NR_mmap, 0x20ffc000ul, 0x1000ul, 0x200000cul, 0x8010ul, r[1], 0x8000000ul);
	syscall(__NR_mmap, 0x20ffb000ul, 0x2000ul, 0ul, 0x40010ul, r[1], 0x10000000ul);
	res = syscall(__NR_ioctl, -1, 0x4c80, 0ul);
	if (res != -1)
		r[2] = res;
	res = syscall(__NR_gettid);
	if (res != -1)
		r[3] = res;
*(uint32_t*)0x200000c0 = 0;
*(uint32_t*)0x200000c4 = 0x80;
*(uint8_t*)0x200000c8 = 0x7f;
*(uint8_t*)0x200000c9 = 0;
*(uint8_t*)0x200000ca = -1;
*(uint8_t*)0x200000cb = 0;
*(uint32_t*)0x200000cc = 0;
*(uint64_t*)0x200000d0 = 8;
*(uint64_t*)0x200000d8 = 1;
*(uint64_t*)0x200000e0 = 8;
STORE_BY_BITMASK(uint64_t, , 0x200000e8, 1, 0, 1);
STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 1, 1);
STORE_BY_BITMASK(uint64_t, , 0x200000e8, 1, 2, 1);
STORE_BY_BITMASK(uint64_t, , 0x200000e8, 1, 3, 1);
STORE_BY_BITMASK(uint64_t, , 0x200000e8, 1, 4, 1);
STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 5, 1);
STORE_BY_BITMASK(uint64_t, , 0x200000e8, 1, 6, 1);
STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 7, 1);
STORE_BY_BITMASK(uint64_t, , 0x200000e8, 1, 8, 1);
STORE_BY_BITMASK(uint64_t, , 0x200000e8, 1, 9, 1);
STORE_BY_BITMASK(uint64_t, , 0x200000e8, 1, 10, 1);
STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 11, 1);
STORE_BY_BITMASK(uint64_t, , 0x200000e8, 1, 12, 1);
STORE_BY_BITMASK(uint64_t, , 0x200000e8, 1, 13, 1);
STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 14, 1);
STORE_BY_BITMASK(uint64_t, , 0x200000e8, 1, 15, 2);
STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 17, 1);
STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 18, 1);
STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 19, 1);
STORE_BY_BITMASK(uint64_t, , 0x200000e8, 1, 20, 1);
STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 21, 1);
STORE_BY_BITMASK(uint64_t, , 0x200000e8, 1, 22, 1);
STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 23, 1);
STORE_BY_BITMASK(uint64_t, , 0x200000e8, 1, 24, 1);
STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 25, 1);
STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 26, 1);
STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 27, 1);
STORE_BY_BITMASK(uint64_t, , 0x200000e8, 1, 28, 1);
STORE_BY_BITMASK(uint64_t, , 0x200000e8, 1, 29, 1);
STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 30, 1);
STORE_BY_BITMASK(uint64_t, , 0x200000e8, 1, 31, 1);
STORE_BY_BITMASK(uint64_t, , 0x200000e8, 1, 32, 1);
STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 33, 1);
STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 34, 1);
STORE_BY_BITMASK(uint64_t, , 0x200000e8, 1, 35, 1);
STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 36, 1);
STORE_BY_BITMASK(uint64_t, , 0x200000e8, 1, 37, 1);
STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 38, 26);
*(uint32_t*)0x200000f0 = 0xfff;
*(uint32_t*)0x200000f4 = 0;
*(uint64_t*)0x200000f8 = 0x20000080;
*(uint64_t*)0x20000100 = 0;
*(uint64_t*)0x20000108 = 0x48002;
*(uint64_t*)0x20000110 = 0x10001;
*(uint32_t*)0x20000118 = 0xffffff7f;
*(uint32_t*)0x2000011c = 3;
*(uint64_t*)0x20000120 = 1;
*(uint32_t*)0x20000128 = 0x7fffffff;
*(uint16_t*)0x2000012c = 0x39b6;
*(uint16_t*)0x2000012e = 0;
*(uint32_t*)0x20000130 = 0x433;
*(uint32_t*)0x20000134 = 0;
*(uint64_t*)0x20000138 = 0x10001;
	syscall(__NR_perf_event_open, 0x200000c0ul, r[3], 4ul, -1, 0ul);
	syscall(__NR_ioctl, r[0], 0x4c81, r[2]);
	return 0;
}
