// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[9] = {0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socket, 0xaul, 2ul, 0x88);
	if (res != -1)
		r[0] = res;
*(uint8_t*)0x20000040 = 0xfe;
*(uint8_t*)0x20000041 = 0x88;
memset((void*)0x20000042, 0, 12);
*(uint8_t*)0x2000004e = 0;
*(uint8_t*)0x2000004f = 1;
*(uint8_t*)0x20000050 = 0xfc;
*(uint8_t*)0x20000051 = 1;
memset((void*)0x20000052, 0, 13);
*(uint8_t*)0x2000005f = 0;
*(uint8_t*)0x20000060 = 0xfc;
*(uint8_t*)0x20000061 = 1;
memset((void*)0x20000062, 0, 13);
*(uint8_t*)0x2000006f = 0;
*(uint32_t*)0x20000070 = 0;
*(uint16_t*)0x20000074 = 0x480;
*(uint16_t*)0x20000076 = 0;
*(uint32_t*)0x20000078 = 0;
*(uint64_t*)0x20000080 = 0;
*(uint32_t*)0x20000088 = 0x1000000;
*(uint32_t*)0x2000008c = 0;
	syscall(__NR_ioctl, r[0], 0x890c, 0x20000040ul);
	res = syscall(__NR_socket, 0xaul, 3ul, 2);
	if (res != -1)
		r[1] = res;
	res = syscall(__NR_socket, 0xaul, 2ul, 0x88);
	if (res != -1)
		r[2] = res;
*(uint16_t*)0x20000080 = 0xa;
*(uint16_t*)0x20000082 = htobe16(0);
*(uint32_t*)0x20000084 = htobe32(0);
*(uint8_t*)0x20000088 = -1;
*(uint8_t*)0x20000089 = 1;
memset((void*)0x2000008a, 0, 13);
*(uint8_t*)0x20000097 = 1;
*(uint32_t*)0x20000098 = 0;
	syscall(__NR_connect, r[2], 0x20000080ul, 0x1cul);
	res = syscall(__NR_socket, 0xaul, 2ul, 0x88);
	if (res != -1)
		r[3] = res;
	res = syscall(__NR_socket, 0x11ul, 3ul, 0x300);
	if (res != -1)
		r[4] = res;
*(uint32_t*)0x20000100 = 5;
	syscall(__NR_setsockopt, r[3], 0x11, 0xd, 0x20000100ul, 4ul);
memcpy((void*)0x200002c0, "sit0\000\000\000\000\000\000\000\000\000\000\000\000", 16);
	res = syscall(__NR_ioctl, r[4], 0x8933, 0x200002c0ul);
	if (res != -1)
r[5] = *(uint32_t*)0x200002d0;
	res = syscall(__NR_gettid);
	if (res != -1)
		r[6] = res;
*(uint32_t*)0x200000c0 = 0;
	syscall(__NR_sched_setparam, r[6], 0x200000c0ul);
*(uint32_t*)0x20000040 = 0;
*(uint32_t*)0x20000044 = r[6];
	syscall(__NR_fcntl, r[2], 0xful, 0x20000040ul);
*(uint64_t*)0x20000480 = htobe64(0);
*(uint64_t*)0x20000488 = htobe64(1);
*(uint32_t*)0x20000490 = 0;
*(uint32_t*)0x20000494 = r[5];
	syscall(__NR_ioctl, r[3], 0x8918, 0x20000480ul);
	res = syscall(__NR_getpid);
	if (res != -1)
		r[7] = res;
*(uint32_t*)0x20000140 = 0;
*(uint32_t*)0x20000144 = r[7];
	syscall(__NR_fcntl, r[2], 0xful, 0x20000140ul);
*(uint8_t*)0x20000000 = 0xfc;
*(uint8_t*)0x20000001 = 2;
memset((void*)0x20000002, 0, 13);
*(uint8_t*)0x2000000f = 0;
*(uint32_t*)0x20000010 = 8;
*(uint32_t*)0x20000014 = r[5];
	syscall(__NR_ioctl, r[2], 0x8916, 0x20000000ul);
*(uint16_t*)0x200000c0 = -1;
*(uint8_t*)0x200000c2 = 0;
*(uint8_t*)0x200000c3 = 9;
*(uint32_t*)0x200000c4 = r[5];
*(uint32_t*)0x200000c8 = 6;
	syscall(__NR_setsockopt, r[1], 0x29, 0xcb, 0x200000c0ul, 0xcul);
	res = syscall(__NR_socket, 0xaul, 2ul, 0x88);
	if (res != -1)
		r[8] = res;
	syscall(__NR_ioctl, r[8], 0x8918, 0ul);
*(uint32_t*)0x20000000 = 0x200;
	syscall(__NR_setsockopt, r[8], 0x11, 0xb, 0x20000000ul, 4ul);
	return 0;
}
