// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <fcntl.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

static long syz_open_dev(volatile long a0, volatile long a1, volatile long a2)
{
	if (a0 == 0xc || a0 == 0xb) {
		char buf[128];
		sprintf(buf, "/dev/%s/%d:%d", a0 == 0xc ? "char" : "block", (uint8_t)a1, (uint8_t)a2);
		return open(buf, O_RDWR, 0);
	} else {
		char buf[1024];
		char* hash;
		strncpy(buf, (char*)a0, sizeof(buf) - 1);
		buf[sizeof(buf) - 1] = 0;
		while ((hash = strchr(buf, '#'))) {
			*hash = '0' + (char)(a1 % 10);
			a1 /= 10;
		}
		return open(buf, a2, 0);
	}
}

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
memcpy((void*)0x20000000, "/dev/sg#\000", 9);
	res = -1;
res = syz_open_dev(0x20000000, 0, 0);
	if (res != -1)
		r[0] = res;
*(uint32_t*)0x20000380 = 0x53;
*(uint32_t*)0x20000384 = 0xfffffffc;
*(uint8_t*)0x20000388 = 0x21;
*(uint8_t*)0x20000389 = 0x7f;
*(uint16_t*)0x2000038a = 0;
*(uint32_t*)0x2000038c = 0xc7;
*(uint64_t*)0x20000390 = 0x20000080;
*(uint64_t*)0x20000398 = 0x20000180;
memcpy((void*)0x20000180, "\xd4\xe1\x72\x42\x93\xd2\x48\xff\xa9\x3d\x3c\x94\x70\x7f\x0d\x79\xf2\x49\x45\xa9\xf5\x17\xa7\xc8\xd5\x8a\x28\x1e\x6f\xfd\x9a\xf0\x78", 33);
*(uint64_t*)0x200003a0 = 0x20000240;
*(uint32_t*)0x200003a8 = 0;
*(uint32_t*)0x200003ac = 0;
*(uint32_t*)0x200003b0 = 0;
*(uint64_t*)0x200003b4 = 0;
*(uint8_t*)0x200003bc = 0;
*(uint8_t*)0x200003bd = 0;
*(uint8_t*)0x200003be = 0;
*(uint8_t*)0x200003bf = 0;
*(uint16_t*)0x200003c0 = 0;
*(uint16_t*)0x200003c2 = 0;
*(uint32_t*)0x200003c4 = 0;
*(uint32_t*)0x200003c8 = 0;
*(uint32_t*)0x200003cc = 0;
	syscall(__NR_ioctl, r[0], 0x2285, 0x20000380ul);
	return 0;
}
