// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <fcntl.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

static long syz_open_dev(volatile long a0, volatile long a1, volatile long a2)
{
	if (a0 == 0xc || a0 == 0xb) {
		char buf[128];
		sprintf(buf, "/dev/%s/%d:%d", a0 == 0xc ? "char" : "block", (uint8_t)a1, (uint8_t)a2);
		return open(buf, O_RDWR, 0);
	} else {
		char buf[1024];
		char* hash;
		strncpy(buf, (char*)a0, sizeof(buf) - 1);
		buf[sizeof(buf) - 1] = 0;
		while ((hash = strchr(buf, '#'))) {
			*hash = '0' + (char)(a1 % 10);
			a1 /= 10;
		}
		return open(buf, a2, 0);
	}
}

uint64_t r[2] = {0xffffffffffffffff, 0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
memcpy((void*)0x20000040, "/dev/loop#\000", 11);
	res = -1;
res = syz_open_dev(0x20000040, 0x3fff800000000, 0);
	if (res != -1)
		r[0] = res;
memcpy((void*)0x200003c0, "/dev/loop#\000", 11);
	res = -1;
res = syz_open_dev(0x200003c0, 0, 0);
	if (res != -1)
		r[1] = res;
*(uint32_t*)0x200001c0 = r[1];
*(uint32_t*)0x200001c4 = 0x1000;
*(uint64_t*)0x200001c8 = 0;
*(uint64_t*)0x200001d0 = 0;
*(uint64_t*)0x200001d8 = 0;
*(uint64_t*)0x200001e0 = 0;
*(uint64_t*)0x200001e8 = 0;
*(uint32_t*)0x200001f0 = 0;
*(uint32_t*)0x200001f4 = 0;
*(uint32_t*)0x200001f8 = 0x1a;
*(uint32_t*)0x200001fc = 0x10;
memcpy((void*)0x20000200, "\x37\x18\xa8\xfd\xad\x14\x9c\x00\x24\xc9\xf3\xb3\xa5\xa7\x2e\x3f\xf5\x2c\x36\xfe\x1e\x3c\x04\x9f\xa5\x95\x93\xa6\x3b\x16\xa6\xe5\x7e\x22\x26\x55\x5d\x36\xd9\xa3\x61\xb2\xcf\x37\x84\x08\x93\x86\x2a\x8d\x5b\x10\xa9\x7d\x8d\x1b\xe4\xd5\xcb\x82\x54\x6b\x87\xca", 64);
memcpy((void*)0x20000240, "\x45\xab\x0a\x87\xdd\x17\x8c\x7f\x25\x6c\x1a\x08\xc1\x74\xe6\x79\xc8\x89\x18\x34\xf6\x49\xea\x03\x67\x13\x1d\x13\x57\x82\x5d\x3f\x59\x98\x8f\xf1\x0d\x88\xe5\x2a\x72\xb8\xe2\x79\x63\xfa\x03\x28\x70\xd7\x0c\x21\x11\x31\x40\x8d\x40\x27\xa6\x2a\x76\x60\x6e\x10", 64);
memcpy((void*)0x20000280, "\x35\x7e\xbe\x5f\xa0\x11\xae\x5d\xcc\x9b\xbf\x9a\xa6\x78\x84\x4a\x29\xbc\x5b\x3b\x51\x17\xae\xde\x18\xc8\xd7\xed\x40\x24\x9a\xba", 32);
*(uint64_t*)0x200002a0 = 0;
*(uint64_t*)0x200002a8 = 0;
memset((void*)0x200002b0, 0, 64);
	syscall(__NR_ioctl, r[0], 0x4c0a, 0x200001c0ul);
	return 0;
}
