// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <fcntl.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

static long syz_open_dev(volatile long a0, volatile long a1, volatile long a2)
{
	if (a0 == 0xc || a0 == 0xb) {
		char buf[128];
		sprintf(buf, "/dev/%s/%d:%d", a0 == 0xc ? "char" : "block", (uint8_t)a1, (uint8_t)a2);
		return open(buf, O_RDWR, 0);
	} else {
		char buf[1024];
		char* hash;
		strncpy(buf, (char*)a0, sizeof(buf) - 1);
		buf[sizeof(buf) - 1] = 0;
		while ((hash = strchr(buf, '#'))) {
			*hash = '0' + (char)(a1 % 10);
			a1 /= 10;
		}
		return open(buf, a2, 0);
	}
}

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
memcpy((void*)0x20000040, "/dev/loop#\000", 11);
	res = -1;
res = syz_open_dev(0x20000040, 0, 0x101002);
	if (res != -1)
		r[0] = res;
*(uint32_t*)0x20000140 = 0;
*(uint16_t*)0x20000148 = 0;
*(uint64_t*)0x20000150 = 0;
*(uint16_t*)0x20000158 = 0;
*(uint32_t*)0x20000160 = 0;
*(uint32_t*)0x20000164 = 0x12;
*(uint32_t*)0x20000168 = 0;
*(uint32_t*)0x2000016c = 0;
memcpy((void*)0x20000170, "\x2f\xa9\xc1\x5e\xbb\x9a\xcd\x95\x5d\x95\x70\x0f\xef\xd2\x6e\xd5\x20\xe3\x8e\x5c\x92\x87\x1c\x97\x0e\x2f\x71\xfe\x69\x48\x76\x64\x27\xf3\xc5\x57\x96\xc8\x86\x0a\x3b\xf7\xaa\x74\x53\x85\x76\x7b\x3c\x0b\xaf\xd4\x4f\xd8\x01\xbe\x11\xd8\xf0\x89\x63\xb5\xf9\x32", 64);
memcpy((void*)0x200001b0, "\x86\xaa\xa2\x25\x64\xbe\x36\xb8\xfe\xbb\x10\x32\x79\x97\xe2\xf3\xe0\xa0\x42\x66\x34\x29\xe3\x05\xf5\x07\xb3\xd2\xd9\xf1\xcd\xca", 32);
*(uint64_t*)0x200001d0 = 0;
*(uint64_t*)0x200001d8 = 0;
*(uint32_t*)0x200001e0 = 0;
	syscall(__NR_ioctl, r[0], 0x4c02, 0x20000140ul);
	return 0;
}
