// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

#define BITMASK(bf_off,bf_len) (((1ull << (bf_len)) - 1) << (bf_off))
#define STORE_BY_BITMASK(type,htobe,addr,val,bf_off,bf_len) *(type*)(addr) = htobe((htobe(*(type*)(addr)) & ~BITMASK((bf_off), (bf_len))) | (((type)(val) << (bf_off)) & BITMASK((bf_off), (bf_len))))

struct csum_inet {
	uint32_t acc;
};

static void csum_inet_init(struct csum_inet* csum)
{
	csum->acc = 0;
}

static void csum_inet_update(struct csum_inet* csum, const uint8_t* data, size_t length)
{
	if (length == 0)
		return;
	size_t i = 0;
	for (; i < length - 1; i += 2)
		csum->acc += *(uint16_t*)&data[i];
	if (length & 1)
		csum->acc += le16toh((uint16_t)data[length - 1]);
	while (csum->acc > 0xffff)
		csum->acc = (csum->acc & 0xffff) + (csum->acc >> 16);
}

static uint16_t csum_inet_digest(struct csum_inet* csum)
{
	return ~csum->acc;
}

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socket, 2ul, 2ul, 0);
	if (res != -1)
		r[0] = res;
memcpy((void*)0x20000180, "sit0\000\000\000\000\000\000\000\000\000\000\000\000", 16);
*(uint64_t*)0x20000190 = 0x20000040;
memcpy((void*)0x20000040, "ip_vti0\000\000\000\000\000\000\000\000\000", 16);
*(uint32_t*)0x20000050 = 0;
*(uint16_t*)0x20000054 = htobe16(0);
*(uint16_t*)0x20000056 = htobe16(0);
*(uint32_t*)0x20000058 = htobe32(0);
*(uint32_t*)0x2000005c = htobe32(0);
STORE_BY_BITMASK(uint8_t, , 0x20000060, 0x25, 0, 4);
STORE_BY_BITMASK(uint8_t, , 0x20000060, 4, 4, 4);
STORE_BY_BITMASK(uint8_t, , 0x20000061, 0, 0, 2);
STORE_BY_BITMASK(uint8_t, , 0x20000061, 0, 2, 6);
*(uint16_t*)0x20000062 = htobe16(0x94);
*(uint16_t*)0x20000064 = htobe16(0);
*(uint16_t*)0x20000066 = htobe16(0);
*(uint8_t*)0x20000068 = 0;
*(uint8_t*)0x20000069 = 0;
*(uint16_t*)0x2000006a = htobe16(0);
*(uint8_t*)0x2000006c = 0xac;
*(uint8_t*)0x2000006d = 0x14;
*(uint8_t*)0x2000006e = 0x14;
*(uint8_t*)0x2000006f = 0xbb;
*(uint8_t*)0x20000070 = 0xac;
*(uint8_t*)0x20000071 = 0x14;
*(uint8_t*)0x20000072 = 0x14;
*(uint8_t*)0x20000073 = 0xaa;
*(uint8_t*)0x20000074 = 7;
*(uint8_t*)0x20000075 = 0x17;
*(uint8_t*)0x20000076 = 0;
*(uint8_t*)0x20000077 = 0xac;
*(uint8_t*)0x20000078 = 0x14;
*(uint8_t*)0x20000079 = 0x14;
*(uint8_t*)0x2000007a = 0;
*(uint8_t*)0x2000007b = 0xac;
*(uint8_t*)0x2000007c = 0x14;
*(uint8_t*)0x2000007d = 0x14;
*(uint8_t*)0x2000007e = 0xaa;
*(uint32_t*)0x2000007f = htobe32(0);
*(uint32_t*)0x20000083 = htobe32(0);
*(uint8_t*)0x20000087 = 0xac;
*(uint8_t*)0x20000088 = 0x14;
*(uint8_t*)0x20000089 = 0x14;
*(uint8_t*)0x2000008a = 0xaa;
*(uint8_t*)0x2000008b = 0x89;
*(uint8_t*)0x2000008c = 0x1b;
*(uint8_t*)0x2000008d = 0;
*(uint32_t*)0x2000008e = htobe32(0);
*(uint32_t*)0x20000092 = htobe32(0xe0000002);
*(uint32_t*)0x20000096 = htobe32(0);
*(uint32_t*)0x2000009a = htobe32(0xe0000001);
*(uint32_t*)0x2000009e = htobe32(-1);
*(uint32_t*)0x200000a2 = htobe32(0);
*(uint8_t*)0x200000a6 = 0x86;
*(uint8_t*)0x200000a7 = 0x4b;
*(uint32_t*)0x200000a8 = htobe32(0);
*(uint8_t*)0x200000ac = 0;
*(uint8_t*)0x200000ad = 5;
memcpy((void*)0x200000ae, "\xf7\xcd\x8d", 3);
*(uint8_t*)0x200000b1 = 0;
*(uint8_t*)0x200000b2 = 0xe;
memcpy((void*)0x200000b3, "\x6c\x7e\x4c\xe5\x09\x49\xad\x96\x13\xc9\x68\xd2", 12);
*(uint8_t*)0x200000bf = 0;
*(uint8_t*)0x200000c0 = 9;
memcpy((void*)0x200000c1, "\xa9\xf8\xec\x14\xb0\x5f\x12", 7);
*(uint8_t*)0x200000c8 = 0;
*(uint8_t*)0x200000c9 = 2;
*(uint8_t*)0x200000ca = 0;
*(uint8_t*)0x200000cb = 2;
*(uint8_t*)0x200000cc = 0;
*(uint8_t*)0x200000cd = 0x11;
memcpy((void*)0x200000ce, "\xdd\xbd\x50\xc2\x21\x6a\xc8\x73\xd4\x5d\xa1\xbd\x4c\x8f\xeb", 15);
*(uint8_t*)0x200000dd = 0;
*(uint8_t*)0x200000de = 7;
memcpy((void*)0x200000df, "\x2f\x5e\x1f\x42\xc6", 5);
*(uint8_t*)0x200000e4 = 0;
*(uint8_t*)0x200000e5 = 0xd;
memcpy((void*)0x200000e6, "\xc3\xb3\x60\xe0\x7c\x50\xcc\xc8\xea\x46\x3e", 11);
	struct csum_inet csum_1;
	csum_inet_init(&csum_1);
csum_inet_update(&csum_1, (const uint8_t*)0x20000060, 148);
*(uint16_t*)0x2000006a = csum_inet_digest(&csum_1);
	syscall(__NR_ioctl, r[0], 0x89f3, 0x20000180ul);
	return 0;
}
