// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[3] = {0x0, 0x0, 0x0};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
memcpy((void*)0x20000000, "keyring\000", 8);
memcpy((void*)0x20000040, "syz", 3);
*(uint8_t*)0x20000043 = 0x21;
*(uint8_t*)0x20000044 = 0;
	res = syscall(__NR_add_key, 0x20000000ul, 0x20000040ul, 0ul, 0ul, -1);
	if (res != -1)
		r[0] = res;
memcpy((void*)0x20000080, "logon\000", 6);
memcpy((void*)0x200000c0, "fscrypt:", 8);
*(uint8_t*)0x200000c8 = 0;
*(uint8_t*)0x200000c9 = 0;
*(uint8_t*)0x200000ca = 0;
*(uint8_t*)0x200000cb = 0;
*(uint8_t*)0x200000cc = 0;
*(uint8_t*)0x200000cd = 0;
*(uint8_t*)0x200000ce = 0;
*(uint8_t*)0x200000cf = 0;
*(uint8_t*)0x200000d0 = 0;
*(uint8_t*)0x200000d1 = 0;
*(uint8_t*)0x200000d2 = 0;
*(uint8_t*)0x200000d3 = 0;
*(uint8_t*)0x200000d4 = 0;
*(uint8_t*)0x200000d5 = 0;
*(uint8_t*)0x200000d6 = 0;
*(uint8_t*)0x200000d7 = 0;
*(uint8_t*)0x200000d8 = 0;
*(uint32_t*)0x20000100 = 0;
memcpy((void*)0x20000104, "\xa7\x9d\x31\xc5\x64\x1d\xe6\xf3\xe9\x8b\x74\xb6\xa1\x9b\x6f\xb5\xbf\xa0\xe1\x97\xb4\xe6\x73\x31\x7c\x3f\xf9\x73\x8f\xc7\xeb\x3d\xdc\xf0\x82\x7b\xed\x11\xec\xf5\x1c\xba\x23\xa5\x4c\x24\x28\xd6\xaa\x7b\x12\xab\x1e\x27\x99\xcc\x8d\x9e\x58\x1b\xf5\x93\xcf\x6c", 64);
*(uint32_t*)0x20000144 = 0;
	res = syscall(__NR_add_key, 0x20000080ul, 0x200000c0ul, 0x20000100ul, 0x48ul, r[0]);
	if (res != -1)
		r[1] = res;
memcpy((void*)0x20000400, "keyring\000", 8);
memcpy((void*)0x20000440, "syz", 3);
*(uint8_t*)0x20000443 = 0x23;
*(uint8_t*)0x20000444 = 0;
	res = syscall(__NR_add_key, 0x20000400ul, 0x20000440ul, 0ul, 0ul, 0xfffffffd);
	if (res != -1)
		r[2] = res;
	syscall(__NR_keyctl, 8ul, r[2], r[1], 0, 0);
	return 0;
}
