// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

#ifndef __NR_fsconfig
#define __NR_fsconfig 431
#endif
#ifndef __NR_fsopen
#define __NR_fsopen 430
#endif

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
memcpy((void*)0x20000080, "cpuset\000", 7);
	res = syscall(__NR_fsopen, 0x20000080ul, 0ul);
	if (res != -1)
		r[0] = res;
memcpy((void*)0x20000140, "!\264kw-\003=\'\352\032$\231\343\207\020\206\304s\350\026\326\r\341\371>\226\032\r\367\217 \342\372\200\362\263\335\3259WZ\343\236\240\034\033\311[\243b\305\234$f\212\270\314\034!\f\366\f\026\005\346EO\303\300j\253Qs{qJ\032\274/nI=\306\353t\234\272_H(1\343\205\207\274r\032Yl\374\25120a;\344\332\230\370\371\\C\2460\003qMA\005\277G\232+\352\240\036\005\326\355\a\260W\003\214\035\030&\202\360\006|R:\266\nM\377\301HR.\027\357\267\315\366\353\024?\366\326\211]&q\316:G\022\262\207\362\222a\256\006:j\335\b\301a\272!)\233\'\340sjih\n\267\351\3752\334\177\313\034\305\242\247@\250\332\325\246\036\225`!#p\353\363\373\216i`\335\344\a9\276\324W\375\217\362\366\247FJ`\'L\316\356\200c\035o\0276/,;Z4QR[t\374\277\fq\300U\234\234\200O\256\362\241#\356\223\362\027\020s^\316\225r\245\346i\\\352rh\366\277c\327\242\260\350\370\326\3211\347_\305A\242\037\217\342\211\222\230\272v\325\306jV\272\252;\216\361i\355\023s\321\232\2474\370m\235.%", 332);
memcpy((void*)0x20000040, "\265\363\n\263bK\212\271M\361T\350^y", 14);
	syscall(__NR_fsconfig, r[0], 1ul, 0x20000140ul, 0x20000040ul, 0ul);
	return 0;
}
