// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

#define BITMASK(bf_off,bf_len) (((1ull << (bf_len)) - 1) << (bf_off))
#define STORE_BY_BITMASK(type,htobe,addr,val,bf_off,bf_len) *(type*)(addr) = htobe((htobe(*(type*)(addr)) & ~BITMASK((bf_off), (bf_len))) | (((type)(val) << (bf_off)) & BITMASK((bf_off), (bf_len))))

struct csum_inet {
	uint32_t acc;
};

static void csum_inet_init(struct csum_inet* csum)
{
	csum->acc = 0;
}

static void csum_inet_update(struct csum_inet* csum, const uint8_t* data, size_t length)
{
	if (length == 0)
		return;
	size_t i = 0;
	for (; i < length - 1; i += 2)
		csum->acc += *(uint16_t*)&data[i];
	if (length & 1)
		csum->acc += le16toh((uint16_t)data[length - 1]);
	while (csum->acc > 0xffff)
		csum->acc = (csum->acc & 0xffff) + (csum->acc >> 16);
}

static uint16_t csum_inet_digest(struct csum_inet* csum)
{
	return ~csum->acc;
}

uint64_t r[2] = {0xffffffffffffffff, 0x0};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socket, 2ul, 2ul, 0x88);
	if (res != -1)
		r[0] = res;
memcpy((void*)0x20000000, "syztnl0\000\000\000\000\000\000\000\000\000", 16);
*(uint64_t*)0x20000010 = 0x200000c0;
memcpy((void*)0x200000c0, "gre0\000\000\000\000\000\000\000\000\000\000\000\000", 16);
*(uint32_t*)0x200000d0 = 0;
*(uint16_t*)0x200000d4 = htobe16(7);
*(uint16_t*)0x200000d6 = htobe16(0x8000);
*(uint32_t*)0x200000d8 = htobe32(9);
*(uint32_t*)0x200000dc = htobe32(8);
STORE_BY_BITMASK(uint8_t, , 0x200000e0, 0x21, 0, 4);
STORE_BY_BITMASK(uint8_t, , 0x200000e0, 4, 4, 4);
STORE_BY_BITMASK(uint8_t, , 0x200000e1, 0, 0, 2);
STORE_BY_BITMASK(uint8_t, , 0x200000e1, 2, 2, 6);
*(uint16_t*)0x200000e2 = htobe16(0x84);
*(uint16_t*)0x200000e4 = htobe16(0x64);
*(uint16_t*)0x200000e6 = htobe16(0);
*(uint8_t*)0x200000e8 = 5;
*(uint8_t*)0x200000e9 = 0;
*(uint16_t*)0x200000ea = htobe16(0);
*(uint32_t*)0x200000ec = htobe32(-1);
*(uint8_t*)0x200000f0 = 0xac;
*(uint8_t*)0x200000f1 = 0x14;
*(uint8_t*)0x200000f2 = 0x14;
*(uint8_t*)0x200000f3 = 0xaa;
*(uint8_t*)0x200000f4 = 0x94;
*(uint8_t*)0x200000f5 = 4;
*(uint16_t*)0x200000f6 = 0;
*(uint8_t*)0x200000f8 = 0x86;
*(uint8_t*)0x200000f9 = 0x24;
*(uint32_t*)0x200000fa = htobe32(2);
*(uint8_t*)0x200000fe = 1;
*(uint8_t*)0x200000ff = 9;
memcpy((void*)0x20000100, "\x72\x09\xf5\x19\x8f\xb5\x2b", 7);
*(uint8_t*)0x20000107 = 1;
*(uint8_t*)0x20000108 = 7;
memcpy((void*)0x20000109, "\x54\x06\x50\xd3\x25", 5);
*(uint8_t*)0x2000010e = 0;
*(uint8_t*)0x2000010f = 7;
memcpy((void*)0x20000110, "\xaf\x8c\xaa\x72\x8d", 5);
*(uint8_t*)0x20000115 = 7;
*(uint8_t*)0x20000116 = 7;
memcpy((void*)0x20000117, "\x7c\x8e\x76\xcd\xe2", 5);
*(uint8_t*)0x2000011c = 0x86;
*(uint8_t*)0x2000011d = 0x38;
*(uint32_t*)0x2000011e = htobe32(0);
*(uint8_t*)0x20000122 = 7;
*(uint8_t*)0x20000123 = 0xc;
memcpy((void*)0x20000124, "\xc1\xcc\x96\xd3\xc8\xc8\x95\x97\xf8\xf6", 10);
*(uint8_t*)0x2000012e = 6;
*(uint8_t*)0x2000012f = 0xa;
memcpy((void*)0x20000130, "\xd7\x5b\x21\x35\xad\x77\xec\x02", 8);
*(uint8_t*)0x20000138 = 6;
*(uint8_t*)0x20000139 = 0xc;
memcpy((void*)0x2000013a, "\xa8\x06\xa4\x87\x66\x98\xf8\x2e\x76\xca", 10);
*(uint8_t*)0x20000144 = 1;
*(uint8_t*)0x20000145 = 0x10;
memcpy((void*)0x20000146, "\x92\x50\xac\xfd\xf5\xc9\xf5\x6f\xfd\x0d\x62\x9d\xe5\x07", 14);
*(uint8_t*)0x20000154 = 0x94;
*(uint8_t*)0x20000155 = 0xe;
memcpy((void*)0x20000156, "\xf4\x66\xf5\x36\xaf\xbd\xe9\x5a\x68\xf6\x75\x5b", 12);
*(uint8_t*)0x20000162 = 0;
	struct csum_inet csum_1;
	csum_inet_init(&csum_1);
csum_inet_update(&csum_1, (const uint8_t*)0x200000e0, 132);
*(uint16_t*)0x200000ea = csum_inet_digest(&csum_1);
	res = syscall(__NR_ioctl, r[0], 0x89f2, 0x20000000ul);
	if (res != -1)
r[1] = *(uint32_t*)0x200000d0;
memcpy((void*)0x20000080, "sit0\000\000\000\000\000\000\000\000\000\000\000\000", 16);
*(uint64_t*)0x20000090 = 0x20000040;
memcpy((void*)0x20000040, "syztnl1\000\000\000\000\000\000\000\000\000", 16);
*(uint32_t*)0x20000050 = r[1];
*(uint16_t*)0x20000054 = htobe16(0);
*(uint16_t*)0x20000056 = htobe16(8);
*(uint32_t*)0x20000058 = htobe32(2);
*(uint32_t*)0x2000005c = htobe32(0);
STORE_BY_BITMASK(uint8_t, , 0x20000060, 5, 0, 4);
STORE_BY_BITMASK(uint8_t, , 0x20000060, 4, 4, 4);
STORE_BY_BITMASK(uint8_t, , 0x20000061, 0, 0, 2);
STORE_BY_BITMASK(uint8_t, , 0x20000061, 0, 2, 6);
*(uint16_t*)0x20000062 = htobe16(0x14);
*(uint16_t*)0x20000064 = htobe16(0x64);
*(uint16_t*)0x20000066 = htobe16(0);
*(uint8_t*)0x20000068 = 4;
*(uint8_t*)0x20000069 = 4;
*(uint16_t*)0x2000006a = htobe16(0);
*(uint32_t*)0x2000006c = htobe32(0xe0000002);
*(uint32_t*)0x20000070 = htobe32(0xe0000001);
	struct csum_inet csum_2;
	csum_inet_init(&csum_2);
csum_inet_update(&csum_2, (const uint8_t*)0x20000060, 20);
*(uint16_t*)0x2000006a = csum_inet_digest(&csum_2);
	syscall(__NR_ioctl, r[0], 0x89f1, 0x20000080ul);
	return 0;
}
