// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[2] = {0xffffffffffffffff, 0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_epoll_create, 9);
	if (res != -1)
		r[0] = res;
	res = syscall(__NR_socket, 0x10ul, 3ul, 9);
	if (res != -1)
		r[1] = res;
*(uint64_t*)0x20000080 = 0;
*(uint32_t*)0x20000088 = 0;
*(uint64_t*)0x20000090 = 0x200000c0;
*(uint64_t*)0x200000c0 = 0x20000180;
*(uint32_t*)0x20000180 = 0x10;
*(uint16_t*)0x20000184 = 0x3fb;
*(uint16_t*)0x20000186 = 0;
*(uint32_t*)0x20000188 = 0;
*(uint32_t*)0x2000018c = 0;
*(uint64_t*)0x200000c8 = 0x10;
*(uint64_t*)0x20000098 = 1;
*(uint64_t*)0x200000a0 = 0;
*(uint64_t*)0x200000a8 = 0;
*(uint32_t*)0x200000b0 = 0;
	syscall(__NR_sendmsg, r[1], 0x20000080ul, 0ul);
*(uint32_t*)0x20000100 = 0;
*(uint64_t*)0x20000104 = 0;
	syscall(__NR_epoll_ctl, r[0], 1ul, r[1], 0x20000100ul);
*(uint32_t*)0x20000040 = 0x13;
*(uint64_t*)0x20000044 = 0;
	syscall(__NR_epoll_ctl, r[0], 3ul, r[1], 0x20000040ul);
	return 0;
}
