// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);

*(uint32_t*)0x20000280 = 0x798e2634;
*(uint32_t*)0x20000284 = 0;
*(uint32_t*)0x20000288 = -1;
*(uint32_t*)0x2000028c = 0;
*(uint32_t*)0x20000290 = -1;
*(uint32_t*)0x20000294 = 0;
*(uint16_t*)0x20000298 = 0;
*(uint64_t*)0x200002a0 = 0;
*(uint64_t*)0x200002a8 = 0;
*(uint64_t*)0x200002b0 = 0;
*(uint64_t*)0x200002b8 = 0;
*(uint64_t*)0x200002c0 = 0;
*(uint64_t*)0x200002c8 = 0;
*(uint64_t*)0x200002d0 = 0;
*(uint16_t*)0x200002d8 = 0;
*(uint16_t*)0x200002da = 0;
*(uint16_t*)0x200002dc = 0;
*(uint32_t*)0x200002e0 = 0;
*(uint32_t*)0x200002e4 = -1;
	syscall(__NR_msgctl, 0, 1ul, 0x20000280ul);
	return 0;
}
