// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[3] = {0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socketpair, 1ul, 2ul, 0, 0x200000c0ul);
	if (res != -1) {
r[0] = *(uint32_t*)0x200000c0;
r[1] = *(uint32_t*)0x200000c4;
	}
	syscall(__NR_getpgrp, 0);
	res = syscall(__NR_socket, 0xaul, 2ul, 0x88);
	if (res != -1)
		r[2] = res;
*(uint64_t*)0x20002980 = 0;
*(uint32_t*)0x20002988 = 0;
*(uint64_t*)0x20002990 = 0;
*(uint64_t*)0x20002998 = 0;
*(uint64_t*)0x200029a0 = 0x20000480;
*(uint64_t*)0x20000480 = 0x18;
*(uint32_t*)0x20000488 = 1;
*(uint32_t*)0x2000048c = 1;
*(uint32_t*)0x20000490 = r[2];
*(uint32_t*)0x20000494 = r[0];
*(uint64_t*)0x200029a8 = 0x18;
*(uint32_t*)0x200029b0 = 0;
*(uint32_t*)0x200029b8 = 0;
	syscall(__NR_sendmmsg, r[0], 0x20002980ul, 1ul, 0ul);
	syscall(__NR_dup3, r[1], r[0], 0ul);
*(uint16_t*)0x20000100 = 0;
*(uint8_t*)0x20000102 = 0;
*(uint32_t*)0x20000104 = 0;
	syscall(__NR_connect, r[1], 0x20000100ul, 0x6eul);
	return 0;
}
