// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);

*(uint64_t*)0x200002c0 = 0x20000200;
*(uint64_t*)0x200002c8 = 0xb5;
*(uint64_t*)0x20000340 = 0x20001440;
*(uint64_t*)0x20000348 = 0xdd;
*(uint64_t*)0x20000350 = 0;
*(uint64_t*)0x20000358 = 0;
	syscall(__NR_process_vm_readv, 0, 0x200002c0ul, 1ul, 0x20000340ul, 2ul, 0ul);
	return 0;
}
