// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <fcntl.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

#ifndef __NR_io_uring_setup
#define __NR_io_uring_setup 425
#endif

static long syz_open_procfs(volatile long a0, volatile long a1)
{
	char buf[128];
	memset(buf, 0, sizeof(buf));
	if (a0 == 0) {
		snprintf(buf, sizeof(buf), "/proc/self/%s", (char*)a1);
	} else if (a0 == -1) {
		snprintf(buf, sizeof(buf), "/proc/thread-self/%s", (char*)a1);
	} else {
		snprintf(buf, sizeof(buf), "/proc/self/task/%d/%s", (int)a0, (char*)a1);
	}
	int fd = open(buf, O_RDWR);
	if (fd == -1)
		fd = open(buf, O_RDONLY);
	return fd;
}

uint64_t r[3] = {0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
memcpy((void*)0x20000280, "/dev/autofs\000", 12);
	res = syscall(__NR_openat, 0xffffffffffffff9cul, 0x20000280ul, 0ul, 0ul);
	if (res != -1)
		r[0] = res;
*(uint32_t*)0x20000004 = 0;
*(uint32_t*)0x20000008 = 0;
*(uint32_t*)0x2000000c = 0;
*(uint32_t*)0x20000010 = 0;
*(uint32_t*)0x20000018 = -1;
memset((void*)0x2000001c, 0, 12);
	res = syscall(__NR_io_uring_setup, 0x1b24, 0x20000000ul);
	if (res != -1)
		r[1] = res;
*(uint32_t*)0x200002c0 = 1;
*(uint32_t*)0x200002c4 = 1;
*(uint32_t*)0x200002c8 = 0x71;
*(uint32_t*)0x200002cc = r[1];
memcpy((void*)0x200002d8, "./file0\000", 8);
	res = syscall(__NR_ioctl, r[0], 0xc0189375, 0x200002c0ul);
	if (res != -1)
r[2] = *(uint32_t*)0x200002cc;
memcpy((void*)0x20000140, "net/snmp\000", 9);
syz_open_procfs(0, 0x20000140);
*(uint32_t*)0x200001c0 = 1;
*(uint32_t*)0x200001c4 = 1;
*(uint32_t*)0x200001c8 = 0x18;
*(uint32_t*)0x200001cc = r[2];
memcpy((void*)0x200001d8, "./file0\000", 8);
	syscall(__NR_ioctl, r[0], 0xc0189375, 0x200001c0ul);
	return 0;
}
