// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <arpa/inet.h>
#include <endian.h>
#include <errno.h>
#include <net/if.h>
#include <netinet/in.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

#include <linux/genetlink.h>
#include <linux/if_addr.h>
#include <linux/if_link.h>
#include <linux/in6.h>
#include <linux/neighbour.h>
#include <linux/net.h>
#include <linux/netlink.h>
#include <linux/rtnetlink.h>
#include <linux/veth.h>

#define BITMASK(bf_off,bf_len) (((1ull << (bf_len)) - 1) << (bf_off))
#define STORE_BY_BITMASK(type,htobe,addr,val,bf_off,bf_len) *(type*)(addr) = htobe((htobe(*(type*)(addr)) & ~BITMASK((bf_off), (bf_len))) | (((type)(val) << (bf_off)) & BITMASK((bf_off), (bf_len))))

struct nlmsg {
	char* pos;
	int nesting;
	struct nlattr* nested[8];
	char buf[4096];
};

static void netlink_init(struct nlmsg* nlmsg, int typ, int flags,
			 const void* data, int size)
{
	memset(nlmsg, 0, sizeof(*nlmsg));
	struct nlmsghdr* hdr = (struct nlmsghdr*)nlmsg->buf;
	hdr->nlmsg_type = typ;
	hdr->nlmsg_flags = NLM_F_REQUEST | NLM_F_ACK | flags;
	memcpy(hdr + 1, data, size);
	nlmsg->pos = (char*)(hdr + 1) + NLMSG_ALIGN(size);
}

static void netlink_attr(struct nlmsg* nlmsg, int typ,
			 const void* data, int size)
{
	struct nlattr* attr = (struct nlattr*)nlmsg->pos;
	attr->nla_len = sizeof(*attr) + size;
	attr->nla_type = typ;
	if (size > 0)
		memcpy(attr + 1, data, size);
	nlmsg->pos += NLMSG_ALIGN(attr->nla_len);
}

static int netlink_send_ext(struct nlmsg* nlmsg, int sock,
			    uint16_t reply_type, int* reply_len, bool dofail)
{
	if (nlmsg->pos > nlmsg->buf + sizeof(nlmsg->buf) || nlmsg->nesting)
	exit(1);
	struct nlmsghdr* hdr = (struct nlmsghdr*)nlmsg->buf;
	hdr->nlmsg_len = nlmsg->pos - nlmsg->buf;
	struct sockaddr_nl addr;
	memset(&addr, 0, sizeof(addr));
	addr.nl_family = AF_NETLINK;
	ssize_t n = sendto(sock, nlmsg->buf, hdr->nlmsg_len, 0, (struct sockaddr*)&addr, sizeof(addr));
	if (n != (ssize_t)hdr->nlmsg_len) {
		if (dofail)
	exit(1);
		return -1;
	}
	n = recv(sock, nlmsg->buf, sizeof(nlmsg->buf), 0);
	if (reply_len)
		*reply_len = 0;
	if (n < 0) {
		if (dofail)
	exit(1);
		return -1;
	}
	if (n < (ssize_t)sizeof(struct nlmsghdr)) {
		errno = EINVAL;
		if (dofail)
	exit(1);
		return -1;
	}
	if (hdr->nlmsg_type == NLMSG_DONE)
		return 0;
	if (reply_len && hdr->nlmsg_type == reply_type) {
		*reply_len = n;
		return 0;
	}
	if (n < (ssize_t)(sizeof(struct nlmsghdr) + sizeof(struct nlmsgerr))) {
		errno = EINVAL;
		if (dofail)
	exit(1);
		return -1;
	}
	if (hdr->nlmsg_type != NLMSG_ERROR) {
		errno = EINVAL;
		if (dofail)
	exit(1);
		return -1;
	}
	errno = -((struct nlmsgerr*)(hdr + 1))->error;
	return -errno;
}

static int netlink_query_family_id(struct nlmsg* nlmsg, int sock, const char* family_name, bool dofail)
{
	struct genlmsghdr genlhdr;
	memset(&genlhdr, 0, sizeof(genlhdr));
	genlhdr.cmd = CTRL_CMD_GETFAMILY;
	netlink_init(nlmsg, GENL_ID_CTRL, 0, &genlhdr, sizeof(genlhdr));
	netlink_attr(nlmsg, CTRL_ATTR_FAMILY_NAME, family_name, strnlen(family_name, GENL_NAMSIZ - 1) + 1);
	int n = 0;
	int err = netlink_send_ext(nlmsg, sock, GENL_ID_CTRL, &n, dofail);
	if (err < 0) {
		return -1;
	}
	uint16_t id = 0;
	struct nlattr* attr = (struct nlattr*)(nlmsg->buf + NLMSG_HDRLEN + NLMSG_ALIGN(sizeof(genlhdr)));
	for (; (char*)attr < nlmsg->buf + n; attr = (struct nlattr*)((char*)attr + NLMSG_ALIGN(attr->nla_len))) {
		if (attr->nla_type == CTRL_ATTR_FAMILY_ID) {
			id = *(uint16_t*)(attr + 1);
			break;
		}
	}
	if (!id) {
		errno = EINVAL;
		return -1;
	}
	recv(sock, nlmsg->buf, sizeof(nlmsg->buf), 0);
	return id;
}

static long syz_genetlink_get_family_id(volatile long name, volatile long sock_arg)
{
	int fd = sock_arg;
	if (fd < 0) {
		fd = socket(AF_NETLINK, SOCK_RAW, NETLINK_GENERIC);
		if (fd == -1) {
			return -1;
		}
	}
	struct nlmsg nlmsg_tmp;
	int ret = netlink_query_family_id(&nlmsg_tmp, fd, (char*)name, false);
	if ((int)sock_arg < 0)
		close(fd);
	if (ret < 0) {
		return -1;
	}
	return ret;
}

uint64_t r[2] = {0xffffffffffffffff, 0x0};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socket, 0x10ul, 3ul, 0x10);
	if (res != -1)
		r[0] = res;
memcpy((void*)0x20000080, "nl80211\000", 8);
	res = -1;
res = syz_genetlink_get_family_id(0x20000080, -1);
	if (res != -1)
		r[1] = res;
*(uint64_t*)0x20000300 = 0;
*(uint32_t*)0x20000308 = 0;
*(uint64_t*)0x20000310 = 0x200002c0;
*(uint64_t*)0x200002c0 = 0x20000340;
*(uint32_t*)0x20000340 = 0x134;
*(uint16_t*)0x20000344 = r[1];
*(uint16_t*)0x20000346 = 1;
*(uint32_t*)0x20000348 = 0;
*(uint32_t*)0x2000034c = 0;
*(uint8_t*)0x20000350 = 0x7a;
*(uint8_t*)0x20000351 = 0;
*(uint16_t*)0x20000352 = 0;
*(uint16_t*)0x20000354 = 0xc;
*(uint16_t*)0x20000356 = 0x99;
*(uint32_t*)0x20000358 = 0;
*(uint32_t*)0x2000035c = 0;
*(uint16_t*)0x20000360 = 0x113;
*(uint16_t*)0x20000362 = 0x2a;
*(uint8_t*)0x20000364 = 0x8c;
*(uint8_t*)0x20000365 = 0x18;
*(uint16_t*)0x20000366 = 0;
memcpy((void*)0x20000368, "\x80\x29\xf2\x5a\x99\x1b", 6);
memcpy((void*)0x2000036e, "\x60\xac\x72\xb7\x28\x92\xee\x14\xb6\x40\xcd\xa1\x34\x58\x1f\x4e", 16);
*(uint8_t*)0x2000037e = 0x76;
*(uint8_t*)0x2000037f = 0x4f;
*(uint8_t*)0x20000380 = 0;
*(uint8_t*)0x20000381 = 0;
*(uint16_t*)0x20000382 = 0;
*(uint16_t*)0x20000384 = 0;
*(uint8_t*)0x20000386 = 0x2a;
*(uint8_t*)0x20000387 = 1;
STORE_BY_BITMASK(uint8_t, , 0x20000388, 0, 0, 1);
STORE_BY_BITMASK(uint8_t, , 0x20000388, 0, 1, 1);
STORE_BY_BITMASK(uint8_t, , 0x20000388, 0, 2, 1);
STORE_BY_BITMASK(uint8_t, , 0x20000388, 0, 3, 5);
*(uint8_t*)0x20000389 = 0x26;
*(uint8_t*)0x2000038a = 0xd1;
*(uint8_t*)0x2000038b = 0;
*(uint8_t*)0x2000038c = 0;
*(uint8_t*)0x2000038d = 0;
memcpy((void*)0x2000038e, "\x09\x8f\x1a\xac\x82\x54\x5f\xb9\xa3\x58\xde\x67\x6f\x37\x24\x1a\x0c\x61\xf2\x4d\x57\x82\x51\x4f\x70\x5c\x15\x53\x0f\x54\xbe\xf5\xa4\x8f\x0a\x23\xea\x9d\x7b\x39\x09\x91\x07\x46\xeb\xf8\x4b\x0f\xf5\x2f\x25\x58\x91\x9e\x1d\x4a\xc5\x7c\xfe\x0e\xb8\xee\x32\xe3\x8d\x37\xc7\x2f\xe0\x75\xc3\xf4\x58\x87\xed\xd2\xe1\x6d\x9a\x17\xfe\x32\xca\xd9\xed\xe6\x07\x14\xec\x6d\x99\x88\x77\x3c\x6f\x5a\xe2\x6d\x1c\x46\x48\x90\x8b\x98\x31\x95\xbb\xba\x67\x70\x6b\x5f\xec\xd0\x09\xad\x52\x5e\xd2\xdc\x85\xed\xef\xe5\xea\x7f\xf6\x01\x40\xf0\xbc\x9e\x79\x48\x2f\x6b\x1b\x7f\x37\x63\x13\x66\x56\xc6\xea\x47\xd1\x74\x10\x92\x6b\x7d\x31\x68\x76\xf2\x4b\x18\xc0\x08\x84\xa3\x6a\x77\xde\x03\x3f\x31\x38\x03\xd9\x5c\xd5\x89\x99\x0f\x83\x3a\x95\xbc\x5d\xf5\x87\x54\xab\xb4\x26\xf7\x02\x43\x71\xfe\x83\x41\xa9\x38\xb7\x33\x74\x89\x84\x55\x0d\x85\x52\x93", 206);
*(uint8_t*)0x2000045c = 0x7e;
*(uint8_t*)0x2000045d = 0xa5;
STORE_BY_BITMASK(uint8_t, , 0x2000045e, 0, 0, 1);
STORE_BY_BITMASK(uint8_t, , 0x2000045e, 0, 1, 7);
*(uint8_t*)0x2000045f = 0;
*(uint8_t*)0x20000460 = 0;
memset((void*)0x20000461, 255, 6);
*(uint32_t*)0x20000467 = 0;
*(uint32_t*)0x2000046b = 0;
*(uint32_t*)0x2000046f = 0;
*(uint64_t*)0x200002c8 = 0x134;
*(uint64_t*)0x20000318 = 1;
*(uint64_t*)0x20000320 = 0;
*(uint64_t*)0x20000328 = 0;
*(uint32_t*)0x20000330 = 0;
	syscall(__NR_sendmsg, r[0], 0x20000300ul, 0ul);
	return 0;
}
