// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socket, 0xaul, 1ul, 0);
	if (res != -1)
		r[0] = res;
memcpy((void*)0x20000040, "\x00\x02", 2);
	syscall(__NR_setsockopt, r[0], 0x29, 0x3b, 0x20000040ul, 0x18ul);
*(uint64_t*)0x20000300 = 0x20000000;
*(uint16_t*)0x20000000 = 0xa;
*(uint16_t*)0x20000002 = htobe16(0);
*(uint32_t*)0x20000004 = htobe32(0);
memset((void*)0x20000008, 0, 16);
*(uint32_t*)0x20000018 = 0;
*(uint32_t*)0x20000308 = 0x1c;
*(uint64_t*)0x20000310 = 0;
*(uint64_t*)0x20000318 = 0;
*(uint64_t*)0x20000320 = 0;
*(uint64_t*)0x20000328 = 0;
*(uint32_t*)0x20000330 = 0;
	syscall(__NR_sendmsg, r[0], 0x20000300ul, 0x20000050ul);
*(uint64_t*)0x20001780 = 0;
*(uint32_t*)0x20001788 = 0;
*(uint64_t*)0x20001790 = 0;
*(uint64_t*)0x20001798 = 0;
*(uint64_t*)0x200017a0 = 0x200016c0;
*(uint64_t*)0x200017a8 = 0x90;
*(uint32_t*)0x200017b0 = 0;
	syscall(__NR_sendmsg, r[0], 0x20001780ul, 0ul);
	return 0;
}
