// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socket, 0xaul, 2ul, 0);
	if (res != -1)
		r[0] = res;
*(uint64_t*)0x20004c80 = 0x20000000;
*(uint16_t*)0x20000000 = 0xa;
*(uint16_t*)0x20000002 = htobe16(0x4e23);
*(uint32_t*)0x20000004 = htobe32(0);
*(uint64_t*)0x20000008 = htobe64(0);
*(uint64_t*)0x20000010 = htobe64(1);
*(uint32_t*)0x20000018 = 9;
*(uint32_t*)0x20004c88 = 0x1c;
*(uint64_t*)0x20004c90 = 0x200000c0;
*(uint64_t*)0x200000c0 = 0x20000040;
memset((void*)0x20000040, 34, 1);
*(uint64_t*)0x200000c8 = 1;
*(uint64_t*)0x20004c98 = 1;
*(uint64_t*)0x20004ca0 = 0x20000100;
*(uint64_t*)0x20000100 = 0x14;
*(uint32_t*)0x20000108 = 0x29;
*(uint32_t*)0x2000010c = 0x34;
*(uint32_t*)0x20000110 = 0;
*(uint64_t*)0x20000118 = 0x18;
*(uint32_t*)0x20000120 = 0x29;
*(uint32_t*)0x20000124 = 0x37;
*(uint8_t*)0x20000128 = 0;
*(uint8_t*)0x20000129 = 0;
memset((void*)0x2000012a, 0, 6);
*(uint64_t*)0x20004ca8 = 0x30;
*(uint32_t*)0x20004cb0 = 0;
*(uint32_t*)0x20004cb8 = 0;
*(uint64_t*)0x20004cc0 = 0x20001180;
*(uint16_t*)0x20001180 = 0xa;
*(uint16_t*)0x20001182 = htobe16(0x4e21);
*(uint32_t*)0x20001184 = htobe32(0);
memcpy((void*)0x20001188, " \001\000\000\000\000\000\000\000\000\000\000\000\000\000\000", 16);
*(uint32_t*)0x20001198 = 0;
*(uint32_t*)0x20004cc8 = 0x1c;
*(uint64_t*)0x20004cd0 = 0;
*(uint64_t*)0x20004cd8 = 0;
*(uint64_t*)0x20004ce0 = 0x200024c0;
*(uint64_t*)0x200024c0 = 0x14;
*(uint32_t*)0x200024c8 = 0x29;
*(uint32_t*)0x200024cc = 0x43;
*(uint32_t*)0x200024d0 = 0;
*(uint64_t*)0x200024d8 = 0x14;
*(uint32_t*)0x200024e0 = 0x29;
*(uint32_t*)0x200024e4 = 0xb;
*(uint32_t*)0x200024e8 = htobe32(0);
*(uint64_t*)0x200024f0 = 0x18;
*(uint32_t*)0x200024f8 = 0x29;
*(uint32_t*)0x200024fc = 0x36;
*(uint8_t*)0x20002500 = 0;
*(uint8_t*)0x20002501 = 0;
memset((void*)0x20002502, 0, 6);
*(uint64_t*)0x20002508 = 0x24;
*(uint32_t*)0x20002510 = 0x29;
*(uint32_t*)0x20002514 = 0x32;
*(uint8_t*)0x20002518 = 0xfe;
*(uint8_t*)0x20002519 = 0x88;
memset((void*)0x2000251a, 0, 12);
*(uint8_t*)0x20002526 = 0;
*(uint8_t*)0x20002527 = 1;
*(uint32_t*)0x20002528 = 0;
*(uint64_t*)0x20004ce8 = 0x70;
*(uint32_t*)0x20004cf0 = 0;
*(uint32_t*)0x20004cf8 = 0;
	syscall(__NR_sendmmsg, r[0], 0x20004c80ul, 2ul, 0ul);
	return 0;
}
