// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <sched.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

#include <linux/sched.h>

#ifndef __NR_clone3
#define __NR_clone3 435
#endif

#define USLEEP_FORKED_CHILD (3 * 50 *1000)

static long handle_clone_ret(long ret)
{
	if (ret != 0) {
		return ret;
	}
	usleep(USLEEP_FORKED_CHILD);
	syscall(__NR_exit, 0);
	while (1) {
	}
}

#define MAX_CLONE_ARGS_BYTES 256
static long syz_clone3(volatile long a0, volatile long a1)
{
	unsigned long copy_size = a1;
	if (copy_size < sizeof(uint64_t) || copy_size > MAX_CLONE_ARGS_BYTES)
		return -1;
	char clone_args[MAX_CLONE_ARGS_BYTES];
	memcpy(&clone_args, (void*)a0, copy_size);
	uint64_t* flags = (uint64_t*)&clone_args;
	*flags &= ~CLONE_VM;
	return handle_clone_ret((long)syscall(__NR_clone3, &clone_args, copy_size));
}

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_pipe, 0x20000000ul);
	if (res != -1)
r[0] = *(uint32_t*)0x20000004;
*(uint64_t*)0x20004080 = 0;
*(uint64_t*)0x20004088 = 0;
*(uint64_t*)0x20004090 = 0;
*(uint64_t*)0x20004098 = 0;
*(uint32_t*)0x200040a0 = 0;
*(uint64_t*)0x200040a8 = 0;
*(uint64_t*)0x200040b0 = 0;
*(uint64_t*)0x200040b8 = 0;
*(uint64_t*)0x200040c0 = 0;
*(uint64_t*)0x200040c8 = 0;
*(uint32_t*)0x200040d0 = -1;
syz_clone3(0x20004080, 0x58);
*(uint64_t*)0x20000040 = 0x20000140;
memcpy((void*)0x20000140, "\x12\x2a\xf3\x43\x2b\xc5\xef\x81\xb7\x78\x37\x5b\xd5\xe4\x00\x00\x00\x00\x00\x00\x00\x00\x4b\xa3\xd4\x0f\x88\x67\x8f\xaf\xe7\x51\x53\xd6\x6f\xcc\x5c\x5e\xbb\xd3\xd2\x57\xfa\x10\x84\x9b\x62\x64\x6e\x90\x01\x7c\x8f\x51\x59\xf9\x6b\xd5\xb5\x74\x1a\x1e\xdb\x4f\x39\x54\xc4\x32\x3a\xc3\xec\x97\x43\xc0\x03\xce\x35\x86\xdc\x7d\x64\x59\x3a\xa6\xf8\xbe\x52\x2a\x9c\x21\x70\x32\x1e\x9a\xd0\x7e\xf9\x46\x01", 99);
*(uint64_t*)0x20000048 = 0xfffffca1;
	syscall(__NR_vmsplice, r[0], 0x20000040ul, 1ul, 8ul);
	return 0;
}
