// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[3] = {0x0, 0x0, 0x0};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
memcpy((void*)0x20000200, "cifs.spnego\000", 12);
memcpy((void*)0x20000040, "syz", 3);
*(uint8_t*)0x20000043 = 0x23;
*(uint8_t*)0x20000044 = 0;
	res = syscall(__NR_request_key, 0x20000200ul, 0x20000040ul, 0ul, 0xfffffffb);
	if (res != -1)
		r[0] = res;
memcpy((void*)0x200003c0, "id_legacy\000", 10);
memcpy((void*)0x20000400, "syz", 3);
*(uint8_t*)0x20000403 = 0x21;
*(uint8_t*)0x20000404 = 0;
memcpy((void*)0x20000440, ",\000", 2);
	syscall(__NR_request_key, 0x200003c0ul, 0x20000400ul, 0x20000440ul, r[0]);
memcpy((void*)0x20000140, "keyring\000", 8);
memcpy((void*)0x20000180, "syz", 3);
*(uint8_t*)0x20000183 = 0x21;
*(uint8_t*)0x20000184 = 0;
memset((void*)0x200001c0, 0, 1);
	res = syscall(__NR_request_key, 0x20000140ul, 0x20000180ul, 0x200001c0ul, r[0]);
	if (res != -1)
		r[1] = res;
memcpy((void*)0x20000080, "big_key\000", 8);
memcpy((void*)0x200000c0, "syz", 3);
*(uint8_t*)0x200000c3 = 0x20;
*(uint8_t*)0x200000c4 = 0;
memcpy((void*)0x20000100, "syz", 3);
	syscall(__NR_request_key, 0x20000080ul, 0x200000c0ul, 0x20000100ul, r[1]);
memcpy((void*)0x20000300, "logon\000", 6);
memcpy((void*)0x20000340, "syz", 3);
*(uint8_t*)0x20000343 = 0x22;
*(uint8_t*)0x20000344 = 0;
memcpy((void*)0x20000380, "!})\000", 4);
	res = syscall(__NR_request_key, 0x20000300ul, 0x20000340ul, 0x20000380ul, r[1]);
	if (res != -1)
		r[2] = res;
memcpy((void*)0x20000000, "fscrypt-provisioning\000", 21);
memcpy((void*)0x20000240, "syz", 3);
*(uint8_t*)0x20000243 = 0x20;
*(uint8_t*)0x20000244 = 0;
*(uint32_t*)0x20000280 = 2;
*(uint32_t*)0x20000284 = 0;
memcpy((void*)0x20000288, "\001\002\003\004\005\006\a\b\t\n\v\f\r\016\017\020\021\022\023\024\025\026\027\030\031\032\033\034\035\036\037 !\"#$%&\'()*+,-./0123456789:;<=>?@", 64);
	syscall(__NR_add_key, 0x20000000ul, 0x20000240ul, 0x20000280ul, 0x48ul, r[2]);
	return 0;
}
