// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[3] = {0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socket, 2ul, 3ul, 2);
	if (res != -1)
		r[0] = res;
	res = syscall(__NR_socket, 2ul, 3ul, 2);
	if (res != -1)
		r[1] = res;
*(uint16_t*)0x20000080 = 1;
*(uint8_t*)0x20000082 = 0xd;
*(uint8_t*)0x20000083 = 0xe8;
*(uint32_t*)0x20000084 = 0;
*(uint8_t*)0x20000088 = 0xac;
*(uint8_t*)0x20000089 = 0x14;
*(uint8_t*)0x2000008a = 0x14;
*(uint8_t*)0x2000008b = 0xaa;
*(uint32_t*)0x2000008c = htobe32(0xe0000002);
	syscall(__NR_setsockopt, r[1], 0, 0xcb, 0x20000080ul, 0x10ul);
	res = syscall(__NR_pipe2, 0x200000c0ul, 0xc00ul);
	if (res != -1)
r[2] = *(uint32_t*)0x200000c4;
*(uint8_t*)0x20000100 = -1;
*(uint8_t*)0x20000101 = 2;
memset((void*)0x20000102, 0, 13);
*(uint8_t*)0x2000010f = 1;
*(uint8_t*)0x20000110 = 0xfc;
*(uint8_t*)0x20000111 = 1;
memset((void*)0x20000112, 0, 13);
*(uint8_t*)0x2000011f = 1;
	syscall(__NR_ioctl, r[2], 0x89e1, 0x20000100ul);
*(uint8_t*)0x20000040 = 0xac;
*(uint8_t*)0x20000041 = 0x1e;
*(uint8_t*)0x20000042 = 0;
*(uint8_t*)0x20000043 = 1;
*(uint32_t*)0x20000044 = htobe32(0xe0000001);
*(uint16_t*)0x20000048 = 0;
memcpy((void*)0x2000004a, "\x90\x4b\x22\x1d\xd1\x81\xfa\x4e\x67\xf0\x4c\x60\x86\x05\xa5\x60\x78\xeb\x72\xe8\x2a\x42\x42\xb5\xd3\x15\xe6\x33\x07\xdd\xa3\xe7", 32);
*(uint32_t*)0x2000006c = 0;
*(uint32_t*)0x20000070 = 0;
*(uint32_t*)0x20000074 = 0;
*(uint32_t*)0x20000078 = 0;
	syscall(__NR_setsockopt, r[0], 0, 0xd2, 0x20000040ul, 0x3cul);
	syscall(__NR_socket, 2ul, 3ul, 2);
	return 0;
}
