// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[2] = {0xffffffffffffffff, 0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_pipe, 0x20000000ul);
	if (res != -1) {
r[0] = *(uint32_t*)0x20000000;
r[1] = *(uint32_t*)0x20000004;
	}
*(uint64_t*)0x20000480 = 0x20000200;
memset((void*)0x20000200, 57, 1);
*(uint64_t*)0x20000488 = 1;
	syscall(__NR_vmsplice, -1, 0x20000480ul, 1ul, 0ul);
*(uint32_t*)0x20000180 = r[0];
*(uint16_t*)0x20000184 = 0;
*(uint16_t*)0x20000186 = 0;
	syscall(__NR_poll, 0x20000180ul, 1ul, 0x10000);
*(uint64_t*)0x20000140 = 0x20000040;
memset((void*)0x20000040, 80, 1);
*(uint64_t*)0x20000148 = 1;
	syscall(__NR_vmsplice, r[1], 0x20000140ul, 1ul, 0ul);
	return 0;
}
