// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[3] = {0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_eventfd2, 0, 0ul);
	if (res != -1)
		r[0] = res;
memcpy((void*)0x20000040, "./cgroup/cgroup.procs\000", 22);
	res = syscall(__NR_openat, 0xffffff9c, 0x20000040ul, 0ul, 0ul);
	if (res != -1)
		r[1] = res;
memcpy((void*)0x20000000, "/proc/sys/net/ipv4/tcp_congestion_control\000", 42);
	res = syscall(__NR_openat, 0xffffffffffffff9cul, 0x20000000ul, 1ul, 0ul);
	if (res != -1)
		r[2] = res;
*(uint32_t*)0x20000100 = r[0];
*(uint16_t*)0x20000104 = 0;
*(uint16_t*)0x20000106 = 0;
*(uint32_t*)0x20000108 = r[1];
*(uint16_t*)0x2000010c = 0;
*(uint16_t*)0x2000010e = 0;
*(uint32_t*)0x20000110 = r[2];
*(uint16_t*)0x20000114 = 0;
*(uint16_t*)0x20000116 = 0;
*(uint32_t*)0x20000118 = r[0];
*(uint16_t*)0x2000011c = 0;
*(uint16_t*)0x2000011e = 0;
	syscall(__NR_ppoll, 0x20000100ul, 4ul, 0ul, 0ul, 0ul);
	return 0;
}
