// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);

memcpy((void*)0x20000600, "./file0\000", 8);
	syscall(__NR_mknod, 0x20000600ul, 0x6000ul, 0x700);
memcpy((void*)0x200001c0, "./file0\000", 8);
*(uint64_t*)0x20000a40 = 0x20000a00;
memcpy((void*)0x20000a00, "-&/[$/.\006\000", 9);
*(uint64_t*)0x20000b40 = 0x20000a80;
memcpy((void*)0x20000a80, "ext4\000", 5);
*(uint64_t*)0x20000b48 = 0x20000ac0;
memcpy((void*)0x20000ac0, "@&!\000", 4);
	syscall(__NR_execve, 0x200001c0ul, 0x20000a40ul, 0x20000b40ul);
	return 0;
}
