// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socket, 2ul, 3ul, 0xc);
	if (res != -1)
		r[0] = res;
*(uint16_t*)0x20000000 = 0;
*(uint8_t*)0x20000002 = 0;
*(uint32_t*)0x20000004 = 0;
	syscall(__NR_sendto, r[0], 0ul, 0ul, 0ul, 0x20000000ul, 0x6eul);
	syscall(__NR_clock_gettime, 0ul, 0x200031c0ul);
*(uint64_t*)0x20003080 = 0;
*(uint32_t*)0x20003088 = 0;
*(uint64_t*)0x20003090 = 0x20001200;
*(uint64_t*)0x20001200 = 0x20000100;
*(uint64_t*)0x20001208 = 0x74;
*(uint64_t*)0x20003098 = 1;
*(uint64_t*)0x200030a0 = 0;
*(uint64_t*)0x200030a8 = 0;
*(uint32_t*)0x200030b0 = 0;
*(uint32_t*)0x200030b8 = 0;
*(uint64_t*)0x200030c0 = 0;
*(uint32_t*)0x200030c8 = 0;
*(uint64_t*)0x200030d0 = 0;
*(uint64_t*)0x200030d8 = 0;
*(uint64_t*)0x200030e0 = 0;
*(uint64_t*)0x200030e8 = 0;
*(uint32_t*)0x200030f0 = 0;
*(uint32_t*)0x200030f8 = 0;
	syscall(__NR_recvmmsg, r[0], 0x20003080ul, 2ul, 0x22ul, 0ul);
	return 0;
}
