// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[2] = {0xffffffffffffffff, 0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socket, 0x11ul, 2ul, 0x300);
	if (res != -1)
		r[0] = res;
*(uint16_t*)0x20000000 = 0;
*(uint16_t*)0x20000002 = 0xa001;
	syscall(__NR_setsockopt, r[0], 0x107, 0x12, 0x20000000ul, 4ul);
	res = syscall(__NR_socket, 2ul, 2ul, 0);
	if (res != -1)
		r[1] = res;
*(uint64_t*)0x20001300 = 0x20000080;
*(uint16_t*)0x20000080 = 2;
*(uint16_t*)0x20000082 = htobe16(0x4e29);
*(uint32_t*)0x20000084 = htobe32(0x7f000001);
*(uint32_t*)0x20001308 = 0x10;
*(uint64_t*)0x20001310 = 0;
*(uint64_t*)0x20001318 = 0;
*(uint64_t*)0x20001320 = 0;
*(uint64_t*)0x20001328 = 0;
*(uint32_t*)0x20001330 = 0;
	syscall(__NR_sendmsg, r[1], 0x20001300ul, 0ul);
	return 0;
}
