// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[2] = {0xffffffffffffffff, 0x0};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socket, 0x10ul, 3ul, 0x10);
	if (res != -1)
		r[0] = res;
*(uint64_t*)0x20000400 = 0x20000040;
*(uint16_t*)0x20000040 = 0x10;
*(uint16_t*)0x20000042 = 0;
*(uint32_t*)0x20000044 = 0;
*(uint32_t*)0x20000048 = 4;
*(uint32_t*)0x20000408 = 0xc;
*(uint64_t*)0x20000410 = 0x200003c0;
*(uint64_t*)0x200003c0 = 0;
*(uint64_t*)0x200003c8 = 0;
*(uint64_t*)0x20000418 = 1;
*(uint64_t*)0x20000420 = 0;
*(uint64_t*)0x20000428 = 0;
*(uint32_t*)0x20000430 = 0;
	syscall(__NR_sendmsg, r[0], 0x20000400ul, 0ul);
	syscall(__NR_alarm, 5ul);
memcpy((void*)0x200001c0, "(:+\000", 4);
	syscall(__NR_mq_unlink, 0x200001c0ul);
memcpy((void*)0x20000080, "\x32\xf4\xa5\x88\x2b\x6c\xe0\xd1\xc6\x1b\x8c\x5a\xee\xbb\xa7\x74", 16);
*(uint64_t*)0x20000090 = 0;
*(uint64_t*)0x20000098 = 0;
*(uint64_t*)0x200000a0 = 7;
*(uint32_t*)0x200000a8 = 0x55;
*(uint64_t*)0x200000b0 = 0;
*(uint32_t*)0x200000b8 = -1;
*(uint64_t*)0x200000c0 = -1;
*(uint64_t*)0x200000c8 = 3;
*(uint64_t*)0x200000d0 = 2;
*(uint64_t*)0x200000d8 = 3;
*(uint64_t*)0x200000e0 = 9;
*(uint64_t*)0x200000e8 = 0;
*(uint64_t*)0x200000f0 = 5;
*(uint64_t*)0x200000f8 = 8;
*(uint64_t*)0x20000100 = 0x100;
*(uint64_t*)0x20000108 = 0xed;
*(uint64_t*)0x20000110 = 0x7fffffff;
*(uint64_t*)0x20000118 = 0xc905;
*(uint64_t*)0x20000120 = 3;
*(uint64_t*)0x20000128 = 0x1ff;
*(uint64_t*)0x20000130 = 0x10000;
*(uint64_t*)0x20000138 = 4;
*(uint64_t*)0x20000140 = 2;
	res = syscall(__NR_ioctl, r[0], 0xc0c89425, 0x20000080ul);
	if (res != -1)
r[1] = *(uint64_t*)0x20000098;
*(uint64_t*)0x20000000 = r[1];
	syscall(__NR_ioctl, r[0], 0x40089416, 0x20000000ul);
	return 0;
}
