// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <fcntl.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

static long syz_open_procfs(volatile long a0, volatile long a1)
{
	char buf[128];
	memset(buf, 0, sizeof(buf));
	if (a0 == 0) {
		snprintf(buf, sizeof(buf), "/proc/self/%s", (char*)a1);
	} else if (a0 == -1) {
		snprintf(buf, sizeof(buf), "/proc/thread-self/%s", (char*)a1);
	} else {
		snprintf(buf, sizeof(buf), "/proc/self/task/%d/%s", (int)a0, (char*)a1);
	}
	int fd = open(buf, O_RDWR);
	if (fd == -1)
		fd = open(buf, O_RDONLY);
	return fd;
}

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);

memcpy((void*)0x20000000, ".%\000", 3);
*(uint64_t*)0x20000040 = 0;
*(uint64_t*)0x20000048 = 1;
*(uint64_t*)0x20000050 = 0;
*(uint64_t*)0x20000058 = 8;
memset((void*)0x20000060, 0, 32);
	syscall(__NR_mq_open, 0x20000000ul, 2ul, 0x20ul, 0x20000040ul);
memcpy((void*)0x20001140, "./cgroup/syz0\000", 14);
	syscall(__NR_openat, 0xffffffffffffff9cul, 0x20001140ul, 0x200002ul, 0ul);
	syscall(__NR_socket, 0x10ul, 3ul, 0x10);
*(uint32_t*)0x20001240 = 0;
	syscall(__NR_accept4, -1, 0ul, 0x20001240ul, 0x80000ul);
	syscall(__NR_socket, 2ul, 2ul, 0x88);
	syscall(__NR_getresuid, 0x20001280ul, 0ul, 0x20001300ul);
memcpy((void*)0x20005e00, "./cgroup/syz0\000", 14);
	syscall(__NR_openat, 0xffffffffffffff9cul, 0x20005e00ul, 0x200002ul, 0ul);
memcpy((void*)0x20005e80, "/dev/sr0\000", 9);
	syscall(__NR_openat, 0xffffffffffffff9cul, 0x20005e80ul, 0ul, 0ul);
memcpy((void*)0x20005ec0, "./binderfs2/custom0\000", 20);
	syscall(__NR_openat, 0xffffffffffffff9cul, 0x20005ec0ul, 0x800ul, 0ul);
memcpy((void*)0x200063c0, "ns/time_for_children\000", 21);
syz_open_procfs(-1, 0x200063c0);
	return 0;
}
