// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[3] = {0xffffffffffffffff, 0xffffffffffffffff, 0x0};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socket, 2ul, 0xaul, 0);
	if (res != -1)
		r[0] = res;
	res = syscall(__NR_socket, 0x11ul, 3ul, 0x300);
	if (res != -1)
		r[1] = res;
memcpy((void*)0x200001c0, "team0\000\000\000\000\000\000\000\000\000\000\000", 16);
	res = syscall(__NR_ioctl, r[0], 0x8933, 0x200001c0ul);
	if (res != -1)
r[2] = *(uint32_t*)0x200001d0;
*(uint16_t*)0x20000200 = 0x11;
*(uint16_t*)0x20000202 = htobe16(0);
*(uint32_t*)0x20000204 = r[2];
*(uint16_t*)0x20000208 = 1;
*(uint8_t*)0x2000020a = 0;
*(uint8_t*)0x2000020b = 6;
*(uint8_t*)0x2000020c = 1;
*(uint8_t*)0x2000020d = 0x80;
*(uint8_t*)0x2000020e = 0xc2;
*(uint8_t*)0x2000020f = 0;
*(uint8_t*)0x20000210 = 0;
*(uint8_t*)0x20000211 = 0;
memset((void*)0x20000212, 0, 2);
	syscall(__NR_bind, r[1], 0x20000200ul, 0x14ul);
	return 0;
}
