// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socket, 0xaul, 3ul, 0x3a);
	if (res != -1)
		r[0] = res;
*(uint64_t*)0x20000240 = 0;
*(uint16_t*)0x20000248 = 0x1f;
*(uint16_t*)0x2000024a = 0;
memset((void*)0x2000024c, 0, 6);
*(uint16_t*)0x20000252 = 0;
*(uint8_t*)0x20000254 = 0;
*(uint16_t*)0x20000258 = 0x1a;
*(uint16_t*)0x2000025a = 0;
*(uint8_t*)0x2000025c = 0;
*(uint8_t*)0x2000025d = 0;
*(uint8_t*)0x2000025e = 0;
*(uint8_t*)0x2000025f = 0;
memset((void*)0x20000260, 170, 5);
*(uint8_t*)0x20000265 = 0xaa;
*(uint16_t*)0x20000268 = 0x23;
*(uint8_t*)0x2000026a = 0;
*(uint8_t*)0x2000026b = 0;
*(uint8_t*)0x2000026c = 0;
memset((void*)0x2000026d, 0, 11);
*(uint16_t*)0x20000278 = 0;
*(uint16_t*)0x2000027a = 0;
*(uint64_t*)0x20000280 = 0;
*(uint64_t*)0x20000288 = 0;
*(uint16_t*)0x20000290 = 0;
*(uint64_t*)0x20000298 = 0;
*(uint64_t*)0x200002a0 = 0;
*(uint64_t*)0x200002a8 = 0;
*(uint16_t*)0x200002b0 = 0;
	syscall(__NR_ioctl, r[0], 0x890b, 0x20000240ul);
	return 0;
}
