// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <arpa/inet.h>
#include <endian.h>
#include <errno.h>
#include <net/if.h>
#include <netinet/in.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <sys/socket.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

#include <linux/genetlink.h>
#include <linux/if_addr.h>
#include <linux/if_link.h>
#include <linux/in6.h>
#include <linux/neighbour.h>
#include <linux/net.h>
#include <linux/netlink.h>
#include <linux/rtnetlink.h>
#include <linux/veth.h>

#ifndef __NR_io_uring_register
#define __NR_io_uring_register 427
#endif
#ifndef __NR_io_uring_setup
#define __NR_io_uring_setup 425
#endif

struct nlmsg {
	char* pos;
	int nesting;
	struct nlattr* nested[8];
	char buf[4096];
};

static void netlink_init(struct nlmsg* nlmsg, int typ, int flags,
			 const void* data, int size)
{
	memset(nlmsg, 0, sizeof(*nlmsg));
	struct nlmsghdr* hdr = (struct nlmsghdr*)nlmsg->buf;
	hdr->nlmsg_type = typ;
	hdr->nlmsg_flags = NLM_F_REQUEST | NLM_F_ACK | flags;
	memcpy(hdr + 1, data, size);
	nlmsg->pos = (char*)(hdr + 1) + NLMSG_ALIGN(size);
}

static void netlink_attr(struct nlmsg* nlmsg, int typ,
			 const void* data, int size)
{
	struct nlattr* attr = (struct nlattr*)nlmsg->pos;
	attr->nla_len = sizeof(*attr) + size;
	attr->nla_type = typ;
	if (size > 0)
		memcpy(attr + 1, data, size);
	nlmsg->pos += NLMSG_ALIGN(attr->nla_len);
}

static int netlink_send_ext(struct nlmsg* nlmsg, int sock,
			    uint16_t reply_type, int* reply_len, bool dofail)
{
	if (nlmsg->pos > nlmsg->buf + sizeof(nlmsg->buf) || nlmsg->nesting)
	exit(1);
	struct nlmsghdr* hdr = (struct nlmsghdr*)nlmsg->buf;
	hdr->nlmsg_len = nlmsg->pos - nlmsg->buf;
	struct sockaddr_nl addr;
	memset(&addr, 0, sizeof(addr));
	addr.nl_family = AF_NETLINK;
	ssize_t n = sendto(sock, nlmsg->buf, hdr->nlmsg_len, 0, (struct sockaddr*)&addr, sizeof(addr));
	if (n != (ssize_t)hdr->nlmsg_len) {
		if (dofail)
	exit(1);
		return -1;
	}
	n = recv(sock, nlmsg->buf, sizeof(nlmsg->buf), 0);
	if (reply_len)
		*reply_len = 0;
	if (n < 0) {
		if (dofail)
	exit(1);
		return -1;
	}
	if (n < (ssize_t)sizeof(struct nlmsghdr)) {
		errno = EINVAL;
		if (dofail)
	exit(1);
		return -1;
	}
	if (hdr->nlmsg_type == NLMSG_DONE)
		return 0;
	if (reply_len && hdr->nlmsg_type == reply_type) {
		*reply_len = n;
		return 0;
	}
	if (n < (ssize_t)(sizeof(struct nlmsghdr) + sizeof(struct nlmsgerr))) {
		errno = EINVAL;
		if (dofail)
	exit(1);
		return -1;
	}
	if (hdr->nlmsg_type != NLMSG_ERROR) {
		errno = EINVAL;
		if (dofail)
	exit(1);
		return -1;
	}
	errno = -((struct nlmsgerr*)(hdr + 1))->error;
	return -errno;
}

static int netlink_query_family_id(struct nlmsg* nlmsg, int sock, const char* family_name, bool dofail)
{
	struct genlmsghdr genlhdr;
	memset(&genlhdr, 0, sizeof(genlhdr));
	genlhdr.cmd = CTRL_CMD_GETFAMILY;
	netlink_init(nlmsg, GENL_ID_CTRL, 0, &genlhdr, sizeof(genlhdr));
	netlink_attr(nlmsg, CTRL_ATTR_FAMILY_NAME, family_name, strnlen(family_name, GENL_NAMSIZ - 1) + 1);
	int n = 0;
	int err = netlink_send_ext(nlmsg, sock, GENL_ID_CTRL, &n, dofail);
	if (err < 0) {
		return -1;
	}
	uint16_t id = 0;
	struct nlattr* attr = (struct nlattr*)(nlmsg->buf + NLMSG_HDRLEN + NLMSG_ALIGN(sizeof(genlhdr)));
	for (; (char*)attr < nlmsg->buf + n; attr = (struct nlattr*)((char*)attr + NLMSG_ALIGN(attr->nla_len))) {
		if (attr->nla_type == CTRL_ATTR_FAMILY_ID) {
			id = *(uint16_t*)(attr + 1);
			break;
		}
	}
	if (!id) {
		errno = EINVAL;
		return -1;
	}
	recv(sock, nlmsg->buf, sizeof(nlmsg->buf), 0);
	return id;
}

#define SIZEOF_IO_URING_SQE 64
#define SIZEOF_IO_URING_CQE 16
#define SQ_HEAD_OFFSET 0
#define SQ_TAIL_OFFSET 64
#define SQ_RING_MASK_OFFSET 256
#define SQ_RING_ENTRIES_OFFSET 264
#define SQ_FLAGS_OFFSET 276
#define SQ_DROPPED_OFFSET 272
#define CQ_HEAD_OFFSET 128
#define CQ_TAIL_OFFSET 192
#define CQ_RING_MASK_OFFSET 260
#define CQ_RING_ENTRIES_OFFSET 268
#define CQ_RING_OVERFLOW_OFFSET 284
#define CQ_FLAGS_OFFSET 280
#define CQ_CQES_OFFSET 320

struct io_sqring_offsets {
	uint32_t head;
	uint32_t tail;
	uint32_t ring_mask;
	uint32_t ring_entries;
	uint32_t flags;
	uint32_t dropped;
	uint32_t array;
	uint32_t resv1;
	uint64_t resv2;
};

struct io_cqring_offsets {
	uint32_t head;
	uint32_t tail;
	uint32_t ring_mask;
	uint32_t ring_entries;
	uint32_t overflow;
	uint32_t cqes;
	uint64_t resv[2];
};

struct io_uring_params {
	uint32_t sq_entries;
	uint32_t cq_entries;
	uint32_t flags;
	uint32_t sq_thread_cpu;
	uint32_t sq_thread_idle;
	uint32_t features;
	uint32_t resv[4];
	struct io_sqring_offsets sq_off;
	struct io_cqring_offsets cq_off;
};

#define IORING_OFF_SQ_RING 0
#define IORING_OFF_SQES 0x10000000ULL

static long syz_io_uring_setup(volatile long a0, volatile long a1, volatile long a2, volatile long a3, volatile long a4, volatile long a5)
{
	uint32_t entries = (uint32_t)a0;
	struct io_uring_params* setup_params = (struct io_uring_params*)a1;
	void* vma1 = (void*)a2;
	void* vma2 = (void*)a3;
	void** ring_ptr_out = (void**)a4;
	void** sqes_ptr_out = (void**)a5;
	uint32_t fd_io_uring = syscall(__NR_io_uring_setup, entries, setup_params);
	uint32_t sq_ring_sz = setup_params->sq_off.array + setup_params->sq_entries * sizeof(uint32_t);
	uint32_t cq_ring_sz = setup_params->cq_off.cqes + setup_params->cq_entries * SIZEOF_IO_URING_CQE;
	uint32_t ring_sz = sq_ring_sz > cq_ring_sz ? sq_ring_sz : cq_ring_sz;
	*ring_ptr_out = mmap(vma1, ring_sz, PROT_READ | PROT_WRITE, MAP_SHARED | MAP_POPULATE | MAP_FIXED, fd_io_uring, IORING_OFF_SQ_RING);
	uint32_t sqes_sz = setup_params->sq_entries * SIZEOF_IO_URING_SQE;
	*sqes_ptr_out = mmap(vma2, sqes_sz, PROT_READ | PROT_WRITE, MAP_SHARED | MAP_POPULATE | MAP_FIXED, fd_io_uring, IORING_OFF_SQES);
	return fd_io_uring;
}

static long syz_genetlink_get_family_id(volatile long name, volatile long sock_arg)
{
	int fd = sock_arg;
	if (fd < 0) {
		fd = socket(AF_NETLINK, SOCK_RAW, NETLINK_GENERIC);
		if (fd == -1) {
			return -1;
		}
	}
	struct nlmsg nlmsg_tmp;
	int ret = netlink_query_family_id(&nlmsg_tmp, fd, (char*)name, false);
	if ((int)sock_arg < 0)
		close(fd);
	if (ret < 0) {
		return -1;
	}
	return ret;
}

uint64_t r[5] = {0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
*(uint32_t*)0x20000004 = 0xe227;
*(uint32_t*)0x20000008 = 8;
*(uint32_t*)0x2000000c = 1;
*(uint32_t*)0x20000010 = 0xce;
*(uint32_t*)0x20000018 = -1;
memset((void*)0x2000001c, 0, 12);
	res = -1;
res = syz_io_uring_setup(0x7c96, 0x20000000, 0x20ff8000, 0x20fee000, 0x20000080, 0x200000c0);
	if (res != -1)
		r[0] = res;
	syscall(__NR_io_uring_register, r[0], 1ul, 0ul, 0ul);
*(uint32_t*)0x20000104 = 0x7bb1;
*(uint32_t*)0x20000108 = 0x20;
*(uint32_t*)0x2000010c = 3;
*(uint32_t*)0x20000110 = 0x19f;
*(uint32_t*)0x20000118 = r[0];
memset((void*)0x2000011c, 0, 12);
	res = syscall(__NR_io_uring_setup, 0x5e34, 0x20000100ul);
	if (res != -1)
		r[1] = res;
*(uint32_t*)0x20000184 = 0x777;
*(uint32_t*)0x20000188 = 0;
*(uint32_t*)0x2000018c = 3;
*(uint32_t*)0x20000190 = 0xda;
*(uint32_t*)0x20000198 = r[1];
memset((void*)0x2000019c, 0, 12);
	syscall(__NR_io_uring_setup, 0x3a99, 0x20000180ul);
memcpy((void*)0x20000200, ".log\000", 5);
	res = syscall(__NR_openat, -1, 0x20000200ul, 0x80000ul, 0x10aul);
	if (res != -1)
		r[2] = res;
*(uint32_t*)0x20000240 = 7;
*(uint8_t*)0x20000244 = 0x33;
*(uint16_t*)0x20000245 = 1;
	syscall(__NR_write, r[2], 0x20000240ul, 7ul);
*(uint32_t*)0x20000284 = 0xbf6a;
*(uint32_t*)0x20000288 = 4;
*(uint32_t*)0x2000028c = 3;
*(uint32_t*)0x20000290 = 0x5d;
*(uint32_t*)0x20000298 = r[2];
memset((void*)0x2000029c, 0, 12);
syz_io_uring_setup(0xaba, 0x20000280, 0x20ffe000, 0x20ffa000, 0x20000300, 0x20000340);
	syscall(__NR_ioctl, r[2], 0x40106614, 0x20000400ul);
memcpy((void*)0x20000440, "/dev/sr0\000", 9);
	res = syscall(__NR_openat, 0xffffffffffffff9cul, 0x20000440ul, 0x141000ul, 0ul);
	if (res != -1)
		r[3] = res;
	syscall(__NR_ioctl, r[3], 0x5394, 0x20000480ul);
memcpy((void*)0x200004c0, "NLBL_CALIPSO\000", 13);
syz_genetlink_get_family_id(0x200004c0, -1);
	res = syscall(__NR_socketpair, 0x2cul, 0x800ul, 3, 0x20000500ul);
	if (res != -1)
r[4] = *(uint32_t*)0x20000504;
*(uint32_t*)0x20000540 = 3;
	syscall(__NR_setsockopt, r[4], 0x11, 0x64, 0x20000540ul, 4ul);
	syscall(__NR_ioctl, r[3], 0x530f, 0ul);
*(uint64_t*)0x20000640 = 0x20000580;
*(uint16_t*)0x20000580 = 0x10;
*(uint16_t*)0x20000582 = 0;
*(uint32_t*)0x20000584 = 0;
*(uint32_t*)0x20000588 = 0x20000000;
*(uint32_t*)0x20000648 = 0xc;
*(uint64_t*)0x20000650 = 0x20000600;
*(uint64_t*)0x20000600 = 0x200005c0;
*(uint32_t*)0x200005c0 = 0x10;
*(uint16_t*)0x200005c4 = 0x3f6;
*(uint16_t*)0x200005c6 = 0xb00;
*(uint32_t*)0x200005c8 = 0x70bd25;
*(uint32_t*)0x200005cc = 0x25dfdbfd;
*(uint64_t*)0x20000608 = 0x10;
*(uint64_t*)0x20000658 = 1;
*(uint64_t*)0x20000660 = 0;
*(uint64_t*)0x20000668 = 0;
*(uint32_t*)0x20000670 = 0x44001;
	syscall(__NR_sendmsg, r[4], 0x20000640ul, 0x8000ul);
*(uint32_t*)0x20000684 = 0xa0c9;
*(uint32_t*)0x20000688 = 2;
*(uint32_t*)0x2000068c = 1;
*(uint32_t*)0x20000690 = 0x314;
*(uint32_t*)0x20000698 = -1;
memset((void*)0x2000069c, 0, 12);
syz_io_uring_setup(0x23b3, 0x20000680, 0x20ff3000, 0x20ff2000, 0x20000700, 0x20000740);
	return 0;
}
