// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socket, 0xaul, 1ul, 0);
	if (res != -1)
		r[0] = res;
*(uint32_t*)0x20001380 = 1;
	syscall(__NR_setsockopt, r[0], 6, 0x13, 0x20001380ul, 4ul);
*(uint16_t*)0x20000000 = 0xa;
*(uint16_t*)0x20000002 = htobe16(0);
*(uint32_t*)0x20000004 = htobe32(0);
memset((void*)0x20000008, 0, 10);
memset((void*)0x20000012, 255, 2);
*(uint32_t*)0x20000014 = htobe32(0x7f000001);
*(uint32_t*)0x20000018 = 0;
	syscall(__NR_connect, r[0], 0x20000000ul, 0x1cul);
*(uint16_t*)0x20000580 = 0xa;
*(uint16_t*)0x20000582 = htobe16(0);
*(uint32_t*)0x20000584 = htobe32(0);
*(uint8_t*)0x20000588 = 0xfe;
*(uint8_t*)0x20000589 = 0x88;
memset((void*)0x2000058a, 0, 12);
*(uint8_t*)0x20000596 = 0;
*(uint8_t*)0x20000597 = 1;
*(uint32_t*)0x20000598 = 0;
*(uint8_t*)0x20000600 = 0;
*(uint8_t*)0x20000601 = 0;
*(uint16_t*)0x20000602 = 9;
*(uint32_t*)0x20000604 = 0;
memcpy((void*)0x20000608, "\x7a\x76\xba\x73\x09\x0f\x9d\xec\x60\x70\xb3\xee\x98\x6e\x73\xcc\x50\x25\xf9\x5b\x01\xbd\x02\xb6\x98\xa7\x61\xe5\x9c\x7c\xca\x7d\xea\x7f\x08\xac\xfe\x98\x4a\x6c\x56\x3e\x1b\x36\xc9\xe5\xb2\xb1\xbc\x88\x4b\x67\x9d\xe5\x21\x15\x7e\xe2\x25\xf4\x50\x8d\x2f\x19\xa8\xc8\xbc\xaa\x8e\x07\xf3\xc3\xf2\xb9\x45\xdf\xdb\x16\x0a\x2a", 80);
	syscall(__NR_setsockopt, r[0], 6, 0xe, 0x20000580ul, 0xd8ul);
	syscall(__NR_shutdown, r[0], 1ul);
	return 0;
}
