// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[2] = {0xffffffffffffffff, 0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socketpair, 1ul, 1ul, 0, 0x20000080ul);
	if (res != -1) {
r[0] = *(uint32_t*)0x20000080;
r[1] = *(uint32_t*)0x20000084;
	}
*(uint64_t*)0x2000abc0 = 0;
*(uint32_t*)0x2000abc8 = 0;
*(uint64_t*)0x2000abd0 = 0x20003140;
*(uint64_t*)0x20003140 = 0x20000d80;
memset((void*)0x20000d80, 94, 1);
*(uint64_t*)0x20003148 = 1;
*(uint64_t*)0x2000abd8 = 1;
*(uint64_t*)0x2000abe0 = 0;
*(uint64_t*)0x2000abe8 = 0;
*(uint32_t*)0x2000abf0 = 0;
*(uint32_t*)0x2000abf8 = 0;
	syscall(__NR_sendmmsg, r[1], 0x2000abc0ul, 1ul, 0ul);
*(uint64_t*)0x20000500 = 0;
*(uint32_t*)0x20000508 = 0;
*(uint64_t*)0x20000510 = 0;
*(uint64_t*)0x20000518 = 0;
*(uint64_t*)0x20000520 = 0;
*(uint64_t*)0x20000528 = 0;
*(uint32_t*)0x20000530 = 0;
*(uint32_t*)0x20000538 = 0;
	syscall(__NR_recvmmsg, r[0], 0x20000500ul, 0x400000000000272ul, 0ul, 0ul);
	return 0;
}
