// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);

memcpy((void*)0x20000180, "./file0\000", 8);
	syscall(__NR_creat, 0x20000180ul, 0ul);
memcpy((void*)0x20000000, "./file0\000", 8);
memcpy((void*)0x200002c0, "trans=fd,", 9);
memcpy((void*)0x200002c9, "rfdno", 5);
*(uint8_t*)0x200002ce = 0x3d;
sprintf((char*)0x200002cf, "0x%016llx", (long long)-1);
*(uint8_t*)0x200002e1 = 0x2c;
memcpy((void*)0x200002e2, "wfdno", 5);
*(uint8_t*)0x200002e7 = 0x3d;
sprintf((char*)0x200002e8, "0x%016llx", (long long)-1);
*(uint8_t*)0x200002fa = 0x2c;
*(uint8_t*)0x200002fb = 0;
	syscall(__NR_mount, 0ul, 0x20000000ul, 0ul, 0x40022ul, 0x200002c0ul);
	return 0;
}
