// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socket, 0xaul, 2ul, 0x88);
	if (res != -1)
		r[0] = res;
*(uint8_t*)0x20000280 = 0xfc;
*(uint8_t*)0x20000281 = 1;
memset((void*)0x20000282, 0, 13);
*(uint8_t*)0x2000028f = 0;
*(uint8_t*)0x20000290 = 0xfc;
*(uint8_t*)0x20000291 = 0;
memset((void*)0x20000292, 0, 13);
*(uint8_t*)0x2000029f = 0;
*(uint8_t*)0x200002a0 = 0xfe;
*(uint8_t*)0x200002a1 = 0x80;
memset((void*)0x200002a2, 0, 13);
*(uint8_t*)0x200002af = 0xaa;
*(uint32_t*)0x200002b0 = 0;
*(uint16_t*)0x200002b4 = -1;
*(uint16_t*)0x200002b6 = 0;
*(uint32_t*)0x200002b8 = 0;
*(uint64_t*)0x200002c0 = 0;
*(uint32_t*)0x200002c8 = 0x1430098;
*(uint32_t*)0x200002cc = 0;
	syscall(__NR_ioctl, r[0], 0x890c, 0x20000280ul);
	return 0;
}
