// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socket, 0xaul, 2ul, 0);
	if (res != -1)
		r[0] = res;
*(uint64_t*)0x200013c0 = 0;
*(uint16_t*)0x200013c8 = 2;
*(uint16_t*)0x200013ca = htobe16(0);
*(uint32_t*)0x200013cc = htobe32(0);
*(uint16_t*)0x200013d8 = 2;
*(uint16_t*)0x200013da = htobe16(0);
*(uint32_t*)0x200013dc = htobe32(0xe0000001);
*(uint16_t*)0x200013e8 = 2;
*(uint16_t*)0x200013ea = htobe16(0);
*(uint32_t*)0x200013ec = htobe32(0xe0000001);
*(uint16_t*)0x200013f8 = 0;
*(uint16_t*)0x200013fa = 0;
*(uint64_t*)0x20001400 = 0;
*(uint64_t*)0x20001408 = 0;
*(uint16_t*)0x20001410 = 0;
*(uint64_t*)0x20001418 = 0;
*(uint64_t*)0x20001420 = 0;
*(uint64_t*)0x20001428 = 0;
*(uint16_t*)0x20001430 = 0;
	syscall(__NR_ioctl, r[0], 0x890b, 0x200013c0ul);
	return 0;
}
