// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socket, 0x10ul, 3ul, 4);
	if (res != -1)
		r[0] = res;
*(uint64_t*)0x20007bc0 = 0;
*(uint32_t*)0x20007bc8 = 0;
*(uint64_t*)0x20007bd0 = 0x20001e00;
*(uint64_t*)0x20001e00 = 0x20001d80;
memcpy((void*)0x20001d80, "\x97\xa4\x46\xd9\xec\x9a\xd1\x3f\x12\x19\xfb\xa7\x8c\x11\x42\xaa", 16);
*(uint64_t*)0x20001e08 = 0x10;
*(uint64_t*)0x20007bd8 = 1;
*(uint64_t*)0x20007be0 = 0;
*(uint64_t*)0x20007be8 = 0;
*(uint32_t*)0x20007bf0 = 0;
*(uint32_t*)0x20007bf8 = 0;
*(uint64_t*)0x20007c00 = 0;
*(uint32_t*)0x20007c08 = 0;
*(uint64_t*)0x20007c10 = 0;
*(uint64_t*)0x20007c18 = 0;
*(uint64_t*)0x20007c20 = 0;
*(uint64_t*)0x20007c28 = 0;
*(uint32_t*)0x20007c30 = 0;
*(uint32_t*)0x20007c38 = 0;
	syscall(__NR_sendmmsg, r[0], 0x20007bc0ul, 2ul, 0ul);
	return 0;
}
