// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

#define BITMASK(bf_off,bf_len) (((1ull << (bf_len)) - 1) << (bf_off))
#define STORE_BY_BITMASK(type,htobe,addr,val,bf_off,bf_len) *(type*)(addr) = htobe((htobe(*(type*)(addr)) & ~BITMASK((bf_off), (bf_len))) | (((type)(val) << (bf_off)) & BITMASK((bf_off), (bf_len))))

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socket, 0x10ul, 3ul, 0xc);
	if (res != -1)
		r[0] = res;
*(uint64_t*)0x20000580 = 0;
*(uint32_t*)0x20000588 = 0;
*(uint64_t*)0x20000590 = 0x20000540;
*(uint64_t*)0x20000540 = 0x200003c0;
*(uint32_t*)0x200003c0 = 0x24;
*(uint8_t*)0x200003c4 = 3;
*(uint8_t*)0x200003c5 = 1;
*(uint16_t*)0x200003c6 = 0x101;
*(uint32_t*)0x200003c8 = 0;
*(uint32_t*)0x200003cc = 0;
*(uint8_t*)0x200003d0 = 0;
*(uint8_t*)0x200003d1 = 0;
*(uint16_t*)0x200003d2 = htobe16(0);
*(uint16_t*)0x200003d4 = 0xc;
STORE_BY_BITMASK(uint16_t, , 0x200003d6, 0x19, 0, 14);
STORE_BY_BITMASK(uint16_t, , 0x200003d7, 0, 6, 1);
STORE_BY_BITMASK(uint16_t, , 0x200003d7, 1, 7, 1);
*(uint16_t*)0x200003d8 = 4;
*(uint16_t*)0x200003da = 2;
*(uint32_t*)0x200003dc = 0;
*(uint16_t*)0x200003e0 = 4;
STORE_BY_BITMASK(uint16_t, , 0x200003e2, 2, 0, 14);
STORE_BY_BITMASK(uint16_t, , 0x200003e3, 0, 6, 1);
STORE_BY_BITMASK(uint16_t, , 0x200003e3, 1, 7, 1);
*(uint64_t*)0x20000548 = 0x24;
*(uint64_t*)0x20000598 = 1;
*(uint64_t*)0x200005a0 = 0;
*(uint64_t*)0x200005a8 = 0;
*(uint32_t*)0x200005b0 = 0;
	syscall(__NR_sendmsg, r[0], 0x20000580ul, 0ul);
	return 0;
}
