// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socket, 2ul, 2ul, 0x88);
	if (res != -1)
		r[0] = res;
*(uint64_t*)0x20000580 = 0x20000000;
*(uint16_t*)0x20000000 = 2;
*(uint16_t*)0x20000002 = htobe16(0x4e00);
*(uint8_t*)0x20000004 = 0xac;
*(uint8_t*)0x20000005 = 0x14;
*(uint8_t*)0x20000006 = 0x14;
*(uint8_t*)0x20000007 = 0xaa;
*(uint32_t*)0x20000588 = 0x80;
*(uint64_t*)0x20000590 = 0;
*(uint64_t*)0x20000598 = 0;
*(uint64_t*)0x200005a0 = 0;
*(uint64_t*)0x200005a8 = 0;
*(uint32_t*)0x200005b0 = 0;
*(uint32_t*)0x200005b8 = 0;
	syscall(__NR_sendmmsg, r[0], 0x20000580ul, 1ul, 0x400c800ul);
*(uint64_t*)0x20000300 = 0;
*(uint32_t*)0x20000308 = 0;
*(uint64_t*)0x20000310 = 0;
*(uint64_t*)0x20000318 = 0;
*(uint64_t*)0x20000320 = 0;
*(uint64_t*)0x20000328 = 0;
*(uint32_t*)0x20000330 = 0;
*(uint32_t*)0x20000338 = 0;
*(uint64_t*)0x20000340 = 0x20000080;
*(uint16_t*)0x20000080 = 0;
memcpy((void*)0x20000082, "./file0\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000", 108);
*(uint32_t*)0x20000348 = 0x80;
*(uint64_t*)0x20000350 = 0;
*(uint64_t*)0x20000358 = 0;
*(uint64_t*)0x20000360 = 0x200015c0;
*(uint64_t*)0x200015c0 = 0x10;
*(uint32_t*)0x200015c8 = 0;
*(uint32_t*)0x200015cc = 0;
*(uint64_t*)0x200015d0 = 0x10;
*(uint32_t*)0x200015d8 = 0x11;
*(uint32_t*)0x200015dc = 0;
*(uint64_t*)0x20000368 = 0x20;
*(uint32_t*)0x20000370 = 0;
*(uint32_t*)0x20000378 = 0;
	syscall(__NR_sendmmsg, r[0], 0x20000300ul, 2ul, 0ul);
	return 0;
}
