// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <sched.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

#include <linux/sched.h>

#ifndef __NR_clone3
#define __NR_clone3 435
#endif

#define USLEEP_FORKED_CHILD (3 * 50 *1000)

static long handle_clone_ret(long ret)
{
	if (ret != 0) {
		return ret;
	}
	usleep(USLEEP_FORKED_CHILD);
	syscall(__NR_exit, 0);
	while (1) {
	}
}

#define MAX_CLONE_ARGS_BYTES 256
static long syz_clone3(volatile long a0, volatile long a1)
{
	unsigned long copy_size = a1;
	if (copy_size < sizeof(uint64_t) || copy_size > MAX_CLONE_ARGS_BYTES)
		return -1;
	char clone_args[MAX_CLONE_ARGS_BYTES];
	memcpy(&clone_args, (void*)a0, copy_size);
	uint64_t* flags = (uint64_t*)&clone_args;
	*flags &= ~CLONE_VM;
	return handle_clone_ret((long)syscall(__NR_clone3, &clone_args, copy_size));
}

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);

*(uint64_t*)0x200006c0 = 0x20000440;
*(uint16_t*)0x20000440 = 0x10;
*(uint16_t*)0x20000442 = 0;
*(uint32_t*)0x20000444 = 0;
*(uint32_t*)0x20000448 = 0;
*(uint32_t*)0x200006c8 = 0xc;
*(uint64_t*)0x200006d0 = 0;
*(uint64_t*)0x200006d8 = 1;
*(uint64_t*)0x200006e0 = 0;
*(uint64_t*)0x200006e8 = 0;
*(uint32_t*)0x200006f0 = 0;
	syscall(__NR_sendmsg, -1, 0x200006c0ul, 0ul);
*(uint64_t*)0x20000480 = 0;
*(uint64_t*)0x20000488 = 0x20000000;
*(uint64_t*)0x20000490 = 0x20000040;
*(uint64_t*)0x20000498 = 0x20000180;
*(uint32_t*)0x200004a0 = 0;
*(uint64_t*)0x200004a8 = 0x200000c0;
*(uint64_t*)0x200004b0 = 0x71;
*(uint64_t*)0x200004b8 = 0x200005c0;
*(uint64_t*)0x200004c0 = 0x20000440;
*(uint64_t*)0x200004c8 = 1;
*(uint32_t*)0x200004d0 = -1;
syz_clone3(0x20000480, 0x58);
	return 0;
}
