// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socket, 2ul, 3ul, 2);
	if (res != -1)
		r[0] = res;
*(uint32_t*)0x20000200 = 0;
	syscall(__NR_setsockopt, r[0], 0, 0xc8, 0x20000200ul, 4ul);
*(uint32_t*)0x200000c0 = htobe32(-1);
*(uint32_t*)0x200000c4 = htobe32(0xe0000001);
*(uint16_t*)0x200000c8 = 0;
memcpy((void*)0x200000ca, "\x5e\xb6\x56\x64\x56\x83\x5b\x0a\xaa\x05\x4e\x69\x4d\x7f\xae\xcc\x03\xd3\x24\x9f\xa6\x60\xbf\xa0\xde\x39\x36\xaf\x51\x87\xa6\xa5", 32);
*(uint32_t*)0x200000ec = 0;
*(uint32_t*)0x200000f0 = 0;
*(uint32_t*)0x200000f4 = 0;
*(uint32_t*)0x200000f8 = 0;
	syscall(__NR_setsockopt, r[0], 0, 0xd2, 0x200000c0ul, 0x3cul);
	return 0;
}
