// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[3] = {0xffffffffffffffff, 0xffffffffffffffff, 0x0};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socket, 2ul, 3ul, 2);
	if (res != -1)
		r[0] = res;
	res = syscall(__NR_socket, 0x11ul, 3ul, 0x300);
	if (res != -1)
		r[1] = res;
*(uint32_t*)0x20002bc0 = 0;
	syscall(__NR_setsockopt, r[0], 0, 0x21, 0x20002bc0ul, 4ul);
memcpy((void*)0x200002c0, "sit0\000\000\000\000\000\000\000\000\000\000\000\000", 16);
	res = syscall(__NR_ioctl, r[1], 0x8933, 0x200002c0ul);
	if (res != -1)
r[2] = *(uint32_t*)0x200002d0;
*(uint64_t*)0x200043c0 = 0x20000080;
*(uint16_t*)0x20000080 = 2;
*(uint16_t*)0x20000082 = htobe16(0);
*(uint32_t*)0x20000084 = htobe32(0xe0000001);
*(uint32_t*)0x200043c8 = 0x10;
*(uint64_t*)0x200043d0 = 0;
*(uint64_t*)0x200043d8 = 0;
*(uint64_t*)0x200043e0 = 0x20001480;
*(uint64_t*)0x20001480 = 0x1c;
*(uint32_t*)0x20001488 = 0;
*(uint32_t*)0x2000148c = 8;
*(uint32_t*)0x20001490 = r[2];
*(uint8_t*)0x20001494 = 0xac;
*(uint8_t*)0x20001495 = 0x14;
*(uint8_t*)0x20001496 = 0x14;
*(uint8_t*)0x20001497 = 0xbb;
*(uint32_t*)0x20001498 = htobe32(0xe0000002);
*(uint64_t*)0x200043e8 = 0x20;
*(uint32_t*)0x200043f0 = 0;
*(uint32_t*)0x200043f8 = 0;
	syscall(__NR_sendmmsg, r[0], 0x200043c0ul, 1ul, 0ul);
	return 0;
}
