// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

#ifndef __NR_fsconfig
#define __NR_fsconfig 431
#endif
#ifndef __NR_fsopen
#define __NR_fsopen 430
#endif

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
memcpy((void*)0x20000000, "debugfs\000", 8);
	res = syscall(__NR_fsopen, 0x20000000ul, 0ul);
	if (res != -1)
		r[0] = res;
memcpy((void*)0x20000080, "tracefs\000", 8);
memcpy((void*)0x200001c0, "5\322\346\365#<o\325\220\v*\371\023\345#?v\254\267i\251\351T\206=\243\207\277S\262\236#(IE\313\"\263\234\262M/*\242\3615N\262\004 Eh\335\3275A\354\244\234b\305\237\\\210W\217\214\002\216\372\323\001\316\207\313\254\244W\356km\262\254\373\212\037*Aq]\370\245\2753m\362u\\psVm\207\323\361\245\353>\242-\200=\017c\372q2\304\330I\025\315\310q\203@\334\214\b\236ZH\301", 133);
	syscall(__NR_fsconfig, r[0], 1ul, 0x20000080ul, 0x200001c0ul, 0ul);
	syscall(__NR_fsconfig, r[0], 6ul, 0ul, 0ul, 0ul);
	return 0;
}
