// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[1] = {0x0};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
memcpy((void*)0x20000040, "logon\000", 6);
memcpy((void*)0x20000080, "fscrypt:", 8);
*(uint8_t*)0x20000088 = 0;
*(uint8_t*)0x20000089 = 0;
*(uint8_t*)0x2000008a = 0;
*(uint8_t*)0x2000008b = 0;
*(uint8_t*)0x2000008c = 0;
*(uint8_t*)0x2000008d = 0;
*(uint8_t*)0x2000008e = 0;
*(uint8_t*)0x2000008f = 0;
*(uint8_t*)0x20000090 = 0;
*(uint8_t*)0x20000091 = 0;
*(uint8_t*)0x20000092 = 0;
*(uint8_t*)0x20000093 = 0;
*(uint8_t*)0x20000094 = 0;
*(uint8_t*)0x20000095 = 0;
*(uint8_t*)0x20000096 = 0;
*(uint8_t*)0x20000097 = 0;
*(uint8_t*)0x20000098 = 0;
*(uint32_t*)0x200000c0 = 0;
memcpy((void*)0x200000c4, "\x5e\xc5\x02\xfb\x50\xde\x85\x9d\x8f\x48\x15\x1f\x58\xa0\xeb\xf5\x54\x68\xe8\x9e\x64\xa7\x99\xdf\xd1\xd5\x9b\x27\x31\x83\x50\xde\xdd\x9c\x5e\x35\x53\xd3\x6d\x05\xca\x2d\x84\x2e\x48\x81\xa2\xd9\xf5\xd6\xf0\x18\x26\x00\x79\x7f\x0e\x03\x45\xde\x5c\x7f\xe4\x3d", 64);
*(uint32_t*)0x20000104 = 0;
	res = syscall(__NR_add_key, 0x20000040ul, 0x20000080ul, 0x200000c0ul, 0x48ul, 0xfffffffb);
	if (res != -1)
		r[0] = res;
	syscall(__NR_keyctl, 0x10ul, r[0], 0, 0, 0);
	return 0;
}
