// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <fcntl.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

static long syz_open_dev(volatile long a0, volatile long a1, volatile long a2)
{
	if (a0 == 0xc || a0 == 0xb) {
		char buf[128];
		sprintf(buf, "/dev/%s/%d:%d", a0 == 0xc ? "char" : "block", (uint8_t)a1, (uint8_t)a2);
		return open(buf, O_RDWR, 0);
	} else {
		char buf[1024];
		char* hash;
		strncpy(buf, (char*)a0, sizeof(buf) - 1);
		buf[sizeof(buf) - 1] = 0;
		while ((hash = strchr(buf, '#'))) {
			*hash = '0' + (char)(a1 % 10);
			a1 /= 10;
		}
		return open(buf, a2, 0);
	}
}

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = -1;
res = syz_open_dev(0xc, 4, 1);
	if (res != -1)
		r[0] = res;
memcpy((void*)0x20000100, "#! ", 3);
memcpy((void*)0x20000103, "./file0", 7);
*(uint8_t*)0x2000010a = 0xa;
memcpy((void*)0x2000010b, "\x66\xcf\xd4\xc3\xc4\xc2\xc5\xe6\xb6\xd4\x7f\x91\x56\xe5\x1b\x92\xd3\xdb\x70\xa7\xe4\x10\xdb\x5d\x1e\x22\x90\x4b\x8d\x9b\xc9\xf0\x4d\xe8\xbf\x75\x06\x8a\x0b\x3f\x8e\xc1\x05\xd8\x67\xd6\x41\x18\x42\x04\xc8\x4a\x7c\x31\x6b\xb9\x2b\xbe\x67\x74\x50\xd1\x35\xa8\x5e\xa5\x99\x74\x1a\x03\xa1\x12\xed\x66\x53\xdb\x01\x95\xbb\x7d\xdb\xa0\xc2\xed\x28\xd5\x66\x91\x15\x60\x89\xd8\xc2\xc5\xd4\xc5\x74\x2f\x90\xbb\x82\x71\x8a\x81\x3a\x0e\xe9\xea\x99\x76\x19\x13\x2e\xa7\x6c\xb0\xed\x10\xff\xc9\x1f\x16\xe7\x4c\x32\x23\x9b\x50\x0c\x46\x1e\x68\x14\xc4\xa5\x7f\x31\x45\x48\x21\x02\x06\x9c\x6a\x53\xe4\xb6\x32\x4c\x85\x3d\x0a\x6f\x7d\xec\x1c\x9e\x92\xf7\x9b\x72", 161);
	syscall(__NR_write, r[0], 0x20000100ul, 0xacul);
	return 0;
}
