// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <errno.h>
#include <fcntl.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/ioctl.h>
#include <sys/mount.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

#include <linux/loop.h>

#ifndef __NR_memfd_create
#define __NR_memfd_create 319
#endif

static unsigned long long procid;

static long syz_open_procfs(volatile long a0, volatile long a1)
{
	char buf[128];
	memset(buf, 0, sizeof(buf));
	if (a0 == 0) {
		snprintf(buf, sizeof(buf), "/proc/self/%s", (char*)a1);
	} else if (a0 == -1) {
		snprintf(buf, sizeof(buf), "/proc/thread-self/%s", (char*)a1);
	} else {
		snprintf(buf, sizeof(buf), "/proc/self/task/%d/%s", (int)a0, (char*)a1);
	}
	int fd = open(buf, O_RDWR);
	if (fd == -1)
		fd = open(buf, O_RDONLY);
	return fd;
}

struct fs_image_segment {
	void* data;
	uintptr_t size;
	uintptr_t offset;
};
static int setup_loop_device(long unsigned size, long unsigned nsegs, struct fs_image_segment* segs, const char* loopname, int* memfd_p, int* loopfd_p)
{
	int err = 0, loopfd = -1;
	int memfd = syscall(__NR_memfd_create, "syzkaller", 0);
	if (memfd == -1) {
		err = errno;
		goto error;
	}
	if (ftruncate(memfd, size)) {
		err = errno;
		goto error_close_memfd;
	}
	for (size_t i = 0; i < nsegs; i++) {
		if (pwrite(memfd, segs[i].data, segs[i].size, segs[i].offset) < 0) {
		}
	}
	loopfd = open(loopname, O_RDWR);
	if (loopfd == -1) {
		err = errno;
		goto error_close_memfd;
	}
	if (ioctl(loopfd, LOOP_SET_FD, memfd)) {
		if (errno != EBUSY) {
			err = errno;
			goto error_close_loop;
		}
		ioctl(loopfd, LOOP_CLR_FD, 0);
		usleep(1000);
		if (ioctl(loopfd, LOOP_SET_FD, memfd)) {
			err = errno;
			goto error_close_loop;
		}
	}
	*memfd_p = memfd;
	*loopfd_p = loopfd;
	return 0;

error_close_loop:
	close(loopfd);
error_close_memfd:
	close(memfd);
error:
	errno = err;
	return -1;
}

static long syz_mount_image(volatile long fsarg, volatile long dir, volatile unsigned long size, volatile unsigned long nsegs, volatile long segments, volatile long flags, volatile long optsarg, volatile long change_dir)
{
	struct fs_image_segment* segs = (struct fs_image_segment*)segments;
	int res = -1, err = 0, loopfd = -1, memfd = -1, need_loop_device = !!segs;
	char* mount_opts = (char*)optsarg;
	char* target = (char*)dir;
	char* fs = (char*)fsarg;
	char* source = NULL;
	char loopname[64];
	if (need_loop_device) {
		memset(loopname, 0, sizeof(loopname));
		snprintf(loopname, sizeof(loopname), "/dev/loop%llu", procid);
		if (setup_loop_device(size, nsegs, segs, loopname, &memfd, &loopfd) == -1)
			return -1;
		source = loopname;
	}
	mkdir(target, 0777);
	char opts[256];
	memset(opts, 0, sizeof(opts));
	if (strlen(mount_opts) > (sizeof(opts) - 32)) {
	}
	strncpy(opts, mount_opts, sizeof(opts) - 32);
	if (strcmp(fs, "iso9660") == 0) {
		flags |= MS_RDONLY;
	} else if (strncmp(fs, "ext", 3) == 0) {
		if (strstr(opts, "errors=panic") || strstr(opts, "errors=remount-ro") == 0)
			strcat(opts, ",errors=continue");
	} else if (strcmp(fs, "xfs") == 0) {
		strcat(opts, ",nouuid");
	}
	res = mount(source, target, fs, flags, opts);
	if (res == -1) {
		err = errno;
		goto error_clear_loop;
	}
	res = open(target, O_RDONLY | O_DIRECTORY);
	if (res == -1) {
		err = errno;
		goto error_clear_loop;
	}
	if (change_dir) {
		res = chdir(target);
		if (res == -1) {
			err = errno;
		}
	}

error_clear_loop:
	if (need_loop_device) {
		ioctl(loopfd, LOOP_CLR_FD, 0);
		close(loopfd);
		close(memfd);
	}
	errno = err;
	return res;
}

uint64_t r[3] = {0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
memcpy((void*)0x200000c0, "./file0\000", 8);
syz_mount_image(0, 0x200000c0, 0, 0, 0x20000000, 0, 0, 0);
memcpy((void*)0x20000000, "/de\000o\\v/s", 9);
memcpy((void*)0x20000080, "./file0\000", 8);
memcpy((void*)0x200001c0, "nfs\000", 4);
memcpy((void*)0x20000200, "-.%@^:])\000", 9);
	syscall(__NR_mount, 0x20000000ul, 0x20000080ul, 0x200001c0ul, 0x280000ul, 0x20000200ul);
memcpy((void*)0x20000300, "ext2\000", 5);
memcpy((void*)0x20000340, "./file0\000", 8);
*(uint64_t*)0x20000640 = 0x20000400;
memcpy((void*)0x20000400, "\x40\xf4\x34\xce\x02\xdd\x85\x72\x85\x17\x84\x17\x3d\x5a\x34\x54\x7a\x1d\x8b\xb5\xbb\x3c\x4d\x26\x4d\xd5\xbf\x03\xa7\x83\x19\x6d\xce\x6e\x34\x5e\x6e\x55\x11\xd7\x3c\x18\x4c\x30\xe5\x5e\xa0\xfb\x32\x32\x9d\xbb\x72\xce\x3e\x06\xcc\x54\x78\x57\xb3\xfa\x1f\x5a\xed\xa1\x23\x7f\x3b\xa2\x54\xf0\xe2\x01\x94\xc2\xee\xd6\x02\xfc\xf8\x53\xd4\x6f\xd1\x99\xd6\x63\xea\x84\x26\x76\xb3\x24\xd3\xce\x1d\xeb\x75\x0a\xe9\xc2\xd3\x0c\x8d\x16\x39\x5c\x53\x2c\x4f\xbc\xdb\x65\x63\x3d\x0d\x4e\xfe\x53\x50\x89\xee\xaa\x8b\x37\x11\xfb\x34\x2c\x6d\x8a\x8b\xff\xc6\x2d\xd8\xe0\x59\xa7\x74\x61\xbb\xd4\x3a\xc6\x4b\x4a\x9b\x84\x2d\x46\xe3\x6e\xeb\x36\x98\xee\x66\xe0\xeb\xee\xc3\x4f\x45\x68\xed\x51\x7c\x31\x59\x92\xa6\xeb\x30\xed\x19\xa0\xa6\x5a\x20\x3e\x12\x65\x3d\x60\xfb\xe8\xba\x09\x9f\xa0\x76\xd4\xe4\xe0\x46\xb4\xc9\x9f\x26\xb7\xfd\xef\x8f\x55\x78\x4c\xd5\xcd\x4e", 211);
*(uint64_t*)0x20000648 = 0xd3;
*(uint64_t*)0x20000650 = 9;
memcpy((void*)0x20000800, "minixdf", 7);
*(uint8_t*)0x20000807 = 0x2c;
memcpy((void*)0x20000808, "jqfmt=vfsold", 12);
*(uint8_t*)0x20000814 = 0x2c;
memcpy((void*)0x20000815, "bh", 2);
*(uint8_t*)0x20000817 = 0x2c;
memcpy((void*)0x20000818, "prjquota", 8);
*(uint8_t*)0x20000820 = 0x2c;
memcpy((void*)0x20000821, "acl", 3);
*(uint8_t*)0x20000824 = 0x2c;
memcpy((void*)0x20000825, "nolazytime", 10);
*(uint8_t*)0x2000082f = 0x2c;
*(uint8_t*)0x20000830 = 0;
syz_mount_image(0x20000300, 0x20000340, 0xdc, 1, 0x20000640, 0x102440, 0x20000800, 0);
memcpy((void*)0x20000100, "./file0\000", 8);
memcpy((void*)0x20000140, "tmpfs\000", 6);
memcpy((void*)0x20000180, "mpol=prefer", 11);
	syscall(__NR_mount, 0ul, 0x20000100ul, 0x20000140ul, 0ul, 0x20000180ul);
memcpy((void*)0x20000040, "mountinfo\000", 10);
	res = -1;
res = syz_open_procfs(-1, 0x20000040);
	if (res != -1)
		r[0] = res;
memcpy((void*)0x20000280, "/dev/null\000", 10);
	res = syscall(__NR_openat, 0xffffffffffffff9cul, 0x20000280ul, 0x101841ul, 0ul);
	if (res != -1)
		r[1] = res;
memcpy((void*)0x20000240, "./file0\000", 8);
memcpy((void*)0x200002c0, "./file0\000", 8);
	syscall(__NR_pivot_root, 0x20000240ul, 0x200002c0ul);
	syscall(__NR_sendfile, r[1], r[0], 0ul, 0xe76ful);
memcpy((void*)0x20000140, ":@\000", 3);
	res = syscall(__NR_mq_open, 0x20000140ul, 0ul, 0ul, 0ul);
	if (res != -1)
		r[2] = res;
	syscall(__NR_mq_notify, r[2], 0ul);
	syscall(__NR_pread64, r[2], 0x20000700ul, 0xfdul, 4ul);
	return 0;
}
