// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <sched.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

#define USLEEP_FORKED_CHILD (3 * 50 *1000)

static long handle_clone_ret(long ret)
{
	if (ret != 0) {
		return ret;
	}
	usleep(USLEEP_FORKED_CHILD);
	syscall(__NR_exit, 0);
	while (1) {
	}
}

static long syz_clone(volatile long flags, volatile long stack, volatile long stack_len,
		      volatile long ptid, volatile long ctid, volatile long tls)
{
	long sp = (stack + stack_len) & ~15;
	long ret = (long)syscall(__NR_clone, flags & ~CLONE_VM, sp, ptid, ctid, tls);
	return handle_clone_ret(ret);
}

uint64_t r[2] = {0x0, 0x0};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
syz_clone(0, 0, 0, 0, 0, 0);
	res = -1;
res = syz_clone(0, 0, 0, 0, 0, 0);
	if (res != -1)
		r[0] = res;
	syscall(__NR_ptrace, 0x10ul, r[0], 0, 0);
	res = -1;
res = syz_clone(0, 0, 0, 0, 0, 0);
	if (res != -1)
		r[1] = res;
	syscall(__NR_ptrace, 0x10ul, r[1], 0, 0);
*(uint64_t*)0x20000000 = 0x20000140;
*(uint64_t*)0x20000008 = 0x1000;
	syscall(__NR_ptrace, 0x4204ul, r[1], 2ul, 0x20000000ul);
*(uint32_t*)0x200000c0 = 0x11;
*(uint32_t*)0x200000c4 = 0;
*(uint32_t*)0x200000c8 = 0x7ff;
	syscall(__NR_ptrace, 0x4203ul, r[1], 6ul, 0x200000c0ul);
*(uint64_t*)0x20000000 = 0x20000140;
*(uint64_t*)0x20000008 = 0x1000;
	syscall(__NR_ptrace, 0x4204ul, r[0], 2ul, 0x20000000ul);
*(uint32_t*)0x20000040 = 0;
*(uint32_t*)0x20000044 = 0;
*(uint32_t*)0x20000048 = 1;
	syscall(__NR_ptrace, 0x4203ul, r[0], 0ul, 0x20000040ul);
	syscall(__NR_ioprio_set, 2ul, 0, 0ul);
	return 0;
}
