// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);

memcpy((void*)0x20000040, "new ", 4);
memcpy((void*)0x20000044, "default", 7);
*(uint8_t*)0x2000004b = 0x20;
memcpy((void*)0x2000004c, "trusted:", 8);
memset((void*)0x20000054, 91, 1);
*(uint8_t*)0x20000055 = 0x20;
sprintf((char*)0x20000056, "%020llu", (long long)0);
*(uint8_t*)0x2000006a = 0;
	syscall(__NR_keyctl, 0xcul, 0, 0x20000040ul, 0xfffffffffffffe68ul, 0);
	return 0;
}
