// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <fcntl.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

static long syz_open_dev(volatile long a0, volatile long a1, volatile long a2)
{
	if (a0 == 0xc || a0 == 0xb) {
		char buf[128];
		sprintf(buf, "/dev/%s/%d:%d", a0 == 0xc ? "char" : "block", (uint8_t)a1, (uint8_t)a2);
		return open(buf, O_RDWR, 0);
	} else {
		char buf[1024];
		char* hash;
		strncpy(buf, (char*)a0, sizeof(buf) - 1);
		buf[sizeof(buf) - 1] = 0;
		while ((hash = strchr(buf, '#'))) {
			*hash = '0' + (char)(a1 % 10);
			a1 /= 10;
		}
		return open(buf, a2, 0);
	}
}

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
memcpy((void*)0x20000940, "/dev/loop#\000", 11);
	res = -1;
res = syz_open_dev(0x20000940, 0, 0);
	if (res != -1)
		r[0] = res;
*(uint32_t*)0x20000980 = 0;
*(uint16_t*)0x20000988 = 0;
*(uint64_t*)0x20000990 = 0;
*(uint16_t*)0x20000998 = 0;
*(uint32_t*)0x200009a0 = 0;
*(uint32_t*)0x200009a4 = 0;
*(uint32_t*)0x200009a8 = 0;
*(uint32_t*)0x200009ac = 0x1c;
memcpy((void*)0x200009b0, "\x1f\xeb\xa9\x0e\x0c\x9c\x3a\x64\x34\x75\xf0\x11\x8b\x10\xab\xb9\xb6\x9f\x8e\x4c\xa1\x1a\xe1\xd7\x41\x38\x21\x3e\xf8\xe0\x6c\x48\x98\x22\x3d\x2c\xe1\x0f\x1f\xaa\xca\xf6\xec\xeb\x42\xfc\xe7\xb2\xd0\xf7\x6e\x23\xf3\x5c\xbf\x11\x0b\x87\x71\x5f\x49\x44\x20\xe8", 64);
memcpy((void*)0x200009f0, "\xdc\x74\x49\xb0\x67\xb4\x06\xab\x24\x22\x85\x9c\x91\xc2\x7e\xe6\x42\xfd\x8d\x67\xcc\xcd\x86\x7a\x2c\x07\x24\x49\x48\x5a\xf0\xb8", 32);
*(uint64_t*)0x20000a10 = 0xfffffffffffffffc;
*(uint64_t*)0x20000a18 = 4;
*(uint32_t*)0x20000a20 = 0;
	syscall(__NR_ioctl, r[0], 0x4c02, 0x20000980ul);
	return 0;
}
