// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <sched.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

#include <linux/sched.h>

#ifndef __NR_clone3
#define __NR_clone3 435
#endif

#define USLEEP_FORKED_CHILD (3 * 50 *1000)

static long handle_clone_ret(long ret)
{
	if (ret != 0) {
		return ret;
	}
	usleep(USLEEP_FORKED_CHILD);
	syscall(__NR_exit, 0);
	while (1) {
	}
}

#define MAX_CLONE_ARGS_BYTES 256
static long syz_clone3(volatile long a0, volatile long a1)
{
	unsigned long copy_size = a1;
	if (copy_size < sizeof(uint64_t) || copy_size > MAX_CLONE_ARGS_BYTES)
		return -1;
	char clone_args[MAX_CLONE_ARGS_BYTES];
	memcpy(&clone_args, (void*)a0, copy_size);
	uint64_t* flags = (uint64_t*)&clone_args;
	*flags &= ~CLONE_VM;
	return handle_clone_ret((long)syscall(__NR_clone3, &clone_args, copy_size));
}

uint64_t r[6] = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_msgget, 0ul, 0x42aul);
	if (res != -1)
		r[0] = res;
	syscall(__NR_msgctl, r[0], 3ul, 0x20000180ul);
	syscall(__NR_msgctl, r[0], 2ul, 0x20000280ul);
	res = syscall(__NR_msgget, 0ul, 0ul);
	if (res != -1)
		r[1] = res;
	syscall(__NR_msgctl, r[1], 0ul, 0);
	syscall(__NR_msgctl, r[1], 0xcul, 0x200003c0ul);
	res = syscall(__NR_msgget, 0ul, 0x20ul);
	if (res != -1)
		r[2] = res;
	syscall(__NR_msgctl, r[2], 0xbul, 0x200000c0ul);
	syscall(__NR_msgget, 0ul, 0x208ul);
	syscall(__NR_timer_delete, 0);
	syscall(__NR_msgget, 0ul, 0x100ul);
memcpy((void*)0x200017c0, "\x01\x00\x00\x00\x01\x00\x02\x00\x18\x00\x00\x00\x3d\x09\xf9\xd8\xd7\xe1\x78\x51\x8c\x6c\xe2\x72\x0c\x73\x20\xc3\xc4\x9c\xbb\x38\x41\xcc\xc9\xe9\xb8\xa6\x62\xd1\xed\xdd\x55\x13\xe5\x27\x64\x6c\x78\x2e\x0e\x46\xc7\x74\xf9\x06\xd7\x51\x3c\xb8\xfc\x72\x4f\x7d\x9e\xed\x19\x80\x8a\x1f\x27\x12\x18\x2c\x48\xb8\xf7\xb7\x3a\x9f\x09\xdf\xbb\xa3\x0a\x24\xe1\x9c\xf7\x28\x46\xe6\x16\x07\xea\xa5\x72\x2c\x0b\xe9\xb3\xc5\xfd\xdf\xee\x66\xd6\xe8\x65\xf9\xde\x1f\x62\x79\x19\xc5\xea\x63\xea\x4e\x84\x0e\xef\xe6\x95\xe5\x95\x50\x85\x1a\x36\x6f\x43\x64\xbf\x17\x44\x3d\xef\x43\xf8\xe8\x4d\xa7\x17\xd4\x35\xf4\x1f\x66\x82\x5d\xef\xa1\x8e\x58\x41\x2d\x37\x8e\xb0\x5d\xb8\xa0\x16\x7d\xc0\xc6\x49\xd7\x1e\x20\x08\xd5\x3c\xfb\xba\xde\x92\x2f\x56\x17\x41\x2d\x96\xc2\xef\xef\xc7\x3d\x01\x7e\x86\x31\xea\x17\x70\xaf\x61\xba\x93\xf9\x5f\xe9\xeb\x77\xf1\x5b\x6c\xe2\xae\xda\x3e\x61\xca", 215);
*(uint32_t*)0x20001897 = -1;
*(uint32_t*)0x2000189b = 0;
*(uint32_t*)0x2000189f = -1;
memcpy((void*)0x200018a3, "./file0\000", 8);
	res = syscall(__NR_ioctl, -1, 0xc018937b, 0x200017c0ul);
	if (res != -1)
r[3] = *(uint32_t*)0x2000189b;
	res = syscall(__NR_getresuid, 0x20000140ul, 0x200004c0ul, 0x20000500ul);
	if (res != -1)
r[4] = *(uint32_t*)0x200004c0;
*(uint64_t*)0x200016c0 = 0x200000000;
*(uint64_t*)0x200016c8 = 0x20000540;
*(uint64_t*)0x200016d0 = 0x20000580;
*(uint64_t*)0x200016d8 = 0x200005c0;
*(uint32_t*)0x200016e0 = 0x41;
*(uint64_t*)0x200016e8 = 0x20000600;
*(uint64_t*)0x200016f0 = 0x1000;
*(uint64_t*)0x200016f8 = 0x20001600;
*(uint64_t*)0x20001700 = 0x20001680;
*(uint32_t*)0x20001680 = -1;
*(uint32_t*)0x20001684 = 0;
*(uint32_t*)0x20001688 = 0;
*(uint32_t*)0x2000168c = 0;
*(uint32_t*)0x20001690 = -1;
*(uint64_t*)0x20001708 = 5;
*(uint32_t*)0x20001710 = -1;
	res = -1;
res = syz_clone3(0x200016c0, 0x58);
	if (res != -1)
r[5] = *(uint32_t*)0x200005c0;
	syscall(__NR_keyctl, 6ul, 0, 0x200018c0ul, 0xeful, 0);
*(uint32_t*)0x20001740 = 0x798e2635;
*(uint32_t*)0x20001744 = r[3];
*(uint32_t*)0x20001748 = 0;
*(uint32_t*)0x2000174c = r[4];
*(uint32_t*)0x20001750 = 0;
*(uint32_t*)0x20001754 = 0x1b0;
*(uint16_t*)0x20001758 = 0x58;
*(uint64_t*)0x20001760 = 0;
*(uint64_t*)0x20001768 = 0;
*(uint64_t*)0x20001770 = 7;
*(uint64_t*)0x20001778 = 5;
*(uint64_t*)0x20001780 = 7;
*(uint64_t*)0x20001788 = 1;
*(uint64_t*)0x20001790 = 7;
*(uint16_t*)0x20001798 = 0xff01;
*(uint16_t*)0x2000179a = 0x8001;
*(uint16_t*)0x2000179c = 0;
*(uint32_t*)0x200017a0 = r[5];
*(uint32_t*)0x200017a4 = 0;
	syscall(__NR_msgctl, r[2], 1ul, 0x20001740ul);
	return 0;
}
