// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <sched.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

#define USLEEP_FORKED_CHILD (3 * 50 *1000)

static long handle_clone_ret(long ret)
{
	if (ret != 0) {
		return ret;
	}
	usleep(USLEEP_FORKED_CHILD);
	syscall(__NR_exit, 0);
	while (1) {
	}
}

static long syz_clone(volatile long flags, volatile long stack, volatile long stack_len,
		      volatile long ptid, volatile long ctid, volatile long tls)
{
	long sp = (stack + stack_len) & ~15;
	long ret = (long)syscall(__NR_clone, flags & ~CLONE_VM, sp, ptid, ctid, tls);
	return handle_clone_ret(ret);
}

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);

memcpy((void*)0x20000300, "\xfd\x3b\x91\xcb\x47\x5f\xe9\x13\xe7\x0e\x81\xd5\xcb\x04\xf3\xbf\x07\x55\x70\x1b\x05\x39\x8f\x0c\x73\xe7\xd9\x01\x45\x24\x43\x54\xc2\x27\x8f\xa8\xfb\x34\x36\xf6\xe4\x55\x4e\xce\x30\xeb\x8b\x89\xaf\xb9\x6c\xa0\x85\x02\x11\x5d\xbf\xe5\xae\x41\x43\x1d\xa9\xea\x1c\x22\xdd\x47\xb9\x7a\x0b\xa5\xd1\xc2\x66\x5b\x6e\x18\x9d\x49\xd1\x77\xaf\x50\xc4\x43\x16\xf8\xc0\x2b\xa2\x34\x5a\x79\xf6\x50\x01\x5d\xe8\x46\xc9\x2e\xba\x41\x04\x1a\xde\x1f\x30\x9c\x33\xf2\xbc\x5b\x91\xfc\xb4\xc3\xea\xca\x4a\xc6\x3c\x92", 124);
syz_clone(0x4000000, 0x20000200, 0, 0x20000280, 0x200002c0, 0x20000300);
	return 0;
}
