// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

#define BITMASK(bf_off,bf_len) (((1ull << (bf_len)) - 1) << (bf_off))
#define STORE_BY_BITMASK(type,htobe,addr,val,bf_off,bf_len) *(type*)(addr) = htobe((htobe(*(type*)(addr)) & ~BITMASK((bf_off), (bf_len))) | (((type)(val) << (bf_off)) & BITMASK((bf_off), (bf_len))))

struct csum_inet {
	uint32_t acc;
};

static void csum_inet_init(struct csum_inet* csum)
{
	csum->acc = 0;
}

static void csum_inet_update(struct csum_inet* csum, const uint8_t* data, size_t length)
{
	if (length == 0)
		return;
	size_t i = 0;
	for (; i < length - 1; i += 2)
		csum->acc += *(uint16_t*)&data[i];
	if (length & 1)
		csum->acc += le16toh((uint16_t)data[length - 1]);
	while (csum->acc > 0xffff)
		csum->acc = (csum->acc & 0xffff) + (csum->acc >> 16);
}

static uint16_t csum_inet_digest(struct csum_inet* csum)
{
	return ~csum->acc;
}

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socket, 2ul, 2ul, 0);
	if (res != -1)
		r[0] = res;
memcpy((void*)0x20000240, "syztnl0\000\000\000\000\000\000\000\000\000", 16);
*(uint64_t*)0x20000250 = 0x20000100;
memcpy((void*)0x20000100, "sit0\000\000\000\000\000\000\000\000\000\000\000\000", 16);
*(uint32_t*)0x20000110 = 0;
*(uint16_t*)0x20000114 = htobe16(0);
*(uint16_t*)0x20000116 = htobe16(0);
*(uint32_t*)0x20000118 = htobe32(0);
*(uint32_t*)0x2000011c = htobe32(0);
STORE_BY_BITMASK(uint8_t, , 0x20000120, 0x45, 0, 4);
STORE_BY_BITMASK(uint8_t, , 0x20000120, 4, 4, 4);
STORE_BY_BITMASK(uint8_t, , 0x20000121, 0, 0, 2);
STORE_BY_BITMASK(uint8_t, , 0x20000121, 0, 2, 6);
*(uint16_t*)0x20000122 = htobe16(0x114);
*(uint16_t*)0x20000124 = htobe16(0);
*(uint16_t*)0x20000126 = htobe16(0);
*(uint8_t*)0x20000128 = 0;
*(uint8_t*)0x20000129 = 0;
*(uint16_t*)0x2000012a = htobe16(0);
*(uint32_t*)0x2000012c = htobe32(0);
*(uint32_t*)0x20000130 = htobe32(0);
*(uint8_t*)0x20000134 = 0x44;
*(uint8_t*)0x20000135 = 0x14;
*(uint8_t*)0x20000136 = 0;
STORE_BY_BITMASK(uint8_t, , 0x20000137, 0, 0, 4);
STORE_BY_BITMASK(uint8_t, , 0x20000137, 0, 4, 4);
*(uint32_t*)0x20000138 = htobe32(0);
*(uint32_t*)0x2000013c = htobe32(0);
*(uint32_t*)0x20000140 = htobe32(0);
*(uint32_t*)0x20000144 = htobe32(0);
*(uint8_t*)0x20000148 = 0x44;
*(uint8_t*)0x20000149 = 0xc;
*(uint8_t*)0x2000014a = 0;
STORE_BY_BITMASK(uint8_t, , 0x2000014b, 3, 0, 4);
STORE_BY_BITMASK(uint8_t, , 0x2000014b, 0, 4, 4);
*(uint8_t*)0x2000014c = 0xac;
*(uint8_t*)0x2000014d = 0x14;
*(uint8_t*)0x2000014e = 0x14;
*(uint8_t*)0x2000014f = 0xbb;
*(uint32_t*)0x20000150 = htobe32(0);
*(uint8_t*)0x20000154 = 0x44;
*(uint8_t*)0x20000155 = 0x24;
*(uint8_t*)0x20000156 = 0;
STORE_BY_BITMASK(uint8_t, , 0x20000157, 1, 0, 4);
STORE_BY_BITMASK(uint8_t, , 0x20000157, 0, 4, 4);
*(uint32_t*)0x20000158 = htobe32(0);
*(uint32_t*)0x2000015c = htobe32(0);
*(uint32_t*)0x20000160 = htobe32(0x7f000001);
*(uint32_t*)0x20000164 = htobe32(0);
*(uint32_t*)0x20000168 = htobe32(0x7f000001);
*(uint32_t*)0x2000016c = htobe32(0);
*(uint32_t*)0x20000170 = htobe32(0);
*(uint32_t*)0x20000174 = htobe32(0);
*(uint8_t*)0x20000178 = 1;
*(uint8_t*)0x20000179 = 0;
*(uint8_t*)0x2000017a = 0xa;
memcpy((void*)0x2000017b, "\x06\x69\x01\xe7\xc4\x42\x44\x0a", 8);
*(uint8_t*)0x20000183 = 0x44;
*(uint8_t*)0x20000184 = 0x18;
*(uint8_t*)0x20000185 = 0;
STORE_BY_BITMASK(uint8_t, , 0x20000186, 0, 0, 4);
STORE_BY_BITMASK(uint8_t, , 0x20000186, 0, 4, 4);
*(uint32_t*)0x20000187 = htobe32(0);
*(uint32_t*)0x2000018b = htobe32(0);
*(uint32_t*)0x2000018f = htobe32(0);
*(uint32_t*)0x20000193 = htobe32(0);
*(uint32_t*)0x20000197 = htobe32(0);
*(uint8_t*)0x2000019b = 0x86;
*(uint8_t*)0x2000019c = 0x5f;
*(uint32_t*)0x2000019d = htobe32(0);
*(uint8_t*)0x200001a1 = 0;
*(uint8_t*)0x200001a2 = 0x11;
memcpy((void*)0x200001a3, "\xe1\x40\xbb\xf2\x29\xd0\x2c\x1c\x06\xa1\x08\x9e\x08\xc9\x00", 15);
*(uint8_t*)0x200001b2 = 0;
*(uint8_t*)0x200001b3 = 0xe;
memcpy((void*)0x200001b4, "\x63\x6d\x16\x35\x6b\xad\x40\x2f\xa3\x60\xfe\x65", 12);
*(uint8_t*)0x200001c0 = 0;
*(uint8_t*)0x200001c1 = 2;
*(uint8_t*)0x200001c2 = 0;
*(uint8_t*)0x200001c3 = 9;
memcpy((void*)0x200001c4, "\x45\xca\x6a\x9e\xf7\x06\x2b", 7);
*(uint8_t*)0x200001cb = 0;
*(uint8_t*)0x200001cc = 0xf;
memcpy((void*)0x200001cd, "\x1d\xb9\x8b\x68\xa2\x40\xbe\x78\x6c\x15\xd1\x70\xf4", 13);
*(uint8_t*)0x200001da = 0;
*(uint8_t*)0x200001db = 0xf;
memcpy((void*)0x200001dc, "\x4a\xe0\xca\xec\x6d\x20\x27\x1a\xdf\xd7\x22\x44\x79", 13);
*(uint8_t*)0x200001e9 = 0;
*(uint8_t*)0x200001ea = 0x11;
memcpy((void*)0x200001eb, "\x2d\x6d\xeb\xe1\xd3\x1c\x0c\x39\x96\x54\x11\x65\xbd\x4c\x8c", 15);
*(uint8_t*)0x200001fa = 0x44;
*(uint8_t*)0x200001fb = 0x2c;
*(uint8_t*)0x200001fc = 0;
STORE_BY_BITMASK(uint8_t, , 0x200001fd, 3, 0, 4);
STORE_BY_BITMASK(uint8_t, , 0x200001fd, 0, 4, 4);
*(uint32_t*)0x200001fe = htobe32(-1);
*(uint32_t*)0x20000202 = htobe32(0);
*(uint32_t*)0x20000206 = htobe32(0);
*(uint32_t*)0x2000020a = htobe32(0);
*(uint8_t*)0x2000020e = 0xac;
*(uint8_t*)0x2000020f = 0x14;
*(uint8_t*)0x20000210 = 0x14;
*(uint8_t*)0x20000211 = 0;
*(uint32_t*)0x20000212 = htobe32(0);
*(uint32_t*)0x20000216 = htobe32(-1);
*(uint32_t*)0x2000021a = htobe32(0);
*(uint32_t*)0x2000021e = htobe32(0x7f000001);
*(uint32_t*)0x20000222 = htobe32(0);
*(uint8_t*)0x20000226 = 7;
*(uint8_t*)0x20000227 = 0xb;
*(uint8_t*)0x20000228 = 0;
*(uint32_t*)0x20000229 = htobe32(0x7f000001);
*(uint32_t*)0x2000022d = htobe32(0xe0000002);
	struct csum_inet csum_1;
	csum_inet_init(&csum_1);
csum_inet_update(&csum_1, (const uint8_t*)0x20000120, 276);
*(uint16_t*)0x2000012a = csum_inet_digest(&csum_1);
	syscall(__NR_ioctl, r[0], 0x89f3, 0x20000240ul);
	return 0;
}
