// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socket, 0x10ul, 3ul, 6);
	if (res != -1)
		r[0] = res;
*(uint64_t*)0x20000480 = 0;
*(uint32_t*)0x20000488 = 0;
*(uint64_t*)0x20000490 = 0x20000440;
*(uint64_t*)0x20000440 = 0x20000640;
*(uint32_t*)0x20000640 = 0xcc;
*(uint16_t*)0x20000644 = 0x1b;
*(uint16_t*)0x20000646 = 1;
*(uint32_t*)0x20000648 = 0;
*(uint32_t*)0x2000064c = 0;
*(uint32_t*)0x20000650 = htobe32(0xe0000002);
*(uint8_t*)0x20000660 = 0xfe;
*(uint8_t*)0x20000661 = 0x80;
memset((void*)0x20000662, 0, 13);
*(uint8_t*)0x2000066f = 0;
*(uint16_t*)0x20000670 = htobe16(0);
*(uint16_t*)0x20000672 = htobe16(0);
*(uint16_t*)0x20000674 = htobe16(0);
*(uint16_t*)0x20000676 = htobe16(0);
*(uint16_t*)0x20000678 = 0;
*(uint8_t*)0x2000067a = 0;
*(uint8_t*)0x2000067b = 0;
*(uint8_t*)0x2000067c = 0;
*(uint32_t*)0x20000680 = 0;
*(uint32_t*)0x20000684 = 0xee01;
*(uint64_t*)0x20000688 = 0;
*(uint64_t*)0x20000690 = 0;
*(uint64_t*)0x20000698 = 0;
*(uint64_t*)0x200006a0 = 0;
*(uint64_t*)0x200006a8 = 0;
*(uint64_t*)0x200006b0 = 0;
*(uint64_t*)0x200006b8 = 0;
*(uint64_t*)0x200006c0 = 0;
*(uint64_t*)0x200006c8 = 0;
*(uint64_t*)0x200006d0 = 0;
*(uint64_t*)0x200006d8 = 0;
*(uint64_t*)0x200006e0 = 0;
*(uint32_t*)0x200006e8 = 0;
*(uint32_t*)0x200006ec = 0;
*(uint8_t*)0x200006f0 = 0;
*(uint8_t*)0x200006f1 = 0;
*(uint8_t*)0x200006f2 = 0;
*(uint8_t*)0x200006f3 = 0;
*(uint8_t*)0x200006f8 = 0;
*(uint16_t*)0x20000700 = 0xc;
*(uint16_t*)0x20000702 = 8;
*(uint16_t*)0x20000704 = 8;
*(uint16_t*)0x20000706 = 8;
*(uint8_t*)0x20000708 = 0;
*(uint8_t*)0x20000709 = 0;
*(uint16_t*)0x2000070a = 0;
*(uint64_t*)0x20000448 = 0xcc;
*(uint64_t*)0x20000498 = 1;
*(uint64_t*)0x200004a0 = 0;
*(uint64_t*)0x200004a8 = 0;
*(uint32_t*)0x200004b0 = 0;
	syscall(__NR_sendmsg, r[0], 0x20000480ul, 0ul);
	return 0;
}
