// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = syscall(__NR_socket, 0x10ul, 3ul, 0);
	if (res != -1)
		r[0] = res;
*(uint64_t*)0x20009100 = 0;
*(uint32_t*)0x20009108 = 0;
*(uint64_t*)0x20009110 = 0x20001d80;
*(uint64_t*)0x20001d80 = 0x20000000;
*(uint32_t*)0x20000000 = 0x1c;
*(uint16_t*)0x20000004 = 0x5e;
*(uint16_t*)0x20000006 = 0x9355;
*(uint32_t*)0x20000008 = 0;
*(uint32_t*)0x2000000c = 0;
memcpy((void*)0x20000010, "\x67\x3a\x04\xba\xe1\x5f\x28\x36\xd0", 9);
*(uint64_t*)0x20001d88 = 0x1c;
*(uint64_t*)0x20009118 = 1;
*(uint64_t*)0x20009120 = 0;
*(uint64_t*)0x20009128 = 0;
*(uint32_t*)0x20009130 = 0;
	syscall(__NR_sendmsg, r[0], 0x20009100ul, 0ul);
	return 0;
}
