// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);

memcpy((void*)0x20000000, "logon\000", 6);
memcpy((void*)0x20000140, "fscrypt:", 8);
memcpy((void*)0x20000148, "0000111122223333", 16);
*(uint8_t*)0x20000158 = 0;
*(uint32_t*)0x20000180 = 0;
memcpy((void*)0x20000184, "\x40\x6e\x23\xa1\xe3\x4e\x13\x41\x18\x31\x64\x3e\x83\xd7\x98\x40\x57\x9c\xb2\x97\xfe\x86\x30\x77\xc6\x53\x1e\xbb\x74\xf4\xe0\xfe\x88\x82\x16\x2c\xd2\x3c\x52\xc2\x61\x10\x21\xfc\xc4\x97\xb9\x84\x40\x59\x49\xf2\x2e\x23\x22\xc4\xc4\xec\xb2\xee\x3d\xfa\x7d\xa6", 64);
*(uint32_t*)0x200001c4 = 0;
	syscall(__NR_add_key, 0x20000000ul, 0x20000140ul, 0x20000180ul, 0x48ul, -1);
	return 0;
}
