// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

#define BITMASK(bf_off,bf_len) (((1ull << (bf_len)) - 1) << (bf_off))
#define STORE_BY_BITMASK(type,htobe,addr,val,bf_off,bf_len) *(type*)(addr) = htobe((htobe(*(type*)(addr)) & ~BITMASK((bf_off), (bf_len))) | (((type)(val) << (bf_off)) & BITMASK((bf_off), (bf_len))))

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
memcpy((void*)0x200001c0, "/dev/snd/seq\000", 13);
	res = syscall(__NR_openat, 0xffffffffffffff9cul, 0x200001c0ul, 0x80002ul, 0);
	if (res != -1)
		r[0] = res;
*(uint32_t*)0x20000000 = 0;
*(uint32_t*)0x20000004 = 0;
STORE_BY_BITMASK(uint32_t, , 0x20000008, 0, 0, 1);
memcpy((void*)0x20000009, "queue0\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000", 64);
*(uint32_t*)0x2000004c = 0;
memset((void*)0x20000050, 0, 60);
	syscall(__NR_ioctl, r[0], 0xc08c5332, 0x20000000ul);
*(uint8_t*)0x200000c0 = 0;
*(uint8_t*)0x200000c1 = 0;
*(uint8_t*)0x200000c2 = 0;
*(uint8_t*)0x200000c3 = 0;
*(uint32_t*)0x200000c4 = 0x400;
*(uint8_t*)0x200000cc = 0;
*(uint8_t*)0x200000cd = 0;
*(uint8_t*)0x200000ce = 0;
*(uint8_t*)0x200000cf = 0;
*(uint32_t*)0x200000d0 = 0;
*(uint32_t*)0x200000d4 = 0;
*(uint32_t*)0x200000d8 = 0;
	syscall(__NR_write, r[0], 0x200000c0ul, 0x1cul);
*(uint32_t*)0x200002c0 = 0x362;
*(uint32_t*)0x200002c4 = 0;
*(uint8_t*)0x200002cc = 0;
*(uint8_t*)0x200002cd = 0;
*(uint8_t*)0x200002ce = 0;
*(uint8_t*)0x200002cf = 0;
*(uint32_t*)0x200002d0 = 0;
*(uint8_t*)0x200002d4 = 2;
memset((void*)0x200002d8, 0, 40);
	syscall(__NR_ioctl, r[0], 0x4040534e, 0x200002c0ul);
	return 0;
}
