// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

#ifndef __NR_io_uring_setup
#define __NR_io_uring_setup 425
#endif

#define SIZEOF_IO_URING_SQE 64
#define SIZEOF_IO_URING_CQE 16
#define SQ_HEAD_OFFSET 0
#define SQ_TAIL_OFFSET 64
#define SQ_RING_MASK_OFFSET 256
#define SQ_RING_ENTRIES_OFFSET 264
#define SQ_FLAGS_OFFSET 276
#define SQ_DROPPED_OFFSET 272
#define CQ_HEAD_OFFSET 128
#define CQ_TAIL_OFFSET 192
#define CQ_RING_MASK_OFFSET 260
#define CQ_RING_ENTRIES_OFFSET 268
#define CQ_RING_OVERFLOW_OFFSET 284
#define CQ_FLAGS_OFFSET 280
#define CQ_CQES_OFFSET 320

struct io_sqring_offsets {
	uint32_t head;
	uint32_t tail;
	uint32_t ring_mask;
	uint32_t ring_entries;
	uint32_t flags;
	uint32_t dropped;
	uint32_t array;
	uint32_t resv1;
	uint64_t resv2;
};

struct io_cqring_offsets {
	uint32_t head;
	uint32_t tail;
	uint32_t ring_mask;
	uint32_t ring_entries;
	uint32_t overflow;
	uint32_t cqes;
	uint64_t resv[2];
};

struct io_uring_params {
	uint32_t sq_entries;
	uint32_t cq_entries;
	uint32_t flags;
	uint32_t sq_thread_cpu;
	uint32_t sq_thread_idle;
	uint32_t features;
	uint32_t resv[4];
	struct io_sqring_offsets sq_off;
	struct io_cqring_offsets cq_off;
};

#define IORING_OFF_SQ_RING 0
#define IORING_OFF_SQES 0x10000000ULL

static long syz_io_uring_setup(volatile long a0, volatile long a1, volatile long a2, volatile long a3, volatile long a4, volatile long a5)
{
	uint32_t entries = (uint32_t)a0;
	struct io_uring_params* setup_params = (struct io_uring_params*)a1;
	void* vma1 = (void*)a2;
	void* vma2 = (void*)a3;
	void** ring_ptr_out = (void**)a4;
	void** sqes_ptr_out = (void**)a5;
	uint32_t fd_io_uring = syscall(__NR_io_uring_setup, entries, setup_params);
	uint32_t sq_ring_sz = setup_params->sq_off.array + setup_params->sq_entries * sizeof(uint32_t);
	uint32_t cq_ring_sz = setup_params->cq_off.cqes + setup_params->cq_entries * SIZEOF_IO_URING_CQE;
	uint32_t ring_sz = sq_ring_sz > cq_ring_sz ? sq_ring_sz : cq_ring_sz;
	*ring_ptr_out = mmap(vma1, ring_sz, PROT_READ | PROT_WRITE, MAP_SHARED | MAP_POPULATE | MAP_FIXED, fd_io_uring, IORING_OFF_SQ_RING);
	uint32_t sqes_sz = setup_params->sq_entries * SIZEOF_IO_URING_SQE;
	*sqes_ptr_out = mmap(vma2, sqes_sz, PROT_READ | PROT_WRITE, MAP_SHARED | MAP_POPULATE | MAP_FIXED, fd_io_uring, IORING_OFF_SQES);
	return fd_io_uring;
}

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
*(uint32_t*)0x20000004 = 0;
*(uint32_t*)0x20000008 = 0;
*(uint32_t*)0x2000000c = 0;
*(uint32_t*)0x20000010 = 0;
*(uint32_t*)0x20000018 = -1;
memset((void*)0x2000001c, 0, 12);
syz_io_uring_setup(0x5014, 0x20000000, 0x20ffc000, 0x20ffd000, 0, 0);
	res = syscall(__NR_socket, 0xaul, 3ul, 9);
	if (res != -1)
		r[0] = res;
*(uint64_t*)0x20003880 = 0x20000000;
*(uint16_t*)0x20000000 = 0;
*(uint16_t*)0x20000002 = 0;
*(uint32_t*)0x20000004 = 0;
*(uint32_t*)0x20000008 = 0;
*(uint32_t*)0x20003888 = 0x80;
*(uint64_t*)0x20003890 = 0;
*(uint64_t*)0x20003898 = 0;
*(uint64_t*)0x200038a0 = 0x20000200;
memcpy((void*)0x20000200, "\xc8\x00\x00\x00\x00\x00\x00\x00\x84\x00\x00\x00\x01\x04\x00\x00\x6d\x81\xe4\x83\xea\x66\xe4\xfc\x46\xff\xff\x00\x00\x9d\x76\xef\x82\x41\x7b\x4b\x52\x38\xca\x78\x34\x6e\xcd\xc8\x01\x1f\x1f\xe2\xe2\xc4\xa4\x80\xd6\x17\x9b\x9c\xf0\x31\x0b\xae\x45\x4d\x8c\x72\x23\x93\x2b\x57\x71\xdd\x32\xab\x71\x88\x2f\xed\x5c\x00\xac\x6e\x41\x6f\x69\x7c\xbe\xeb\x83\xe7\x56\x4a\x34\x9b\x18\x84\x94\xd9\x92\xa9\xf3\x74\x7d\xdb\xf2\x5d\x6d\xfd\x87\x79\xdd\x78\xf4\x0c\xc3\xe2\x3f\xe6\xd1\xed\xbb\xaa\x62\x7e\xf8\xc4\x80\xfa\x98\x8d\x4d\x69\xa6\xb0\xf3\x05\x39\xc1\x42\x98\xad\xd2\x01\xfb\x5f\x97\x0c\xbf\xaf\x5f\x45\x88\xaa\xeb\x84\x20\xd9\x38\xbb\x09\x00\x00\x00\xc8\xca\x1b\x61\xc0\x34\xa7\xe4\x41\xca\xc3\x41\x38\x39\x0c\xcf\x5f\xb2\x6a\xd5\x38\xb6\xda\x1e\x17\xba\xbf\x3f\x46\x98\x52\x36\x86\x60\xd4\xdf\x37\x9f\x00\x10\x10", 202);
*(uint64_t*)0x200038a8 = 0x10d8;
*(uint32_t*)0x200038b0 = 0;
*(uint32_t*)0x200038b8 = 0;
	syscall(__NR_sendmmsg, r[0], 0x20003880ul, 1ul, 0ul);
	return 0;
}
