// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <errno.h>
#include <fcntl.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/ioctl.h>
#include <sys/mount.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

#include <linux/loop.h>

#ifndef __NR_memfd_create
#define __NR_memfd_create 319
#endif

static unsigned long long procid;

struct fs_image_segment {
	void* data;
	uintptr_t size;
	uintptr_t offset;
};
static int setup_loop_device(long unsigned size, long unsigned nsegs, struct fs_image_segment* segs, const char* loopname, int* memfd_p, int* loopfd_p)
{
	int err = 0, loopfd = -1;
	int memfd = syscall(__NR_memfd_create, "syzkaller", 0);
	if (memfd == -1) {
		err = errno;
		goto error;
	}
	if (ftruncate(memfd, size)) {
		err = errno;
		goto error_close_memfd;
	}
	for (size_t i = 0; i < nsegs; i++) {
		if (pwrite(memfd, segs[i].data, segs[i].size, segs[i].offset) < 0) {
		}
	}
	loopfd = open(loopname, O_RDWR);
	if (loopfd == -1) {
		err = errno;
		goto error_close_memfd;
	}
	if (ioctl(loopfd, LOOP_SET_FD, memfd)) {
		if (errno != EBUSY) {
			err = errno;
			goto error_close_loop;
		}
		ioctl(loopfd, LOOP_CLR_FD, 0);
		usleep(1000);
		if (ioctl(loopfd, LOOP_SET_FD, memfd)) {
			err = errno;
			goto error_close_loop;
		}
	}
	*memfd_p = memfd;
	*loopfd_p = loopfd;
	return 0;

error_close_loop:
	close(loopfd);
error_close_memfd:
	close(memfd);
error:
	errno = err;
	return -1;
}

static long syz_mount_image(volatile long fsarg, volatile long dir, volatile unsigned long size, volatile unsigned long nsegs, volatile long segments, volatile long flags, volatile long optsarg, volatile long change_dir)
{
	struct fs_image_segment* segs = (struct fs_image_segment*)segments;
	int res = -1, err = 0, loopfd = -1, memfd = -1, need_loop_device = !!segs;
	char* mount_opts = (char*)optsarg;
	char* target = (char*)dir;
	char* fs = (char*)fsarg;
	char* source = NULL;
	char loopname[64];
	if (need_loop_device) {
		memset(loopname, 0, sizeof(loopname));
		snprintf(loopname, sizeof(loopname), "/dev/loop%llu", procid);
		if (setup_loop_device(size, nsegs, segs, loopname, &memfd, &loopfd) == -1)
			return -1;
		source = loopname;
	}
	mkdir(target, 0777);
	char opts[256];
	memset(opts, 0, sizeof(opts));
	if (strlen(mount_opts) > (sizeof(opts) - 32)) {
	}
	strncpy(opts, mount_opts, sizeof(opts) - 32);
	if (strcmp(fs, "iso9660") == 0) {
		flags |= MS_RDONLY;
	} else if (strncmp(fs, "ext", 3) == 0) {
		if (strstr(opts, "errors=panic") || strstr(opts, "errors=remount-ro") == 0)
			strcat(opts, ",errors=continue");
	} else if (strcmp(fs, "xfs") == 0) {
		strcat(opts, ",nouuid");
	}
	res = mount(source, target, fs, flags, opts);
	if (res == -1) {
		err = errno;
		goto error_clear_loop;
	}
	res = open(target, O_RDONLY | O_DIRECTORY);
	if (res == -1) {
		err = errno;
		goto error_clear_loop;
	}
	if (change_dir) {
		res = chdir(target);
		if (res == -1) {
			err = errno;
		}
	}

error_clear_loop:
	if (need_loop_device) {
		ioctl(loopfd, LOOP_CLR_FD, 0);
		close(loopfd);
		close(memfd);
	}
	errno = err;
	return res;
}

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);

memcpy((void*)0x20000040, "./file0\000", 8);
syz_mount_image(0, 0x20000040, 0, 0, 0x20000000, 0, 0, 0);
memcpy((void*)0x20000080, "./file0\000", 8);
memcpy((void*)0x20000140, "./file0\000", 8);
	syscall(__NR_mount, 0x20000080ul, 0x20000140ul, 0ul, 0x281042ul, 0ul);
memcpy((void*)0x20000100, "ext4\000", 5);
memcpy((void*)0x20000180, "./file0\000", 8);
*(uint64_t*)0x20000640 = 0x20000400;
memcpy((void*)0x20000400, "\x93\xeb\x35\x17\x95\x02", 6);
*(uint64_t*)0x20000648 = 6;
*(uint64_t*)0x20000650 = 0;
memcpy((void*)0x20000880, "grpjquota", 9);
*(uint8_t*)0x20000889 = 0x3d;
memcpy((void*)0x2000088a, "./file0", 7);
*(uint8_t*)0x20000891 = 0x2c;
memcpy((void*)0x20000892, "usrjquota", 9);
*(uint8_t*)0x2000089b = 0x3d;
*(uint8_t*)0x2000089c = 0x2c;
memcpy((void*)0x2000089d, "permit_directio", 15);
*(uint8_t*)0x200008ac = 0x2c;
memcpy((void*)0x200008ad, "obj_user", 8);
*(uint8_t*)0x200008b5 = 0x3d;
memcpy((void*)0x200008b6, "/\\{", 3);
*(uint8_t*)0x200008b9 = 0x2c;
memcpy((void*)0x200008ba, "context", 7);
*(uint8_t*)0x200008c1 = 0x3d;
memcpy((void*)0x200008c2, "user_u", 6);
*(uint8_t*)0x200008c8 = 0x2c;
memcpy((void*)0x200008c9, "context", 7);
*(uint8_t*)0x200008d0 = 0x3d;
memcpy((void*)0x200008d1, "user_u", 6);
*(uint8_t*)0x200008d7 = 0x2c;
memcpy((void*)0x200008d8, "fsuuid", 6);
*(uint8_t*)0x200008de = 0x3d;
*(uint8_t*)0x200008df = 0x33;
*(uint8_t*)0x200008e0 = 0;
*(uint8_t*)0x200008e1 = 0x33;
*(uint8_t*)0x200008e2 = 0x33;
*(uint8_t*)0x200008e3 = 0;
*(uint8_t*)0x200008e4 = 0x31;
*(uint8_t*)0x200008e5 = 0;
*(uint8_t*)0x200008e6 = 0;
*(uint8_t*)0x200008e7 = 0x2d;
*(uint8_t*)0x200008e8 = 0x62;
*(uint8_t*)0x200008e9 = 0x35;
*(uint8_t*)0x200008ea = 0x65;
*(uint8_t*)0x200008eb = 0x39;
*(uint8_t*)0x200008ec = 0x2d;
*(uint8_t*)0x200008ed = 0x37;
*(uint8_t*)0x200008ee = 0;
*(uint8_t*)0x200008ef = 0x39;
*(uint8_t*)0x200008f0 = 0x34;
*(uint8_t*)0x200008f1 = 0x2d;
*(uint8_t*)0x200008f2 = 0x37;
*(uint8_t*)0x200008f3 = 0x31;
*(uint8_t*)0x200008f4 = 0x39;
*(uint8_t*)0x200008f5 = 0x38;
*(uint8_t*)0x200008f6 = 0x2d;
*(uint8_t*)0x200008f7 = 0x61;
*(uint8_t*)0x200008f8 = 0x38;
*(uint8_t*)0x200008f9 = 0x39;
*(uint8_t*)0x200008fa = 0;
*(uint8_t*)0x200008fb = 0x63;
*(uint8_t*)0x200008fc = 0x32;
*(uint8_t*)0x200008fd = 0x37;
*(uint8_t*)0x200008fe = 0x65;
*(uint8_t*)0x200008ff = 0x2c;
memcpy((void*)0x20000900, "rootcontext", 11);
*(uint8_t*)0x2000090b = 0x3d;
memcpy((void*)0x2000090c, "unconfined_u", 12);
*(uint8_t*)0x20000918 = 0x2c;
*(uint8_t*)0x20000919 = 0;
syz_mount_image(0x20000100, 0x20000180, 0x7ed6, 1, 0x20000640, 0x80000, 0x20000880, 0);
	return 0;
}
